package com.scttsc.business.model;

import com.scttsc.admin.model.City;
import com.scttsc.baselibs.model.Cons;
import com.scttsc.common.util.DateUtils;

import java.math.BigDecimal;
import java.util.Date;

public class Bbu {
  
    private BigDecimal intId;
    private String name;
    private String bbuNo;
    private BigDecimal longitude;
    private BigDecimal latitude;
    private String btsName;
    private String bscName;
    private BigDecimal btsId;
    private String circuitroomOwnership;
    private String transOwnership;
    private String vendorBtstype;
    private BigDecimal cityId;
    private BigDecimal countyId;
    private BigDecimal relatedBts;
    private BigDecimal isShare;
    private BigDecimal bbuType;
    private BigDecimal relateWybts;
    private BigDecimal manualFlag;
    private BigDecimal deleteFlag;
    private Long deleteResoncode;
    private String deleteText;
    private Date deletetime;
    private Date updatetime;
    private Cons cons;
    private String highTrainFlag;//高铁标识
    private Integer redLineFlag;//红线标识
    private String redLineFlagStr;

    private int shareBbuCount;//共站BBU数量
    
    //冗余
    private String cityName;//本地网名称
    private City city;//本地网
    private City country;//区县

    private String deleteTimeStr;
    private String updatetimeStr;
    
    
    //冗余c_bts字段信息

    
    
    private String mscName;
    private String useStatus;
    private String doBts;


    private CBts cBts;//关联的c_bts的int_id数据信息



    //冗余告警信息
    private String alarmName;//告警名称
    private String alarmCode;//告警代码
    private String alarmLevel;//告警级别
    private String alarmTime;//告警时间
    
  
    

    public Cons getCons() {
        return cons;
    }

    public void setCons(Cons cons) {
        this.cons = cons;
    }

    public String getDeleteText() {
        return deleteText;
    }

    public void setDeleteText(String deleteText) {
        this.deleteText = deleteText;
    }

    public Long getDeleteResoncode() {
        return deleteResoncode;
    }

    public void setDeleteResoncode(Long deleteResoncode) {
        this.deleteResoncode = deleteResoncode;
    }




    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BBU.INT_ID
     *
     * @return the value of WY_BBU.INT_ID
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public BigDecimal getIntId() {
        return intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BBU.INT_ID
     *
     * @param intId the value for WY_BBU.INT_ID
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public void setIntId(BigDecimal intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BBU.NAME
     *
     * @return the value of WY_BBU.NAME
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BBU.NAME
     *
     * @param name the value for WY_BBU.NAME
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BBU.BBU_NO
     *
     * @return the value of WY_BBU.BBU_NO
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public String getBbuNo() {
        return bbuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BBU.BBU_NO
     *
     * @param bbuNo the value for WY_BBU.BBU_NO
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public void setBbuNo(String bbuNo) {
        this.bbuNo = bbuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BBU.LONGITUDE
     *
     * @return the value of WY_BBU.LONGITUDE
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BBU.LONGITUDE
     *
     * @param longitude the value for WY_BBU.LONGITUDE
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BBU.LATITUDE
     *
     * @return the value of WY_BBU.LATITUDE
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BBU.LATITUDE
     *
     * @param latitude the value for WY_BBU.LATITUDE
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BBU.BTS_NAME
     *
     * @return the value of WY_BBU.BTS_NAME
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public String getBtsName() {
        return btsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BBU.BTS_NAME
     *
     * @param btsName the value for WY_BBU.BTS_NAME
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public void setBtsName(String btsName) {
        this.btsName = btsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BBU.BSC_NAME
     *
     * @return the value of WY_BBU.BSC_NAME
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public String getBscName() {
        return bscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BBU.BSC_NAME
     *
     * @param bscName the value for WY_BBU.BSC_NAME
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public void setBscName(String bscName) {
        this.bscName = bscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BBU.BTS_ID
     *
     * @return the value of WY_BBU.BTS_ID
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public BigDecimal getBtsId() {
        return btsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BBU.BTS_ID
     *
     * @param btsId the value for WY_BBU.BTS_ID
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public void setBtsId(BigDecimal btsId) {
        this.btsId = btsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BBU.CIRCUITROOM_OWNERSHIP
     *
     * @return the value of WY_BBU.CIRCUITROOM_OWNERSHIP
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public String getCircuitroomOwnership() {
        return circuitroomOwnership;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BBU.CIRCUITROOM_OWNERSHIP
     *
     * @param circuitroomOwnership the value for WY_BBU.CIRCUITROOM_OWNERSHIP
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public void setCircuitroomOwnership(String circuitroomOwnership) {
        this.circuitroomOwnership = circuitroomOwnership;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BBU.TRANS_OWNERSHIP
     *
     * @return the value of WY_BBU.TRANS_OWNERSHIP
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public String getTransOwnership() {
        return transOwnership;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BBU.TRANS_OWNERSHIP
     *
     * @param transOwnership the value for WY_BBU.TRANS_OWNERSHIP
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public void setTransOwnership(String transOwnership) {
        this.transOwnership = transOwnership;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BBU.VENDOR_BTSTYPE
     *
     * @return the value of WY_BBU.VENDOR_BTSTYPE
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public String getVendorBtstype() {
        return vendorBtstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BBU.VENDOR_BTSTYPE
     *
     * @param vendorBtstype the value for WY_BBU.VENDOR_BTSTYPE
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public void setVendorBtstype(String vendorBtstype) {
        this.vendorBtstype = vendorBtstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BBU.CITY_ID
     *
     * @return the value of WY_BBU.CITY_ID
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public BigDecimal getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BBU.CITY_ID
     *
     * @param cityId the value for WY_BBU.CITY_ID
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public void setCityId(BigDecimal cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BBU.COUNTY_ID
     *
     * @return the value of WY_BBU.COUNTY_ID
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public BigDecimal getCountyId() {
        return countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BBU.COUNTY_ID
     *
     * @param countyId the value for WY_BBU.COUNTY_ID
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public void setCountyId(BigDecimal countyId) {
        this.countyId = countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BBU.RELATED_BTS
     *
     * @return the value of WY_BBU.RELATED_BTS
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public BigDecimal getRelatedBts() {
        return relatedBts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BBU.RELATED_BTS
     *
     * @param relatedBts the value for WY_BBU.RELATED_BTS
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public void setRelatedBts(BigDecimal relatedBts) {
        this.relatedBts = relatedBts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BBU.IS_SHARE
     *
     * @return the value of WY_BBU.IS_SHARE
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public BigDecimal getIsShare() {
        return isShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BBU.IS_SHARE
     *
     * @param isShare the value for WY_BBU.IS_SHARE
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public void setIsShare(BigDecimal isShare) {
        this.isShare = isShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BBU.BBU_TYPE
     *
     * @return the value of WY_BBU.BBU_TYPE
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public BigDecimal getBbuType() {
        return bbuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BBU.BBU_TYPE
     *
     * @param bbuType the value for WY_BBU.BBU_TYPE
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public void setBbuType(BigDecimal bbuType) {
        this.bbuType = bbuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BBU.RELATE_WYBTS
     *
     * @return the value of WY_BBU.RELATE_WYBTS
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public BigDecimal getRelateWybts() {
        return relateWybts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BBU.RELATE_WYBTS
     *
     * @param relateWybts the value for WY_BBU.RELATE_WYBTS
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public void setRelateWybts(BigDecimal relateWybts) {
        this.relateWybts = relateWybts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BBU.MANUAL_FLAG
     *
     * @return the value of WY_BBU.MANUAL_FLAG
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public BigDecimal getManualFlag() {
        return manualFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BBU.MANUAL_FLAG
     *
     * @param manualFlag the value for WY_BBU.MANUAL_FLAG
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public void setManualFlag(BigDecimal manualFlag) {
        this.manualFlag = manualFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BBU.DELETE_FLAG
     *
     * @return the value of WY_BBU.DELETE_FLAG
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public BigDecimal getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BBU.DELETE_FLAG
     *
     * @param deleteFlag the value for WY_BBU.DELETE_FLAG
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public void setDeleteFlag(BigDecimal deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    public Date getDeletetime() {
        return deletetime;
    }

    public void setDeletetime(Date deletetime) {
        this.deletetime = deletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BBU.UPDATETIME
     *
     * @return the value of WY_BBU.UPDATETIME
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BBU.UPDATETIME
     *
     * @param updatetime the value for WY_BBU.UPDATETIME
     *
     * @mbggenerated Wed Apr 03 15:29:57 CST 2013
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

   
    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public City getCountry() {
        return country;
    }

    public void setCountry(City country) {
        this.country = country;
    }

	public String getMscName() {
		return mscName;
	}

	public void setMscName(String mscName) {
		this.mscName = mscName;
	}

	public String getUseStatus() {
		return useStatus;
	}

	public void setUseStatus(String useStatus) {
		this.useStatus = useStatus;
	}

	public String getDoBts() {
		return doBts;
	}

	public void setDoBts(String doBts) {
		this.doBts = doBts;
	}

    public BigDecimal getShare() {
        return isShare;
    }

    public void setShare(BigDecimal share) {
        isShare = share;
    }

    public CBts getcBts() {
        return cBts;
    }

    public void setcBts(CBts cBts) {
        this.cBts = cBts;
    }


    public String getDeleteTimeStr() {
        return deletetime==null?"": DateUtils.DateToStr(deletetime,"yyyy-MM-dd");
    }

    public void setDeleteTimeStr(String deleteTimeStr) {
        this.deleteTimeStr = deleteTimeStr;
    }

    public int getShareBbuCount() {
        return shareBbuCount;
    }

    public void setShareBbuCount(int shareBbuCount) {
        this.shareBbuCount = shareBbuCount;
    }


    public String getAlarmName() {
        return alarmName;
    }

    public void setAlarmName(String alarmName) {
        this.alarmName = alarmName;
    }

    public String getAlarmCode() {
        return alarmCode;
    }

    public void setAlarmCode(String alarmCode) {
        this.alarmCode = alarmCode;
    }

    public String getAlarmLevel() {
        return alarmLevel;
    }

    public void setAlarmLevel(String alarmLevel) {
        this.alarmLevel = alarmLevel;
    }

    public String getAlarmTime() {
        return alarmTime;
    }

    public void setAlarmTime(String alarmTime) {
        this.alarmTime = alarmTime;
    }


    public String getUpdatetimeStr() {
        return updatetime==null?"": DateUtils.DateToStr(updatetime,"yyyy-MM-dd");
    }

    public void setUpdatetimeStr(String updatetimeStr) {
        this.updatetimeStr = updatetimeStr;
    }

    public City getCity() {
        return city;
    }

    public void setCity(City city) {
        this.city = city;
    }

    public String getHighTrainFlag() {
        return highTrainFlag;
    }

    public void setHighTrainFlag(String highTrainFlag) {
        this.highTrainFlag = highTrainFlag;
    }

    public Integer getRedLineFlag() {
        return redLineFlag;
    }

    public void setRedLineFlag(Integer redLineFlag) {
        this.redLineFlag = redLineFlag;
    }

    public String getRedLineFlagStr() {
        if (redLineFlag == null) {
            return "";
        }
        switch (redLineFlag) {
            case 1:
                redLineFlagStr = "红线内";
                break;
            case 2:
                redLineFlagStr = "红线外";
                break;
            default:
                break;
        }
        return redLineFlagStr;
    }

    public void setRedLineFlagStr(String redLineFlagStr) {
        this.redLineFlagStr = redLineFlagStr;
    }
}