package com.scttsc.business.model;

import java.math.BigDecimal;
import java.util.Date;

import com.scttsc.baselibs.model.Cons;

public class BbuManual extends Entity{

	private Long intId;
	private String name;
	private String bscName;
	private Integer btsId;
	private Integer installPosCode;
	private String sharFlag;
	private String sharName;
	private String address;
	private String openTime;
	private String tranModel;
	private String tranFac;
	private String tranUpsitename;
	private String tranDownsitename;
	private String tranNetprotect;
	private String tranIsnode;
	private Integer tranSitenum;
	private String sourModel;
	private String sourFac;
	private String sourModuleModel;
	private Integer sourModuleNum;
	private Integer sourCapa;
	private String boxModel;
	private String boxFac;
	private String cellModel;
	private String cellFac;
	private Integer cellCapa;
	private Integer cellNum;
	private Double cellPower; //设备总耗电
	private Double cellDuar;  //设备运行时长
	private String cellUstime;
	private String acModel;
	private String acFac;
	private Integer acNum;
	private String dhModel;
	private String dhFac;
	private String xfModel;
	private String xfFac;
	private Integer mrStrut;//机房机构
	private Double mrLength;//机房长度
	private Double mrWidth;
	private Double mrHigh;
	private String mrOwner;
	private String mrPic;
	private String wdType;
	private String wdModel;
	private String wdFac;
	private String wdGds;
	private String oeType;
	private String oeModel;
	private String oePower;
	private String oeFac;
	private String remark;
	private Date updatetime;
	private Long updateuser;


    private BigDecimal longitude;
    private BigDecimal latitude;

    private String town;//乡镇
    private String village;//农村


    private Cons mrStrutCons;//机房机构



    public void setIgFields() {
       igFields.add("updatetime");
       igFields.add("mrStrutCons");
    }

    /**
     *
     * @param object
     * @return
     */
    public String compareEntity(Object object){
        return super.compareEntity(object);
    }

    public Long getIntId() {
        return intId;
    }

    public void setIntId(Long intId) {
        this.intId = intId;
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.NAME
	 * 
	 * @return the value of WY_BBU_MANUAL.NAME
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.NAME
	 * 
	 * @param name
	 *            the value for WY_BBU_MANUAL.NAME
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.BSC_NAME
	 * 
	 * @return the value of WY_BBU_MANUAL.BSC_NAME
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getBscName() {
		return bscName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.BSC_NAME
	 * 
	 * @param bscName
	 *            the value for WY_BBU_MANUAL.BSC_NAME
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setBscName(String bscName) {
		this.bscName = bscName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.BTS_ID
	 * 
	 * @return the value of WY_BBU_MANUAL.BTS_ID
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public Integer getBtsId() {
		return btsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.BTS_ID
	 * 
	 * @param btsId
	 *            the value for WY_BBU_MANUAL.BTS_ID
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setBtsId(Integer btsId) {
		this.btsId = btsId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.INSTALL_POS_CODE
	 * 
	 * @return the value of WY_BBU_MANUAL.INSTALL_POS_CODE
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public Integer getInstallPosCode() {
		return installPosCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.INSTALL_POS_CODE
	 * 
	 * @param installPosCode
	 *            the value for WY_BBU_MANUAL.INSTALL_POS_CODE
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setInstallPosCode(Integer installPosCode) {
		this.installPosCode = installPosCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.SHAR_FLAG
	 * 
	 * @return the value of WY_BBU_MANUAL.SHAR_FLAG
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getSharFlag() {
		return sharFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.SHAR_FLAG
	 * 
	 * @param sharFlag
	 *            the value for WY_BBU_MANUAL.SHAR_FLAG
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setSharFlag(String sharFlag) {
		this.sharFlag = sharFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.SHAR_NAME
	 * 
	 * @return the value of WY_BBU_MANUAL.SHAR_NAME
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getSharName() {
		return sharName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.SHAR_NAME
	 * 
	 * @param sharName
	 *            the value for WY_BBU_MANUAL.SHAR_NAME
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setSharName(String sharName) {
		this.sharName = sharName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.ADDRESS
	 * 
	 * @return the value of WY_BBU_MANUAL.ADDRESS
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.ADDRESS
	 * 
	 * @param address
	 *            the value for WY_BBU_MANUAL.ADDRESS
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.OPEN_TIME
	 * 
	 * @return the value of WY_BBU_MANUAL.OPEN_TIME
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getOpenTime() {
		return openTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.OPEN_TIME
	 * 
	 * @param openTime
	 *            the value for WY_BBU_MANUAL.OPEN_TIME
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setOpenTime(String openTime) {
		this.openTime = openTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.TRAN_MODEL
	 * 
	 * @return the value of WY_BBU_MANUAL.TRAN_MODEL
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getTranModel() {
		return tranModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.TRAN_MODEL
	 * 
	 * @param tranModel
	 *            the value for WY_BBU_MANUAL.TRAN_MODEL
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setTranModel(String tranModel) {
		this.tranModel = tranModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.TRAN_FAC
	 * 
	 * @return the value of WY_BBU_MANUAL.TRAN_FAC
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getTranFac() {
		return tranFac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.TRAN_FAC
	 * 
	 * @param tranFac
	 *            the value for WY_BBU_MANUAL.TRAN_FAC
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setTranFac(String tranFac) {
		this.tranFac = tranFac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.TRAN_UPSITENAME
	 * 
	 * @return the value of WY_BBU_MANUAL.TRAN_UPSITENAME
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getTranUpsitename() {
		return tranUpsitename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.TRAN_UPSITENAME
	 * 
	 * @param tranUpsitename
	 *            the value for WY_BBU_MANUAL.TRAN_UPSITENAME
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setTranUpsitename(String tranUpsitename) {
		this.tranUpsitename = tranUpsitename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.TRAN_DOWNSITENAME
	 * 
	 * @return the value of WY_BBU_MANUAL.TRAN_DOWNSITENAME
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getTranDownsitename() {
		return tranDownsitename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.TRAN_DOWNSITENAME
	 * 
	 * @param tranDownsitename
	 *            the value for WY_BBU_MANUAL.TRAN_DOWNSITENAME
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setTranDownsitename(String tranDownsitename) {
		this.tranDownsitename = tranDownsitename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.TRAN_NETPROTECT
	 * 
	 * @return the value of WY_BBU_MANUAL.TRAN_NETPROTECT
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getTranNetprotect() {
		return tranNetprotect;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.TRAN_NETPROTECT
	 * 
	 * @param tranNetprotect
	 *            the value for WY_BBU_MANUAL.TRAN_NETPROTECT
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setTranNetprotect(String tranNetprotect) {
		this.tranNetprotect = tranNetprotect;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.TRAN_ISNODE
	 * 
	 * @return the value of WY_BBU_MANUAL.TRAN_ISNODE
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getTranIsnode() {
		return tranIsnode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.TRAN_ISNODE
	 * 
	 * @param tranIsnode
	 *            the value for WY_BBU_MANUAL.TRAN_ISNODE
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setTranIsnode(String tranIsnode) {
		this.tranIsnode = tranIsnode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.TRAN_SITENUM
	 * 
	 * @return the value of WY_BBU_MANUAL.TRAN_SITENUM
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public Integer getTranSitenum() {
		return tranSitenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.TRAN_SITENUM
	 * 
	 * @param tranSitenum
	 *            the value for WY_BBU_MANUAL.TRAN_SITENUM
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setTranSitenum(Integer tranSitenum) {
		this.tranSitenum = tranSitenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.SOUR_MODEL
	 * 
	 * @return the value of WY_BBU_MANUAL.SOUR_MODEL
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getSourModel() {
		return sourModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.SOUR_MODEL
	 * 
	 * @param sourModel
	 *            the value for WY_BBU_MANUAL.SOUR_MODEL
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setSourModel(String sourModel) {
		this.sourModel = sourModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.SOUR_FAC
	 * 
	 * @return the value of WY_BBU_MANUAL.SOUR_FAC
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getSourFac() {
		return sourFac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.SOUR_FAC
	 * 
	 * @param sourFac
	 *            the value for WY_BBU_MANUAL.SOUR_FAC
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setSourFac(String sourFac) {
		this.sourFac = sourFac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.SOUR_MODULE_MODEL
	 * 
	 * @return the value of WY_BBU_MANUAL.SOUR_MODULE_MODEL
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getSourModuleModel() {
		return sourModuleModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.SOUR_MODULE_MODEL
	 * 
	 * @param sourModuleModel
	 *            the value for WY_BBU_MANUAL.SOUR_MODULE_MODEL
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setSourModuleModel(String sourModuleModel) {
		this.sourModuleModel = sourModuleModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.SOUR_MODULE_NUM
	 * 
	 * @return the value of WY_BBU_MANUAL.SOUR_MODULE_NUM
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public Integer getSourModuleNum() {
		return sourModuleNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.SOUR_MODULE_NUM
	 * 
	 * @param sourModuleNum
	 *            the value for WY_BBU_MANUAL.SOUR_MODULE_NUM
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setSourModuleNum(Integer sourModuleNum) {
		this.sourModuleNum = sourModuleNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.SOUR_CAPA
	 * 
	 * @return the value of WY_BBU_MANUAL.SOUR_CAPA
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public Integer getSourCapa() {
		return sourCapa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.SOUR_CAPA
	 * 
	 * @param sourCapa
	 *            the value for WY_BBU_MANUAL.SOUR_CAPA
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setSourCapa(Integer sourCapa) {
		this.sourCapa = sourCapa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.BOX_MODEL
	 * 
	 * @return the value of WY_BBU_MANUAL.BOX_MODEL
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getBoxModel() {
		return boxModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.BOX_MODEL
	 * 
	 * @param boxModel
	 *            the value for WY_BBU_MANUAL.BOX_MODEL
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setBoxModel(String boxModel) {
		this.boxModel = boxModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.BOX_FAC
	 * 
	 * @return the value of WY_BBU_MANUAL.BOX_FAC
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getBoxFac() {
		return boxFac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.BOX_FAC
	 * 
	 * @param boxFac
	 *            the value for WY_BBU_MANUAL.BOX_FAC
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setBoxFac(String boxFac) {
		this.boxFac = boxFac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.CELL_MODEL
	 * 
	 * @return the value of WY_BBU_MANUAL.CELL_MODEL
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getCellModel() {
		return cellModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.CELL_MODEL
	 * 
	 * @param cellModel
	 *            the value for WY_BBU_MANUAL.CELL_MODEL
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setCellModel(String cellModel) {
		this.cellModel = cellModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.CELL_FAC
	 * 
	 * @return the value of WY_BBU_MANUAL.CELL_FAC
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getCellFac() {
		return cellFac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.CELL_FAC
	 * 
	 * @param cellFac
	 *            the value for WY_BBU_MANUAL.CELL_FAC
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setCellFac(String cellFac) {
		this.cellFac = cellFac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.CELL_CAPA
	 * 
	 * @return the value of WY_BBU_MANUAL.CELL_CAPA
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public Integer getCellCapa() {
		return cellCapa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.CELL_CAPA
	 * 
	 * @param cellCapa
	 *            the value for WY_BBU_MANUAL.CELL_CAPA
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setCellCapa(Integer cellCapa) {
		this.cellCapa = cellCapa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.CELL_NUM
	 * 
	 * @return the value of WY_BBU_MANUAL.CELL_NUM
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public Integer getCellNum() {
		return cellNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.CELL_NUM
	 * 
	 * @param cellNum
	 *            the value for WY_BBU_MANUAL.CELL_NUM
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setCellNum(Integer cellNum) {
		this.cellNum = cellNum;
	}

    public Double getCellPower() {
        return cellPower;
    }

    public void setCellPower(Double cellPower) {
        this.cellPower = cellPower;
    }

    public Double getCellDuar() {
        return cellDuar;
    }

    public void setCellDuar(Double cellDuar) {
        this.cellDuar = cellDuar;
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.CELL_USTIME
	 * 
	 * @return the value of WY_BBU_MANUAL.CELL_USTIME
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getCellUstime() {
		return cellUstime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.CELL_USTIME
	 * 
	 * @param cellUstime
	 *            the value for WY_BBU_MANUAL.CELL_USTIME
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setCellUstime(String cellUstime) {
		this.cellUstime = cellUstime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.AC_MODEL
	 * 
	 * @return the value of WY_BBU_MANUAL.AC_MODEL
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getAcModel() {
		return acModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.AC_MODEL
	 * 
	 * @param acModel
	 *            the value for WY_BBU_MANUAL.AC_MODEL
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setAcModel(String acModel) {
		this.acModel = acModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.AC_FAC
	 * 
	 * @return the value of WY_BBU_MANUAL.AC_FAC
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getAcFac() {
		return acFac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.AC_FAC
	 * 
	 * @param acFac
	 *            the value for WY_BBU_MANUAL.AC_FAC
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setAcFac(String acFac) {
		this.acFac = acFac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.AC_NUM
	 * 
	 * @return the value of WY_BBU_MANUAL.AC_NUM
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public Integer getAcNum() {
		return acNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.AC_NUM
	 * 
	 * @param acNum
	 *            the value for WY_BBU_MANUAL.AC_NUM
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setAcNum(Integer acNum) {
		this.acNum = acNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.DH_MODEL
	 * 
	 * @return the value of WY_BBU_MANUAL.DH_MODEL
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getDhModel() {
		return dhModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.DH_MODEL
	 * 
	 * @param dhModel
	 *            the value for WY_BBU_MANUAL.DH_MODEL
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setDhModel(String dhModel) {
		this.dhModel = dhModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.DH_FAC
	 * 
	 * @return the value of WY_BBU_MANUAL.DH_FAC
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getDhFac() {
		return dhFac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.DH_FAC
	 * 
	 * @param dhFac
	 *            the value for WY_BBU_MANUAL.DH_FAC
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setDhFac(String dhFac) {
		this.dhFac = dhFac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.XF_MODEL
	 * 
	 * @return the value of WY_BBU_MANUAL.XF_MODEL
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getXfModel() {
		return xfModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.XF_MODEL
	 * 
	 * @param xfModel
	 *            the value for WY_BBU_MANUAL.XF_MODEL
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setXfModel(String xfModel) {
		this.xfModel = xfModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.XF_FAC
	 * 
	 * @return the value of WY_BBU_MANUAL.XF_FAC
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getXfFac() {
		return xfFac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.XF_FAC
	 * 
	 * @param xfFac
	 *            the value for WY_BBU_MANUAL.XF_FAC
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setXfFac(String xfFac) {
		this.xfFac = xfFac;
	}

	
	public Integer getMrStrut() {
		return mrStrut;
	}

	public void setMrStrut(Integer mrStrut) {
		this.mrStrut = mrStrut;
	}

    public Double getMrLength() {
        return mrLength;
    }

    public void setMrLength(Double mrLength) {
        this.mrLength = mrLength;
    }

    public Double getMrWidth() {
        return mrWidth;
    }

    public void setMrWidth(Double mrWidth) {
        this.mrWidth = mrWidth;
    }

    public Double getMrHigh() {
        return mrHigh;
    }

    public void setMrHigh(Double mrHigh) {
        this.mrHigh = mrHigh;
    }

    public String getMrOwner() {
		return mrOwner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.MR_OWNER
	 * 
	 * @param mrOwner
	 *            the value for WY_BBU_MANUAL.MR_OWNER
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setMrOwner(String mrOwner) {
		this.mrOwner = mrOwner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.MR_PIC
	 * 
	 * @return the value of WY_BBU_MANUAL.MR_PIC
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getMrPic() {
		return mrPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.MR_PIC
	 * 
	 * @param mrPic
	 *            the value for WY_BBU_MANUAL.MR_PIC
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setMrPic(String mrPic) {
		this.mrPic = mrPic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.WD_TYPE
	 * 
	 * @return the value of WY_BBU_MANUAL.WD_TYPE
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getWdType() {
		return wdType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.WD_TYPE
	 * 
	 * @param wdType
	 *            the value for WY_BBU_MANUAL.WD_TYPE
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setWdType(String wdType) {
		this.wdType = wdType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.WD_MODEL
	 * 
	 * @return the value of WY_BBU_MANUAL.WD_MODEL
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getWdModel() {
		return wdModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.WD_MODEL
	 * 
	 * @param wdModel
	 *            the value for WY_BBU_MANUAL.WD_MODEL
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setWdModel(String wdModel) {
		this.wdModel = wdModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.WD_FAC
	 * 
	 * @return the value of WY_BBU_MANUAL.WD_FAC
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getWdFac() {
		return wdFac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.WD_FAC
	 * 
	 * @param wdFac
	 *            the value for WY_BBU_MANUAL.WD_FAC
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setWdFac(String wdFac) {
		this.wdFac = wdFac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.WD_GDS
	 * 
	 * @return the value of WY_BBU_MANUAL.WD_GDS
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getWdGds() {
		return wdGds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.WD_GDS
	 * 
	 * @param wdGds
	 *            the value for WY_BBU_MANUAL.WD_GDS
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setWdGds(String wdGds) {
		this.wdGds = wdGds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.OE_TYPE
	 * 
	 * @return the value of WY_BBU_MANUAL.OE_TYPE
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getOeType() {
		return oeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.OE_TYPE
	 * 
	 * @param oeType
	 *            the value for WY_BBU_MANUAL.OE_TYPE
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setOeType(String oeType) {
		this.oeType = oeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.OE_MODEL
	 * 
	 * @return the value of WY_BBU_MANUAL.OE_MODEL
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getOeModel() {
		return oeModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.OE_MODEL
	 * 
	 * @param oeModel
	 *            the value for WY_BBU_MANUAL.OE_MODEL
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setOeModel(String oeModel) {
		this.oeModel = oeModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.OE_POWER
	 * 
	 * @return the value of WY_BBU_MANUAL.OE_POWER
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getOePower() {
		return oePower;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.OE_POWER
	 * 
	 * @param oePower
	 *            the value for WY_BBU_MANUAL.OE_POWER
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setOePower(String oePower) {
		this.oePower = oePower;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.OE_FAC
	 * 
	 * @return the value of WY_BBU_MANUAL.OE_FAC
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getOeFac() {
		return oeFac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.OE_FAC
	 * 
	 * @param oeFac
	 *            the value for WY_BBU_MANUAL.OE_FAC
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setOeFac(String oeFac) {
		this.oeFac = oeFac;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.REMARK
	 * 
	 * @return the value of WY_BBU_MANUAL.REMARK
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.REMARK
	 * 
	 * @param remark
	 *            the value for WY_BBU_MANUAL.REMARK
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_BBU_MANUAL.UPDATETIME
	 * 
	 * @return the value of WY_BBU_MANUAL.UPDATETIME
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_BBU_MANUAL.UPDATETIME
	 * 
	 * @param updatetime
	 *            the value for WY_BBU_MANUAL.UPDATETIME
	 * 
	 * @mbggenerated Sun Apr 07 14:44:13 CST 2013
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

    public Long getUpdateuser() {
        return updateuser;
    }

    public void setUpdateuser(Long updateuser) {
        this.updateuser = updateuser;
    }

    public Cons getMrStrutCons() {
		return mrStrutCons;
	}

	public void setMrStrutCons(Cons mrStrutCons) {
		this.mrStrutCons = mrStrutCons;
	}


    public BigDecimal getLongitude() {
        return longitude;
    }

    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    public BigDecimal getLatitude() {
        return latitude;
    }

    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    public String getTown() {
        return town;
    }
    public void setTown(String town) {
        this.town = town;
    }
    public String getVillage() {
        return village;
    }
    public void setVillage(String village) {
        this.village = village;
    }
}