package com.scttsc.business.model;

import com.scttsc.admin.model.City;
import com.scttsc.baselibs.model.Cons;
import com.scttsc.common.util.DateUtils;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class Bts {

    private BigDecimal intId;
    public String name;
    private BigDecimal longitude;
    private BigDecimal latitude;
    private String isIndoor;
    private String isRru;
    private String btsName;
    private String bscName;
    private BigDecimal btsId;
    private String circuitroomOwnership;
    private String transOwnership;
    private String vendorBtstype;
    private BigDecimal cityId;
    private BigDecimal countyId;
    private BigDecimal relatedBts;
    private BigDecimal manualFlag;
    private BigDecimal deleteFlag;
    private Date deletetime;
    private Date updatetime;
    private String serviceLevel;

    private Long deleteResoncode;

    private String deleteText;


    //冗余
    private String cityName;//本地网名称
    private City city;//本地网
    private City country;//区县


    private String deleteTimeStr;

    private String updateTimeStr;


    List<Bbu> bbus;//共站BBU列表
    List<Cell> cells;//所带小区

    public Cons getCons() {
        return cons;
    }

    public void setCons(Cons cons) {
        this.cons = cons;
    }

    private Cons cons;

    public String getIndoor() {
        return isIndoor;
    }

    public void setIndoor(String indoor) {
        isIndoor = indoor;
    }

    public String getRru() {
        return isRru;
    }

    public void setRru(String rru) {
        isRru = rru;
    }

    public Long getDeleteResoncode() {
        return deleteResoncode;
    }

    public void setDeleteResoncode(Long deleteResoncode) {
        this.deleteResoncode = deleteResoncode;
    }

    public String getDeleteText() {
        return deleteText;
    }

    public void setDeleteText(String deleteText) {
        this.deleteText = deleteText;
    }


    public BigDecimal getIntId() {
        return intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BTS.INT_ID
     *
     * @param intId the value for WY_BTS.INT_ID
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public void setIntId(BigDecimal intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BTS.NAME
     *
     * @return the value of WY_BTS.NAME
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BTS.NAME
     *
     * @param name the value for WY_BTS.NAME
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BTS.LONGITUDE
     *
     * @return the value of WY_BTS.LONGITUDE
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BTS.LONGITUDE
     *
     * @param longitude the value for WY_BTS.LONGITUDE
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BTS.LATITUDE
     *
     * @return the value of WY_BTS.LATITUDE
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BTS.LATITUDE
     *
     * @param latitude the value for WY_BTS.LATITUDE
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BTS.IS_INDOOR
     *
     * @return the value of WY_BTS.IS_INDOOR
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public String getIsIndoor() {
        return isIndoor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BTS.IS_INDOOR
     *
     * @param isIndoor the value for WY_BTS.IS_INDOOR
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public void setIsIndoor(String isIndoor) {
        this.isIndoor = isIndoor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BTS.IS_RRU
     *
     * @return the value of WY_BTS.IS_RRU
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public String getIsRru() {
        return isRru;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BTS.IS_RRU
     *
     * @param isRru the value for WY_BTS.IS_RRU
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public void setIsRru(String isRru) {
        this.isRru = isRru;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BTS.BTS_NAME
     *
     * @return the value of WY_BTS.BTS_NAME
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public String getBtsName() {
        return btsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BTS.BTS_NAME
     *
     * @param btsName the value for WY_BTS.BTS_NAME
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public void setBtsName(String btsName) {
        this.btsName = btsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BTS.BSC_NAME
     *
     * @return the value of WY_BTS.BSC_NAME
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public String getBscName() {
        return bscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BTS.BSC_NAME
     *
     * @param bscName the value for WY_BTS.BSC_NAME
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public void setBscName(String bscName) {
        this.bscName = bscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BTS.BTS_ID
     *
     * @return the value of WY_BTS.BTS_ID
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public BigDecimal getBtsId() {
        return btsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BTS.BTS_ID
     *
     * @param btsId the value for WY_BTS.BTS_ID
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public void setBtsId(BigDecimal btsId) {
        this.btsId = btsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BTS.CIRCUITROOM_OWNERSHIP
     *
     * @return the value of WY_BTS.CIRCUITROOM_OWNERSHIP
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public String getCircuitroomOwnership() {
        return circuitroomOwnership;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BTS.CIRCUITROOM_OWNERSHIP
     *
     * @param circuitroomOwnership the value for WY_BTS.CIRCUITROOM_OWNERSHIP
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public void setCircuitroomOwnership(String circuitroomOwnership) {
        this.circuitroomOwnership = circuitroomOwnership;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BTS.TRANS_OWNERSHIP
     *
     * @return the value of WY_BTS.TRANS_OWNERSHIP
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public String getTransOwnership() {
        return transOwnership;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BTS.TRANS_OWNERSHIP
     *
     * @param transOwnership the value for WY_BTS.TRANS_OWNERSHIP
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public void setTransOwnership(String transOwnership) {
        this.transOwnership = transOwnership;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BTS.VENDOR_BTSTYPE
     *
     * @return the value of WY_BTS.VENDOR_BTSTYPE
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public String getVendorBtstype() {
        return vendorBtstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BTS.VENDOR_BTSTYPE
     *
     * @param vendorBtstype the value for WY_BTS.VENDOR_BTSTYPE
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public void setVendorBtstype(String vendorBtstype) {
        this.vendorBtstype = vendorBtstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BTS.CITY_ID
     *
     * @return the value of WY_BTS.CITY_ID
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public BigDecimal getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BTS.CITY_ID
     *
     * @param cityId the value for WY_BTS.CITY_ID
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public void setCityId(BigDecimal cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BTS.COUNTY_ID
     *
     * @return the value of WY_BTS.COUNTY_ID
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public BigDecimal getCountyId() {
        return countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BTS.COUNTY_ID
     *
     * @param countyId the value for WY_BTS.COUNTY_ID
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public void setCountyId(BigDecimal countyId) {
        this.countyId = countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BTS.RELATED_BTS
     *
     * @return the value of WY_BTS.RELATED_BTS
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public BigDecimal getRelatedBts() {
        return relatedBts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BTS.RELATED_BTS
     *
     * @param relatedBts the value for WY_BTS.RELATED_BTS
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public void setRelatedBts(BigDecimal relatedBts) {
        this.relatedBts = relatedBts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BTS.MANUAL_FLAG
     *
     * @return the value of WY_BTS.MANUAL_FLAG
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public BigDecimal getManualFlag() {
        return manualFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BTS.MANUAL_FLAG
     *
     * @param manualFlag the value for WY_BTS.MANUAL_FLAG
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public void setManualFlag(BigDecimal manualFlag) {
        this.manualFlag = manualFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BTS.DELETE_FLAG
     *
     * @return the value of WY_BTS.DELETE_FLAG
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public BigDecimal getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BTS.DELETE_FLAG
     *
     * @param deleteFlag the value for WY_BTS.DELETE_FLAG
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public void setDeleteFlag(BigDecimal deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    public Date getDeletetime() {
        return deletetime;
    }

    public void setDeletetime(Date deletetime) {
        this.deletetime = deletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BTS.UPDATETIME
     *
     * @return the value of WY_BTS.UPDATETIME
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BTS.UPDATETIME
     *
     * @param updatetime the value for WY_BTS.UPDATETIME
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_BTS.SERVICE_LEVEL
     *
     * @return the value of WY_BTS.SERVICE_LEVEL
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public String getServiceLevel() {
        return serviceLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_BTS.SERVICE_LEVEL
     *
     * @param serviceLevel the value for WY_BTS.SERVICE_LEVEL
     * @mbggenerated Thu Mar 28 14:50:24 CST 2013
     */
    public void setServiceLevel(String serviceLevel) {
        this.serviceLevel = serviceLevel;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public City getCountry() {
        return country;
    }

    public void setCountry(City country) {
        this.country = country;
    }

    public City getCity() {
        return city;
    }

    public void setCity(City city) {
        this.city = city;
    }

    public List<Bbu> getBbus() {
        return bbus;
    }

    public void setBbus(List<Bbu> bbus) {
        this.bbus = bbus;
    }


    public String getDeleteTimeStr() {
         return deletetime==null?"": DateUtils.DateToStr(deletetime,"yyyy-MM-dd");
    }

    public void setDeleteTimeStr(String deleteTimeStr) {
        this.deleteTimeStr = deleteTimeStr;
    }

    public List<Cell> getCells() {
        return cells;
    }

    public void setCells(List<Cell> cells) {
        this.cells = cells;
    }


    public String getUpdateTimeStr() {
        return updatetime==null?"": DateUtils.DateToStr(updatetime,"yyyy-MM-dd");
    }

    public void setUpdateTimeStr(String updateTimeStr) {
        this.updateTimeStr = updateTimeStr;
    }
}