package com.scttsc.business.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class CBts {

    private BigDecimal intId;
    private String objectRdn;
    private String name;
    private BigDecimal bssid;
    private BigDecimal btsid;
    private BigDecimal vendorId;
    private BigDecimal omcId;
    private BigDecimal relatedOmc;
    private BigDecimal relatedMsc;
    private BigDecimal relatedBsc;
    private String mscName;
    private String bscName;
    private BigDecimal cityId;
    private BigDecimal confirmed;
    private BigDecimal sysType;
    private Date timeStamp;
    private BigDecimal numce;
    private BigDecimal numfa;
    private BigDecimal numrru;
    private BigDecimal numtch;
    private Double capacity;
    private BigDecimal btsclass;
    private BigDecimal btstype;
    private BigDecimal status;
    private String grade;
    private Double longitude;
    private Double latitude;
    private String vendorBtstype;
    private String cellCarrierNum1x;
    private String cellCarrierNumDo;
    private BigDecimal cutoverstatus;
    private BigDecimal usestatus;
    private Date changetime;
    private String note;
    private BigDecimal doBts;
    private BigDecimal relatedRnc;
    private String rncName;
    private BigDecimal dcsid;
    private BigDecimal rncid;
    private BigDecimal relatedDcs;
    private String uniqueRdn;
    private BigDecimal channelNbr;
    private BigDecimal nbr2m;
    private BigDecimal numfado;
    private BigDecimal sid;
    private BigDecimal nid;
    private Double bandabis;
    private BigDecimal numcedo;


    private List<Ccell> ccellList;//站点小区列表



    public BigDecimal getIntId() {
        return intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.INT_ID
     *
     * @param intId the value for C_BTS.INT_ID
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setIntId(BigDecimal intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.OBJECT_RDN
     *
     * @return the value of C_BTS.OBJECT_RDN
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public String getObjectRdn() {
        return objectRdn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.OBJECT_RDN
     *
     * @param objectRdn the value for C_BTS.OBJECT_RDN
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setObjectRdn(String objectRdn) {
        this.objectRdn = objectRdn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.NAME
     *
     * @return the value of C_BTS.NAME
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.NAME
     *
     * @param name the value for C_BTS.NAME
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.BSSID
     *
     * @return the value of C_BTS.BSSID
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getBssid() {
        return bssid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.BSSID
     *
     * @param bssid the value for C_BTS.BSSID
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setBssid(BigDecimal bssid) {
        this.bssid = bssid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.BTSID
     *
     * @return the value of C_BTS.BTSID
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getBtsid() {
        return btsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.BTSID
     *
     * @param btsid the value for C_BTS.BTSID
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setBtsid(BigDecimal btsid) {
        this.btsid = btsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.VENDOR_ID
     *
     * @return the value of C_BTS.VENDOR_ID
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getVendorId() {
        return vendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.VENDOR_ID
     *
     * @param vendorId the value for C_BTS.VENDOR_ID
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setVendorId(BigDecimal vendorId) {
        this.vendorId = vendorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.OMC_ID
     *
     * @return the value of C_BTS.OMC_ID
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getOmcId() {
        return omcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.OMC_ID
     *
     * @param omcId the value for C_BTS.OMC_ID
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setOmcId(BigDecimal omcId) {
        this.omcId = omcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.RELATED_OMC
     *
     * @return the value of C_BTS.RELATED_OMC
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getRelatedOmc() {
        return relatedOmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.RELATED_OMC
     *
     * @param relatedOmc the value for C_BTS.RELATED_OMC
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setRelatedOmc(BigDecimal relatedOmc) {
        this.relatedOmc = relatedOmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.RELATED_MSC
     *
     * @return the value of C_BTS.RELATED_MSC
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getRelatedMsc() {
        return relatedMsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.RELATED_MSC
     *
     * @param relatedMsc the value for C_BTS.RELATED_MSC
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setRelatedMsc(BigDecimal relatedMsc) {
        this.relatedMsc = relatedMsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.RELATED_BSC
     *
     * @return the value of C_BTS.RELATED_BSC
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getRelatedBsc() {
        return relatedBsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.RELATED_BSC
     *
     * @param relatedBsc the value for C_BTS.RELATED_BSC
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setRelatedBsc(BigDecimal relatedBsc) {
        this.relatedBsc = relatedBsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.MSC_NAME
     *
     * @return the value of C_BTS.MSC_NAME
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public String getMscName() {
        return mscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.MSC_NAME
     *
     * @param mscName the value for C_BTS.MSC_NAME
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setMscName(String mscName) {
        this.mscName = mscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.BSC_NAME
     *
     * @return the value of C_BTS.BSC_NAME
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public String getBscName() {
        return bscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.BSC_NAME
     *
     * @param bscName the value for C_BTS.BSC_NAME
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setBscName(String bscName) {
        this.bscName = bscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.CITY_ID
     *
     * @return the value of C_BTS.CITY_ID
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.CITY_ID
     *
     * @param cityId the value for C_BTS.CITY_ID
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setCityId(BigDecimal cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.CONFIRMED
     *
     * @return the value of C_BTS.CONFIRMED
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getConfirmed() {
        return confirmed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.CONFIRMED
     *
     * @param confirmed the value for C_BTS.CONFIRMED
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setConfirmed(BigDecimal confirmed) {
        this.confirmed = confirmed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.SYS_TYPE
     *
     * @return the value of C_BTS.SYS_TYPE
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getSysType() {
        return sysType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.SYS_TYPE
     *
     * @param sysType the value for C_BTS.SYS_TYPE
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setSysType(BigDecimal sysType) {
        this.sysType = sysType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.TIME_STAMP
     *
     * @return the value of C_BTS.TIME_STAMP
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.TIME_STAMP
     *
     * @param timeStamp the value for C_BTS.TIME_STAMP
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.NUMCE
     *
     * @return the value of C_BTS.NUMCE
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getNumce() {
        return numce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.NUMCE
     *
     * @param numce the value for C_BTS.NUMCE
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setNumce(BigDecimal numce) {
        this.numce = numce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.NUMFA
     *
     * @return the value of C_BTS.NUMFA
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getNumfa() {
        return numfa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.NUMFA
     *
     * @param numfa the value for C_BTS.NUMFA
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setNumfa(BigDecimal numfa) {
        this.numfa = numfa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.NUMRRU
     *
     * @return the value of C_BTS.NUMRRU
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getNumrru() {
        return numrru;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.NUMRRU
     *
     * @param numrru the value for C_BTS.NUMRRU
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setNumrru(BigDecimal numrru) {
        this.numrru = numrru;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.NUMTCH
     *
     * @return the value of C_BTS.NUMTCH
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getNumtch() {
        return numtch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.NUMTCH
     *
     * @param numtch the value for C_BTS.NUMTCH
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setNumtch(BigDecimal numtch) {
        this.numtch = numtch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.CAPACITY
     *
     * @return the value of C_BTS.CAPACITY
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public Double getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.CAPACITY
     *
     * @param capacity the value for C_BTS.CAPACITY
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setCapacity(Double capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.BTSCLASS
     *
     * @return the value of C_BTS.BTSCLASS
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getBtsclass() {
        return btsclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.BTSCLASS
     *
     * @param btsclass the value for C_BTS.BTSCLASS
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setBtsclass(BigDecimal btsclass) {
        this.btsclass = btsclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.BTSTYPE
     *
     * @return the value of C_BTS.BTSTYPE
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getBtstype() {
        return btstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.BTSTYPE
     *
     * @param btstype the value for C_BTS.BTSTYPE
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setBtstype(BigDecimal btstype) {
        this.btstype = btstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.STATUS
     *
     * @return the value of C_BTS.STATUS
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.STATUS
     *
     * @param status the value for C_BTS.STATUS
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setStatus(BigDecimal status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.GRADE
     *
     * @return the value of C_BTS.GRADE
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.GRADE
     *
     * @param grade the value for C_BTS.GRADE
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.LONGITUDE
     *
     * @return the value of C_BTS.LONGITUDE
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.LONGITUDE
     *
     * @param longitude the value for C_BTS.LONGITUDE
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.LATITUDE
     *
     * @return the value of C_BTS.LATITUDE
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.LATITUDE
     *
     * @param latitude the value for C_BTS.LATITUDE
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.VENDOR_BTSTYPE
     *
     * @return the value of C_BTS.VENDOR_BTSTYPE
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public String getVendorBtstype() {
        return vendorBtstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.VENDOR_BTSTYPE
     *
     * @param vendorBtstype the value for C_BTS.VENDOR_BTSTYPE
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setVendorBtstype(String vendorBtstype) {
        this.vendorBtstype = vendorBtstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.CELL_CARRIER_NUM_1X
     *
     * @return the value of C_BTS.CELL_CARRIER_NUM_1X
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public String getCellCarrierNum1x() {
        return cellCarrierNum1x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.CELL_CARRIER_NUM_1X
     *
     * @param cellCarrierNum1x the value for C_BTS.CELL_CARRIER_NUM_1X
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setCellCarrierNum1x(String cellCarrierNum1x) {
        this.cellCarrierNum1x = cellCarrierNum1x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.CELL_CARRIER_NUM_DO
     *
     * @return the value of C_BTS.CELL_CARRIER_NUM_DO
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public String getCellCarrierNumDo() {
        return cellCarrierNumDo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.CELL_CARRIER_NUM_DO
     *
     * @param cellCarrierNumDo the value for C_BTS.CELL_CARRIER_NUM_DO
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setCellCarrierNumDo(String cellCarrierNumDo) {
        this.cellCarrierNumDo = cellCarrierNumDo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.CUTOVERSTATUS
     *
     * @return the value of C_BTS.CUTOVERSTATUS
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getCutoverstatus() {
        return cutoverstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.CUTOVERSTATUS
     *
     * @param cutoverstatus the value for C_BTS.CUTOVERSTATUS
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setCutoverstatus(BigDecimal cutoverstatus) {
        this.cutoverstatus = cutoverstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.USESTATUS
     *
     * @return the value of C_BTS.USESTATUS
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getUsestatus() {
        return usestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.USESTATUS
     *
     * @param usestatus the value for C_BTS.USESTATUS
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setUsestatus(BigDecimal usestatus) {
        this.usestatus = usestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.CHANGETIME
     *
     * @return the value of C_BTS.CHANGETIME
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public Date getChangetime() {
        return changetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.CHANGETIME
     *
     * @param changetime the value for C_BTS.CHANGETIME
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setChangetime(Date changetime) {
        this.changetime = changetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.NOTE
     *
     * @return the value of C_BTS.NOTE
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.NOTE
     *
     * @param note the value for C_BTS.NOTE
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.DO_BTS
     *
     * @return the value of C_BTS.DO_BTS
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getDoBts() {
        return doBts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.DO_BTS
     *
     * @param doBts the value for C_BTS.DO_BTS
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setDoBts(BigDecimal doBts) {
        this.doBts = doBts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.RELATED_RNC
     *
     * @return the value of C_BTS.RELATED_RNC
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getRelatedRnc() {
        return relatedRnc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.RELATED_RNC
     *
     * @param relatedRnc the value for C_BTS.RELATED_RNC
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setRelatedRnc(BigDecimal relatedRnc) {
        this.relatedRnc = relatedRnc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.RNC_NAME
     *
     * @return the value of C_BTS.RNC_NAME
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public String getRncName() {
        return rncName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.RNC_NAME
     *
     * @param rncName the value for C_BTS.RNC_NAME
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setRncName(String rncName) {
        this.rncName = rncName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.DCSID
     *
     * @return the value of C_BTS.DCSID
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getDcsid() {
        return dcsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.DCSID
     *
     * @param dcsid the value for C_BTS.DCSID
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setDcsid(BigDecimal dcsid) {
        this.dcsid = dcsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.RNCID
     *
     * @return the value of C_BTS.RNCID
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getRncid() {
        return rncid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.RNCID
     *
     * @param rncid the value for C_BTS.RNCID
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setRncid(BigDecimal rncid) {
        this.rncid = rncid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.RELATED_DCS
     *
     * @return the value of C_BTS.RELATED_DCS
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getRelatedDcs() {
        return relatedDcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.RELATED_DCS
     *
     * @param relatedDcs the value for C_BTS.RELATED_DCS
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setRelatedDcs(BigDecimal relatedDcs) {
        this.relatedDcs = relatedDcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.UNIQUE_RDN
     *
     * @return the value of C_BTS.UNIQUE_RDN
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public String getUniqueRdn() {
        return uniqueRdn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.UNIQUE_RDN
     *
     * @param uniqueRdn the value for C_BTS.UNIQUE_RDN
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setUniqueRdn(String uniqueRdn) {
        this.uniqueRdn = uniqueRdn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.CHANNEL_NBR
     *
     * @return the value of C_BTS.CHANNEL_NBR
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getChannelNbr() {
        return channelNbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.CHANNEL_NBR
     *
     * @param channelNbr the value for C_BTS.CHANNEL_NBR
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setChannelNbr(BigDecimal channelNbr) {
        this.channelNbr = channelNbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.NBR_2M
     *
     * @return the value of C_BTS.NBR_2M
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getNbr2m() {
        return nbr2m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.NBR_2M
     *
     * @param nbr2m the value for C_BTS.NBR_2M
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setNbr2m(BigDecimal nbr2m) {
        this.nbr2m = nbr2m;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.NUMFADO
     *
     * @return the value of C_BTS.NUMFADO
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getNumfado() {
        return numfado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.NUMFADO
     *
     * @param numfado the value for C_BTS.NUMFADO
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setNumfado(BigDecimal numfado) {
        this.numfado = numfado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.SID
     *
     * @return the value of C_BTS.SID
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.SID
     *
     * @param sid the value for C_BTS.SID
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setSid(BigDecimal sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.NID
     *
     * @return the value of C_BTS.NID
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getNid() {
        return nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.NID
     *
     * @param nid the value for C_BTS.NID
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setNid(BigDecimal nid) {
        this.nid = nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.BANDABIS
     *
     * @return the value of C_BTS.BANDABIS
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public Double getBandabis() {
        return bandabis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.BANDABIS
     *
     * @param bandabis the value for C_BTS.BANDABIS
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setBandabis(Double bandabis) {
        this.bandabis = bandabis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_BTS.NUMCEDO
     *
     * @return the value of C_BTS.NUMCEDO
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public BigDecimal getNumcedo() {
        return numcedo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_BTS.NUMCEDO
     *
     * @param numcedo the value for C_BTS.NUMCEDO
     *
     * @mbggenerated Thu Apr 18 12:25:42 CST 2013
     */
    public void setNumcedo(BigDecimal numcedo) {
        this.numcedo = numcedo;
    }

    public List<Ccell> getCcellList() {
        return ccellList;
    }

    public void setCcellList(List<Ccell> ccellList) {
        this.ccellList = ccellList;
    }
}