package com.scttsc.business.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CcellExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table C_CELL
     *
     * @mbggenerated Wed Apr 10 15:30:30 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table C_CELL
     *
     * @mbggenerated Wed Apr 10 15:30:30 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table C_CELL
     *
     * @mbggenerated Wed Apr 10 15:30:30 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_CELL
     *
     * @mbggenerated Wed Apr 10 15:30:30 CST 2013
     */
    public CcellExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_CELL
     *
     * @mbggenerated Wed Apr 10 15:30:30 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_CELL
     *
     * @mbggenerated Wed Apr 10 15:30:30 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_CELL
     *
     * @mbggenerated Wed Apr 10 15:30:30 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_CELL
     *
     * @mbggenerated Wed Apr 10 15:30:30 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_CELL
     *
     * @mbggenerated Wed Apr 10 15:30:30 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_CELL
     *
     * @mbggenerated Wed Apr 10 15:30:30 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_CELL
     *
     * @mbggenerated Wed Apr 10 15:30:30 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_CELL
     *
     * @mbggenerated Wed Apr 10 15:30:30 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_CELL
     *
     * @mbggenerated Wed Apr 10 15:30:30 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table C_CELL
     *
     * @mbggenerated Wed Apr 10 15:30:30 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table C_CELL
     *
     * @mbggenerated Wed Apr 10 15:30:30 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIntIdIsNull() {
            addCriterion("INT_ID is null");
            return (Criteria) this;
        }

        public Criteria andIntIdIsNotNull() {
            addCriterion("INT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andIntIdEqualTo(BigDecimal value) {
            addCriterion("INT_ID =", value, "intId");
            return (Criteria) this;
        }

        public Criteria andIntIdNotEqualTo(BigDecimal value) {
            addCriterion("INT_ID <>", value, "intId");
            return (Criteria) this;
        }

        public Criteria andIntIdGreaterThan(BigDecimal value) {
            addCriterion("INT_ID >", value, "intId");
            return (Criteria) this;
        }

        public Criteria andIntIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INT_ID >=", value, "intId");
            return (Criteria) this;
        }

        public Criteria andIntIdLessThan(BigDecimal value) {
            addCriterion("INT_ID <", value, "intId");
            return (Criteria) this;
        }

        public Criteria andIntIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INT_ID <=", value, "intId");
            return (Criteria) this;
        }

        public Criteria andIntIdIn(List<BigDecimal> values) {
            addCriterion("INT_ID in", values, "intId");
            return (Criteria) this;
        }

        public Criteria andIntIdNotIn(List<BigDecimal> values) {
            addCriterion("INT_ID not in", values, "intId");
            return (Criteria) this;
        }

        public Criteria andIntIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INT_ID between", value1, value2, "intId");
            return (Criteria) this;
        }

        public Criteria andIntIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INT_ID not between", value1, value2, "intId");
            return (Criteria) this;
        }

        public Criteria andObjectRdnIsNull() {
            addCriterion("OBJECT_RDN is null");
            return (Criteria) this;
        }

        public Criteria andObjectRdnIsNotNull() {
            addCriterion("OBJECT_RDN is not null");
            return (Criteria) this;
        }

        public Criteria andObjectRdnEqualTo(String value) {
            addCriterion("OBJECT_RDN =", value, "objectRdn");
            return (Criteria) this;
        }

        public Criteria andObjectRdnNotEqualTo(String value) {
            addCriterion("OBJECT_RDN <>", value, "objectRdn");
            return (Criteria) this;
        }

        public Criteria andObjectRdnGreaterThan(String value) {
            addCriterion("OBJECT_RDN >", value, "objectRdn");
            return (Criteria) this;
        }

        public Criteria andObjectRdnGreaterThanOrEqualTo(String value) {
            addCriterion("OBJECT_RDN >=", value, "objectRdn");
            return (Criteria) this;
        }

        public Criteria andObjectRdnLessThan(String value) {
            addCriterion("OBJECT_RDN <", value, "objectRdn");
            return (Criteria) this;
        }

        public Criteria andObjectRdnLessThanOrEqualTo(String value) {
            addCriterion("OBJECT_RDN <=", value, "objectRdn");
            return (Criteria) this;
        }

        public Criteria andObjectRdnLike(String value) {
            addCriterion("OBJECT_RDN like", value, "objectRdn");
            return (Criteria) this;
        }

        public Criteria andObjectRdnNotLike(String value) {
            addCriterion("OBJECT_RDN not like", value, "objectRdn");
            return (Criteria) this;
        }

        public Criteria andObjectRdnIn(List<String> values) {
            addCriterion("OBJECT_RDN in", values, "objectRdn");
            return (Criteria) this;
        }

        public Criteria andObjectRdnNotIn(List<String> values) {
            addCriterion("OBJECT_RDN not in", values, "objectRdn");
            return (Criteria) this;
        }

        public Criteria andObjectRdnBetween(String value1, String value2) {
            addCriterion("OBJECT_RDN between", value1, value2, "objectRdn");
            return (Criteria) this;
        }

        public Criteria andObjectRdnNotBetween(String value1, String value2) {
            addCriterion("OBJECT_RDN not between", value1, value2, "objectRdn");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andBssidIsNull() {
            addCriterion("BSSID is null");
            return (Criteria) this;
        }

        public Criteria andBssidIsNotNull() {
            addCriterion("BSSID is not null");
            return (Criteria) this;
        }

        public Criteria andBssidEqualTo(BigDecimal value) {
            addCriterion("BSSID =", value, "bssid");
            return (Criteria) this;
        }

        public Criteria andBssidNotEqualTo(BigDecimal value) {
            addCriterion("BSSID <>", value, "bssid");
            return (Criteria) this;
        }

        public Criteria andBssidGreaterThan(BigDecimal value) {
            addCriterion("BSSID >", value, "bssid");
            return (Criteria) this;
        }

        public Criteria andBssidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BSSID >=", value, "bssid");
            return (Criteria) this;
        }

        public Criteria andBssidLessThan(BigDecimal value) {
            addCriterion("BSSID <", value, "bssid");
            return (Criteria) this;
        }

        public Criteria andBssidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BSSID <=", value, "bssid");
            return (Criteria) this;
        }

        public Criteria andBssidIn(List<BigDecimal> values) {
            addCriterion("BSSID in", values, "bssid");
            return (Criteria) this;
        }

        public Criteria andBssidNotIn(List<BigDecimal> values) {
            addCriterion("BSSID not in", values, "bssid");
            return (Criteria) this;
        }

        public Criteria andBssidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BSSID between", value1, value2, "bssid");
            return (Criteria) this;
        }

        public Criteria andBssidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BSSID not between", value1, value2, "bssid");
            return (Criteria) this;
        }

        public Criteria andBtsidIsNull() {
            addCriterion("BTSID is null");
            return (Criteria) this;
        }

        public Criteria andBtsidIsNotNull() {
            addCriterion("BTSID is not null");
            return (Criteria) this;
        }

        public Criteria andBtsidEqualTo(BigDecimal value) {
            addCriterion("BTSID =", value, "btsid");
            return (Criteria) this;
        }

        public Criteria andBtsidNotEqualTo(BigDecimal value) {
            addCriterion("BTSID <>", value, "btsid");
            return (Criteria) this;
        }

        public Criteria andBtsidGreaterThan(BigDecimal value) {
            addCriterion("BTSID >", value, "btsid");
            return (Criteria) this;
        }

        public Criteria andBtsidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BTSID >=", value, "btsid");
            return (Criteria) this;
        }

        public Criteria andBtsidLessThan(BigDecimal value) {
            addCriterion("BTSID <", value, "btsid");
            return (Criteria) this;
        }

        public Criteria andBtsidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BTSID <=", value, "btsid");
            return (Criteria) this;
        }

        public Criteria andBtsidIn(List<BigDecimal> values) {
            addCriterion("BTSID in", values, "btsid");
            return (Criteria) this;
        }

        public Criteria andBtsidNotIn(List<BigDecimal> values) {
            addCriterion("BTSID not in", values, "btsid");
            return (Criteria) this;
        }

        public Criteria andBtsidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BTSID between", value1, value2, "btsid");
            return (Criteria) this;
        }

        public Criteria andBtsidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BTSID not between", value1, value2, "btsid");
            return (Criteria) this;
        }

        public Criteria andCellidIsNull() {
            addCriterion("CELLID is null");
            return (Criteria) this;
        }

        public Criteria andCellidIsNotNull() {
            addCriterion("CELLID is not null");
            return (Criteria) this;
        }

        public Criteria andCellidEqualTo(BigDecimal value) {
            addCriterion("CELLID =", value, "cellid");
            return (Criteria) this;
        }

        public Criteria andCellidNotEqualTo(BigDecimal value) {
            addCriterion("CELLID <>", value, "cellid");
            return (Criteria) this;
        }

        public Criteria andCellidGreaterThan(BigDecimal value) {
            addCriterion("CELLID >", value, "cellid");
            return (Criteria) this;
        }

        public Criteria andCellidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CELLID >=", value, "cellid");
            return (Criteria) this;
        }

        public Criteria andCellidLessThan(BigDecimal value) {
            addCriterion("CELLID <", value, "cellid");
            return (Criteria) this;
        }

        public Criteria andCellidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CELLID <=", value, "cellid");
            return (Criteria) this;
        }

        public Criteria andCellidIn(List<BigDecimal> values) {
            addCriterion("CELLID in", values, "cellid");
            return (Criteria) this;
        }

        public Criteria andCellidNotIn(List<BigDecimal> values) {
            addCriterion("CELLID not in", values, "cellid");
            return (Criteria) this;
        }

        public Criteria andCellidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CELLID between", value1, value2, "cellid");
            return (Criteria) this;
        }

        public Criteria andCellidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CELLID not between", value1, value2, "cellid");
            return (Criteria) this;
        }

        public Criteria andAdjNumIsNull() {
            addCriterion("ADJ_NUM is null");
            return (Criteria) this;
        }

        public Criteria andAdjNumIsNotNull() {
            addCriterion("ADJ_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andAdjNumEqualTo(BigDecimal value) {
            addCriterion("ADJ_NUM =", value, "adjNum");
            return (Criteria) this;
        }

        public Criteria andAdjNumNotEqualTo(BigDecimal value) {
            addCriterion("ADJ_NUM <>", value, "adjNum");
            return (Criteria) this;
        }

        public Criteria andAdjNumGreaterThan(BigDecimal value) {
            addCriterion("ADJ_NUM >", value, "adjNum");
            return (Criteria) this;
        }

        public Criteria andAdjNumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ADJ_NUM >=", value, "adjNum");
            return (Criteria) this;
        }

        public Criteria andAdjNumLessThan(BigDecimal value) {
            addCriterion("ADJ_NUM <", value, "adjNum");
            return (Criteria) this;
        }

        public Criteria andAdjNumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ADJ_NUM <=", value, "adjNum");
            return (Criteria) this;
        }

        public Criteria andAdjNumIn(List<BigDecimal> values) {
            addCriterion("ADJ_NUM in", values, "adjNum");
            return (Criteria) this;
        }

        public Criteria andAdjNumNotIn(List<BigDecimal> values) {
            addCriterion("ADJ_NUM not in", values, "adjNum");
            return (Criteria) this;
        }

        public Criteria andAdjNumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ADJ_NUM between", value1, value2, "adjNum");
            return (Criteria) this;
        }

        public Criteria andAdjNumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ADJ_NUM not between", value1, value2, "adjNum");
            return (Criteria) this;
        }

        public Criteria andUniqueRdnIsNull() {
            addCriterion("UNIQUE_RDN is null");
            return (Criteria) this;
        }

        public Criteria andUniqueRdnIsNotNull() {
            addCriterion("UNIQUE_RDN is not null");
            return (Criteria) this;
        }

        public Criteria andUniqueRdnEqualTo(String value) {
            addCriterion("UNIQUE_RDN =", value, "uniqueRdn");
            return (Criteria) this;
        }

        public Criteria andUniqueRdnNotEqualTo(String value) {
            addCriterion("UNIQUE_RDN <>", value, "uniqueRdn");
            return (Criteria) this;
        }

        public Criteria andUniqueRdnGreaterThan(String value) {
            addCriterion("UNIQUE_RDN >", value, "uniqueRdn");
            return (Criteria) this;
        }

        public Criteria andUniqueRdnGreaterThanOrEqualTo(String value) {
            addCriterion("UNIQUE_RDN >=", value, "uniqueRdn");
            return (Criteria) this;
        }

        public Criteria andUniqueRdnLessThan(String value) {
            addCriterion("UNIQUE_RDN <", value, "uniqueRdn");
            return (Criteria) this;
        }

        public Criteria andUniqueRdnLessThanOrEqualTo(String value) {
            addCriterion("UNIQUE_RDN <=", value, "uniqueRdn");
            return (Criteria) this;
        }

        public Criteria andUniqueRdnLike(String value) {
            addCriterion("UNIQUE_RDN like", value, "uniqueRdn");
            return (Criteria) this;
        }

        public Criteria andUniqueRdnNotLike(String value) {
            addCriterion("UNIQUE_RDN not like", value, "uniqueRdn");
            return (Criteria) this;
        }

        public Criteria andUniqueRdnIn(List<String> values) {
            addCriterion("UNIQUE_RDN in", values, "uniqueRdn");
            return (Criteria) this;
        }

        public Criteria andUniqueRdnNotIn(List<String> values) {
            addCriterion("UNIQUE_RDN not in", values, "uniqueRdn");
            return (Criteria) this;
        }

        public Criteria andUniqueRdnBetween(String value1, String value2) {
            addCriterion("UNIQUE_RDN between", value1, value2, "uniqueRdn");
            return (Criteria) this;
        }

        public Criteria andUniqueRdnNotBetween(String value1, String value2) {
            addCriterion("UNIQUE_RDN not between", value1, value2, "uniqueRdn");
            return (Criteria) this;
        }

        public Criteria andZhNameIsNull() {
            addCriterion("ZH_NAME is null");
            return (Criteria) this;
        }

        public Criteria andZhNameIsNotNull() {
            addCriterion("ZH_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andZhNameEqualTo(String value) {
            addCriterion("ZH_NAME =", value, "zhName");
            return (Criteria) this;
        }

        public Criteria andZhNameNotEqualTo(String value) {
            addCriterion("ZH_NAME <>", value, "zhName");
            return (Criteria) this;
        }

        public Criteria andZhNameGreaterThan(String value) {
            addCriterion("ZH_NAME >", value, "zhName");
            return (Criteria) this;
        }

        public Criteria andZhNameGreaterThanOrEqualTo(String value) {
            addCriterion("ZH_NAME >=", value, "zhName");
            return (Criteria) this;
        }

        public Criteria andZhNameLessThan(String value) {
            addCriterion("ZH_NAME <", value, "zhName");
            return (Criteria) this;
        }

        public Criteria andZhNameLessThanOrEqualTo(String value) {
            addCriterion("ZH_NAME <=", value, "zhName");
            return (Criteria) this;
        }

        public Criteria andZhNameLike(String value) {
            addCriterion("ZH_NAME like", value, "zhName");
            return (Criteria) this;
        }

        public Criteria andZhNameNotLike(String value) {
            addCriterion("ZH_NAME not like", value, "zhName");
            return (Criteria) this;
        }

        public Criteria andZhNameIn(List<String> values) {
            addCriterion("ZH_NAME in", values, "zhName");
            return (Criteria) this;
        }

        public Criteria andZhNameNotIn(List<String> values) {
            addCriterion("ZH_NAME not in", values, "zhName");
            return (Criteria) this;
        }

        public Criteria andZhNameBetween(String value1, String value2) {
            addCriterion("ZH_NAME between", value1, value2, "zhName");
            return (Criteria) this;
        }

        public Criteria andZhNameNotBetween(String value1, String value2) {
            addCriterion("ZH_NAME not between", value1, value2, "zhName");
            return (Criteria) this;
        }

        public Criteria andVendorIdIsNull() {
            addCriterion("VENDOR_ID is null");
            return (Criteria) this;
        }

        public Criteria andVendorIdIsNotNull() {
            addCriterion("VENDOR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andVendorIdEqualTo(BigDecimal value) {
            addCriterion("VENDOR_ID =", value, "vendorId");
            return (Criteria) this;
        }

        public Criteria andVendorIdNotEqualTo(BigDecimal value) {
            addCriterion("VENDOR_ID <>", value, "vendorId");
            return (Criteria) this;
        }

        public Criteria andVendorIdGreaterThan(BigDecimal value) {
            addCriterion("VENDOR_ID >", value, "vendorId");
            return (Criteria) this;
        }

        public Criteria andVendorIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VENDOR_ID >=", value, "vendorId");
            return (Criteria) this;
        }

        public Criteria andVendorIdLessThan(BigDecimal value) {
            addCriterion("VENDOR_ID <", value, "vendorId");
            return (Criteria) this;
        }

        public Criteria andVendorIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VENDOR_ID <=", value, "vendorId");
            return (Criteria) this;
        }

        public Criteria andVendorIdIn(List<BigDecimal> values) {
            addCriterion("VENDOR_ID in", values, "vendorId");
            return (Criteria) this;
        }

        public Criteria andVendorIdNotIn(List<BigDecimal> values) {
            addCriterion("VENDOR_ID not in", values, "vendorId");
            return (Criteria) this;
        }

        public Criteria andVendorIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VENDOR_ID between", value1, value2, "vendorId");
            return (Criteria) this;
        }

        public Criteria andVendorIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VENDOR_ID not between", value1, value2, "vendorId");
            return (Criteria) this;
        }

        public Criteria andOmcIdIsNull() {
            addCriterion("OMC_ID is null");
            return (Criteria) this;
        }

        public Criteria andOmcIdIsNotNull() {
            addCriterion("OMC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOmcIdEqualTo(BigDecimal value) {
            addCriterion("OMC_ID =", value, "omcId");
            return (Criteria) this;
        }

        public Criteria andOmcIdNotEqualTo(BigDecimal value) {
            addCriterion("OMC_ID <>", value, "omcId");
            return (Criteria) this;
        }

        public Criteria andOmcIdGreaterThan(BigDecimal value) {
            addCriterion("OMC_ID >", value, "omcId");
            return (Criteria) this;
        }

        public Criteria andOmcIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("OMC_ID >=", value, "omcId");
            return (Criteria) this;
        }

        public Criteria andOmcIdLessThan(BigDecimal value) {
            addCriterion("OMC_ID <", value, "omcId");
            return (Criteria) this;
        }

        public Criteria andOmcIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("OMC_ID <=", value, "omcId");
            return (Criteria) this;
        }

        public Criteria andOmcIdIn(List<BigDecimal> values) {
            addCriterion("OMC_ID in", values, "omcId");
            return (Criteria) this;
        }

        public Criteria andOmcIdNotIn(List<BigDecimal> values) {
            addCriterion("OMC_ID not in", values, "omcId");
            return (Criteria) this;
        }

        public Criteria andOmcIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OMC_ID between", value1, value2, "omcId");
            return (Criteria) this;
        }

        public Criteria andOmcIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("OMC_ID not between", value1, value2, "omcId");
            return (Criteria) this;
        }

        public Criteria andRelatedOmcIsNull() {
            addCriterion("RELATED_OMC is null");
            return (Criteria) this;
        }

        public Criteria andRelatedOmcIsNotNull() {
            addCriterion("RELATED_OMC is not null");
            return (Criteria) this;
        }

        public Criteria andRelatedOmcEqualTo(BigDecimal value) {
            addCriterion("RELATED_OMC =", value, "relatedOmc");
            return (Criteria) this;
        }

        public Criteria andRelatedOmcNotEqualTo(BigDecimal value) {
            addCriterion("RELATED_OMC <>", value, "relatedOmc");
            return (Criteria) this;
        }

        public Criteria andRelatedOmcGreaterThan(BigDecimal value) {
            addCriterion("RELATED_OMC >", value, "relatedOmc");
            return (Criteria) this;
        }

        public Criteria andRelatedOmcGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RELATED_OMC >=", value, "relatedOmc");
            return (Criteria) this;
        }

        public Criteria andRelatedOmcLessThan(BigDecimal value) {
            addCriterion("RELATED_OMC <", value, "relatedOmc");
            return (Criteria) this;
        }

        public Criteria andRelatedOmcLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RELATED_OMC <=", value, "relatedOmc");
            return (Criteria) this;
        }

        public Criteria andRelatedOmcIn(List<BigDecimal> values) {
            addCriterion("RELATED_OMC in", values, "relatedOmc");
            return (Criteria) this;
        }

        public Criteria andRelatedOmcNotIn(List<BigDecimal> values) {
            addCriterion("RELATED_OMC not in", values, "relatedOmc");
            return (Criteria) this;
        }

        public Criteria andRelatedOmcBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RELATED_OMC between", value1, value2, "relatedOmc");
            return (Criteria) this;
        }

        public Criteria andRelatedOmcNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RELATED_OMC not between", value1, value2, "relatedOmc");
            return (Criteria) this;
        }

        public Criteria andRelatedMscIsNull() {
            addCriterion("RELATED_MSC is null");
            return (Criteria) this;
        }

        public Criteria andRelatedMscIsNotNull() {
            addCriterion("RELATED_MSC is not null");
            return (Criteria) this;
        }

        public Criteria andRelatedMscEqualTo(BigDecimal value) {
            addCriterion("RELATED_MSC =", value, "relatedMsc");
            return (Criteria) this;
        }

        public Criteria andRelatedMscNotEqualTo(BigDecimal value) {
            addCriterion("RELATED_MSC <>", value, "relatedMsc");
            return (Criteria) this;
        }

        public Criteria andRelatedMscGreaterThan(BigDecimal value) {
            addCriterion("RELATED_MSC >", value, "relatedMsc");
            return (Criteria) this;
        }

        public Criteria andRelatedMscGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RELATED_MSC >=", value, "relatedMsc");
            return (Criteria) this;
        }

        public Criteria andRelatedMscLessThan(BigDecimal value) {
            addCriterion("RELATED_MSC <", value, "relatedMsc");
            return (Criteria) this;
        }

        public Criteria andRelatedMscLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RELATED_MSC <=", value, "relatedMsc");
            return (Criteria) this;
        }

        public Criteria andRelatedMscIn(List<BigDecimal> values) {
            addCriterion("RELATED_MSC in", values, "relatedMsc");
            return (Criteria) this;
        }

        public Criteria andRelatedMscNotIn(List<BigDecimal> values) {
            addCriterion("RELATED_MSC not in", values, "relatedMsc");
            return (Criteria) this;
        }

        public Criteria andRelatedMscBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RELATED_MSC between", value1, value2, "relatedMsc");
            return (Criteria) this;
        }

        public Criteria andRelatedMscNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RELATED_MSC not between", value1, value2, "relatedMsc");
            return (Criteria) this;
        }

        public Criteria andRelatedBscIsNull() {
            addCriterion("RELATED_BSC is null");
            return (Criteria) this;
        }

        public Criteria andRelatedBscIsNotNull() {
            addCriterion("RELATED_BSC is not null");
            return (Criteria) this;
        }

        public Criteria andRelatedBscEqualTo(BigDecimal value) {
            addCriterion("RELATED_BSC =", value, "relatedBsc");
            return (Criteria) this;
        }

        public Criteria andRelatedBscNotEqualTo(BigDecimal value) {
            addCriterion("RELATED_BSC <>", value, "relatedBsc");
            return (Criteria) this;
        }

        public Criteria andRelatedBscGreaterThan(BigDecimal value) {
            addCriterion("RELATED_BSC >", value, "relatedBsc");
            return (Criteria) this;
        }

        public Criteria andRelatedBscGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RELATED_BSC >=", value, "relatedBsc");
            return (Criteria) this;
        }

        public Criteria andRelatedBscLessThan(BigDecimal value) {
            addCriterion("RELATED_BSC <", value, "relatedBsc");
            return (Criteria) this;
        }

        public Criteria andRelatedBscLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RELATED_BSC <=", value, "relatedBsc");
            return (Criteria) this;
        }

        public Criteria andRelatedBscIn(List<BigDecimal> values) {
            addCriterion("RELATED_BSC in", values, "relatedBsc");
            return (Criteria) this;
        }

        public Criteria andRelatedBscNotIn(List<BigDecimal> values) {
            addCriterion("RELATED_BSC not in", values, "relatedBsc");
            return (Criteria) this;
        }

        public Criteria andRelatedBscBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RELATED_BSC between", value1, value2, "relatedBsc");
            return (Criteria) this;
        }

        public Criteria andRelatedBscNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RELATED_BSC not between", value1, value2, "relatedBsc");
            return (Criteria) this;
        }

        public Criteria andRelatedBtsIsNull() {
            addCriterion("RELATED_BTS is null");
            return (Criteria) this;
        }

        public Criteria andRelatedBtsIsNotNull() {
            addCriterion("RELATED_BTS is not null");
            return (Criteria) this;
        }

        public Criteria andRelatedBtsEqualTo(BigDecimal value) {
            addCriterion("RELATED_BTS =", value, "relatedBts");
            return (Criteria) this;
        }

        public Criteria andRelatedBtsNotEqualTo(BigDecimal value) {
            addCriterion("RELATED_BTS <>", value, "relatedBts");
            return (Criteria) this;
        }

        public Criteria andRelatedBtsGreaterThan(BigDecimal value) {
            addCriterion("RELATED_BTS >", value, "relatedBts");
            return (Criteria) this;
        }

        public Criteria andRelatedBtsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RELATED_BTS >=", value, "relatedBts");
            return (Criteria) this;
        }

        public Criteria andRelatedBtsLessThan(BigDecimal value) {
            addCriterion("RELATED_BTS <", value, "relatedBts");
            return (Criteria) this;
        }

        public Criteria andRelatedBtsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RELATED_BTS <=", value, "relatedBts");
            return (Criteria) this;
        }

        public Criteria andRelatedBtsIn(List<BigDecimal> values) {
            addCriterion("RELATED_BTS in", values, "relatedBts");
            return (Criteria) this;
        }

        public Criteria andRelatedBtsNotIn(List<BigDecimal> values) {
            addCriterion("RELATED_BTS not in", values, "relatedBts");
            return (Criteria) this;
        }

        public Criteria andRelatedBtsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RELATED_BTS between", value1, value2, "relatedBts");
            return (Criteria) this;
        }

        public Criteria andRelatedBtsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RELATED_BTS not between", value1, value2, "relatedBts");
            return (Criteria) this;
        }

        public Criteria andMscNameIsNull() {
            addCriterion("MSC_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMscNameIsNotNull() {
            addCriterion("MSC_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMscNameEqualTo(String value) {
            addCriterion("MSC_NAME =", value, "mscName");
            return (Criteria) this;
        }

        public Criteria andMscNameNotEqualTo(String value) {
            addCriterion("MSC_NAME <>", value, "mscName");
            return (Criteria) this;
        }

        public Criteria andMscNameGreaterThan(String value) {
            addCriterion("MSC_NAME >", value, "mscName");
            return (Criteria) this;
        }

        public Criteria andMscNameGreaterThanOrEqualTo(String value) {
            addCriterion("MSC_NAME >=", value, "mscName");
            return (Criteria) this;
        }

        public Criteria andMscNameLessThan(String value) {
            addCriterion("MSC_NAME <", value, "mscName");
            return (Criteria) this;
        }

        public Criteria andMscNameLessThanOrEqualTo(String value) {
            addCriterion("MSC_NAME <=", value, "mscName");
            return (Criteria) this;
        }

        public Criteria andMscNameLike(String value) {
            addCriterion("MSC_NAME like", value, "mscName");
            return (Criteria) this;
        }

        public Criteria andMscNameNotLike(String value) {
            addCriterion("MSC_NAME not like", value, "mscName");
            return (Criteria) this;
        }

        public Criteria andMscNameIn(List<String> values) {
            addCriterion("MSC_NAME in", values, "mscName");
            return (Criteria) this;
        }

        public Criteria andMscNameNotIn(List<String> values) {
            addCriterion("MSC_NAME not in", values, "mscName");
            return (Criteria) this;
        }

        public Criteria andMscNameBetween(String value1, String value2) {
            addCriterion("MSC_NAME between", value1, value2, "mscName");
            return (Criteria) this;
        }

        public Criteria andMscNameNotBetween(String value1, String value2) {
            addCriterion("MSC_NAME not between", value1, value2, "mscName");
            return (Criteria) this;
        }

        public Criteria andBscNameIsNull() {
            addCriterion("BSC_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBscNameIsNotNull() {
            addCriterion("BSC_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBscNameEqualTo(String value) {
            addCriterion("BSC_NAME =", value, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameNotEqualTo(String value) {
            addCriterion("BSC_NAME <>", value, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameGreaterThan(String value) {
            addCriterion("BSC_NAME >", value, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameGreaterThanOrEqualTo(String value) {
            addCriterion("BSC_NAME >=", value, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameLessThan(String value) {
            addCriterion("BSC_NAME <", value, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameLessThanOrEqualTo(String value) {
            addCriterion("BSC_NAME <=", value, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameLike(String value) {
            addCriterion("BSC_NAME like", value, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameNotLike(String value) {
            addCriterion("BSC_NAME not like", value, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameIn(List<String> values) {
            addCriterion("BSC_NAME in", values, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameNotIn(List<String> values) {
            addCriterion("BSC_NAME not in", values, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameBetween(String value1, String value2) {
            addCriterion("BSC_NAME between", value1, value2, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameNotBetween(String value1, String value2) {
            addCriterion("BSC_NAME not between", value1, value2, "bscName");
            return (Criteria) this;
        }

        public Criteria andBtsNameIsNull() {
            addCriterion("BTS_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBtsNameIsNotNull() {
            addCriterion("BTS_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBtsNameEqualTo(String value) {
            addCriterion("BTS_NAME =", value, "btsName");
            return (Criteria) this;
        }

        public Criteria andBtsNameNotEqualTo(String value) {
            addCriterion("BTS_NAME <>", value, "btsName");
            return (Criteria) this;
        }

        public Criteria andBtsNameGreaterThan(String value) {
            addCriterion("BTS_NAME >", value, "btsName");
            return (Criteria) this;
        }

        public Criteria andBtsNameGreaterThanOrEqualTo(String value) {
            addCriterion("BTS_NAME >=", value, "btsName");
            return (Criteria) this;
        }

        public Criteria andBtsNameLessThan(String value) {
            addCriterion("BTS_NAME <", value, "btsName");
            return (Criteria) this;
        }

        public Criteria andBtsNameLessThanOrEqualTo(String value) {
            addCriterion("BTS_NAME <=", value, "btsName");
            return (Criteria) this;
        }

        public Criteria andBtsNameLike(String value) {
            addCriterion("BTS_NAME like", value, "btsName");
            return (Criteria) this;
        }

        public Criteria andBtsNameNotLike(String value) {
            addCriterion("BTS_NAME not like", value, "btsName");
            return (Criteria) this;
        }

        public Criteria andBtsNameIn(List<String> values) {
            addCriterion("BTS_NAME in", values, "btsName");
            return (Criteria) this;
        }

        public Criteria andBtsNameNotIn(List<String> values) {
            addCriterion("BTS_NAME not in", values, "btsName");
            return (Criteria) this;
        }

        public Criteria andBtsNameBetween(String value1, String value2) {
            addCriterion("BTS_NAME between", value1, value2, "btsName");
            return (Criteria) this;
        }

        public Criteria andBtsNameNotBetween(String value1, String value2) {
            addCriterion("BTS_NAME not between", value1, value2, "btsName");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNull() {
            addCriterion("CITY_ID is null");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNotNull() {
            addCriterion("CITY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCityIdEqualTo(BigDecimal value) {
            addCriterion("CITY_ID =", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotEqualTo(BigDecimal value) {
            addCriterion("CITY_ID <>", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThan(BigDecimal value) {
            addCriterion("CITY_ID >", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CITY_ID >=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThan(BigDecimal value) {
            addCriterion("CITY_ID <", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CITY_ID <=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdIn(List<BigDecimal> values) {
            addCriterion("CITY_ID in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotIn(List<BigDecimal> values) {
            addCriterion("CITY_ID not in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CITY_ID between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CITY_ID not between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andTimeStampIsNull() {
            addCriterion("TIME_STAMP is null");
            return (Criteria) this;
        }

        public Criteria andTimeStampIsNotNull() {
            addCriterion("TIME_STAMP is not null");
            return (Criteria) this;
        }

        public Criteria andTimeStampEqualTo(Date value) {
            addCriterionForJDBCDate("TIME_STAMP =", value, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andTimeStampNotEqualTo(Date value) {
            addCriterionForJDBCDate("TIME_STAMP <>", value, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andTimeStampGreaterThan(Date value) {
            addCriterionForJDBCDate("TIME_STAMP >", value, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andTimeStampGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("TIME_STAMP >=", value, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andTimeStampLessThan(Date value) {
            addCriterionForJDBCDate("TIME_STAMP <", value, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andTimeStampLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("TIME_STAMP <=", value, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andTimeStampIn(List<Date> values) {
            addCriterionForJDBCDate("TIME_STAMP in", values, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andTimeStampNotIn(List<Date> values) {
            addCriterionForJDBCDate("TIME_STAMP not in", values, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andTimeStampBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("TIME_STAMP between", value1, value2, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andTimeStampNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("TIME_STAMP not between", value1, value2, "timeStamp");
            return (Criteria) this;
        }

        public Criteria andConfirmedIsNull() {
            addCriterion("CONFIRMED is null");
            return (Criteria) this;
        }

        public Criteria andConfirmedIsNotNull() {
            addCriterion("CONFIRMED is not null");
            return (Criteria) this;
        }

        public Criteria andConfirmedEqualTo(BigDecimal value) {
            addCriterion("CONFIRMED =", value, "confirmed");
            return (Criteria) this;
        }

        public Criteria andConfirmedNotEqualTo(BigDecimal value) {
            addCriterion("CONFIRMED <>", value, "confirmed");
            return (Criteria) this;
        }

        public Criteria andConfirmedGreaterThan(BigDecimal value) {
            addCriterion("CONFIRMED >", value, "confirmed");
            return (Criteria) this;
        }

        public Criteria andConfirmedGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CONFIRMED >=", value, "confirmed");
            return (Criteria) this;
        }

        public Criteria andConfirmedLessThan(BigDecimal value) {
            addCriterion("CONFIRMED <", value, "confirmed");
            return (Criteria) this;
        }

        public Criteria andConfirmedLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CONFIRMED <=", value, "confirmed");
            return (Criteria) this;
        }

        public Criteria andConfirmedIn(List<BigDecimal> values) {
            addCriterion("CONFIRMED in", values, "confirmed");
            return (Criteria) this;
        }

        public Criteria andConfirmedNotIn(List<BigDecimal> values) {
            addCriterion("CONFIRMED not in", values, "confirmed");
            return (Criteria) this;
        }

        public Criteria andConfirmedBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CONFIRMED between", value1, value2, "confirmed");
            return (Criteria) this;
        }

        public Criteria andConfirmedNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CONFIRMED not between", value1, value2, "confirmed");
            return (Criteria) this;
        }

        public Criteria andCiIsNull() {
            addCriterion("CI is null");
            return (Criteria) this;
        }

        public Criteria andCiIsNotNull() {
            addCriterion("CI is not null");
            return (Criteria) this;
        }

        public Criteria andCiEqualTo(BigDecimal value) {
            addCriterion("CI =", value, "ci");
            return (Criteria) this;
        }

        public Criteria andCiNotEqualTo(BigDecimal value) {
            addCriterion("CI <>", value, "ci");
            return (Criteria) this;
        }

        public Criteria andCiGreaterThan(BigDecimal value) {
            addCriterion("CI >", value, "ci");
            return (Criteria) this;
        }

        public Criteria andCiGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CI >=", value, "ci");
            return (Criteria) this;
        }

        public Criteria andCiLessThan(BigDecimal value) {
            addCriterion("CI <", value, "ci");
            return (Criteria) this;
        }

        public Criteria andCiLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CI <=", value, "ci");
            return (Criteria) this;
        }

        public Criteria andCiIn(List<BigDecimal> values) {
            addCriterion("CI in", values, "ci");
            return (Criteria) this;
        }

        public Criteria andCiNotIn(List<BigDecimal> values) {
            addCriterion("CI not in", values, "ci");
            return (Criteria) this;
        }

        public Criteria andCiBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CI between", value1, value2, "ci");
            return (Criteria) this;
        }

        public Criteria andCiNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CI not between", value1, value2, "ci");
            return (Criteria) this;
        }

        public Criteria andSectorlocIsNull() {
            addCriterion("SECTORLOC is null");
            return (Criteria) this;
        }

        public Criteria andSectorlocIsNotNull() {
            addCriterion("SECTORLOC is not null");
            return (Criteria) this;
        }

        public Criteria andSectorlocEqualTo(BigDecimal value) {
            addCriterion("SECTORLOC =", value, "sectorloc");
            return (Criteria) this;
        }

        public Criteria andSectorlocNotEqualTo(BigDecimal value) {
            addCriterion("SECTORLOC <>", value, "sectorloc");
            return (Criteria) this;
        }

        public Criteria andSectorlocGreaterThan(BigDecimal value) {
            addCriterion("SECTORLOC >", value, "sectorloc");
            return (Criteria) this;
        }

        public Criteria andSectorlocGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SECTORLOC >=", value, "sectorloc");
            return (Criteria) this;
        }

        public Criteria andSectorlocLessThan(BigDecimal value) {
            addCriterion("SECTORLOC <", value, "sectorloc");
            return (Criteria) this;
        }

        public Criteria andSectorlocLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SECTORLOC <=", value, "sectorloc");
            return (Criteria) this;
        }

        public Criteria andSectorlocIn(List<BigDecimal> values) {
            addCriterion("SECTORLOC in", values, "sectorloc");
            return (Criteria) this;
        }

        public Criteria andSectorlocNotIn(List<BigDecimal> values) {
            addCriterion("SECTORLOC not in", values, "sectorloc");
            return (Criteria) this;
        }

        public Criteria andSectorlocBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SECTORLOC between", value1, value2, "sectorloc");
            return (Criteria) this;
        }

        public Criteria andSectorlocNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SECTORLOC not between", value1, value2, "sectorloc");
            return (Criteria) this;
        }

        public Criteria andNumfaIsNull() {
            addCriterion("NUMFA is null");
            return (Criteria) this;
        }

        public Criteria andNumfaIsNotNull() {
            addCriterion("NUMFA is not null");
            return (Criteria) this;
        }

        public Criteria andNumfaEqualTo(BigDecimal value) {
            addCriterion("NUMFA =", value, "numfa");
            return (Criteria) this;
        }

        public Criteria andNumfaNotEqualTo(BigDecimal value) {
            addCriterion("NUMFA <>", value, "numfa");
            return (Criteria) this;
        }

        public Criteria andNumfaGreaterThan(BigDecimal value) {
            addCriterion("NUMFA >", value, "numfa");
            return (Criteria) this;
        }

        public Criteria andNumfaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("NUMFA >=", value, "numfa");
            return (Criteria) this;
        }

        public Criteria andNumfaLessThan(BigDecimal value) {
            addCriterion("NUMFA <", value, "numfa");
            return (Criteria) this;
        }

        public Criteria andNumfaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("NUMFA <=", value, "numfa");
            return (Criteria) this;
        }

        public Criteria andNumfaIn(List<BigDecimal> values) {
            addCriterion("NUMFA in", values, "numfa");
            return (Criteria) this;
        }

        public Criteria andNumfaNotIn(List<BigDecimal> values) {
            addCriterion("NUMFA not in", values, "numfa");
            return (Criteria) this;
        }

        public Criteria andNumfaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NUMFA between", value1, value2, "numfa");
            return (Criteria) this;
        }

        public Criteria andNumfaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NUMFA not between", value1, value2, "numfa");
            return (Criteria) this;
        }

        public Criteria andCapacityIsNull() {
            addCriterion("CAPACITY is null");
            return (Criteria) this;
        }

        public Criteria andCapacityIsNotNull() {
            addCriterion("CAPACITY is not null");
            return (Criteria) this;
        }

        public Criteria andCapacityEqualTo(Double value) {
            addCriterion("CAPACITY =", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityNotEqualTo(Double value) {
            addCriterion("CAPACITY <>", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityGreaterThan(Double value) {
            addCriterion("CAPACITY >", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityGreaterThanOrEqualTo(Double value) {
            addCriterion("CAPACITY >=", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityLessThan(Double value) {
            addCriterion("CAPACITY <", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityLessThanOrEqualTo(Double value) {
            addCriterion("CAPACITY <=", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityIn(List<Double> values) {
            addCriterion("CAPACITY in", values, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityNotIn(List<Double> values) {
            addCriterion("CAPACITY not in", values, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityBetween(Double value1, Double value2) {
            addCriterion("CAPACITY between", value1, value2, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityNotBetween(Double value1, Double value2) {
            addCriterion("CAPACITY not between", value1, value2, "capacity");
            return (Criteria) this;
        }

        public Criteria andMicrocellIsNull() {
            addCriterion("MICROCELL is null");
            return (Criteria) this;
        }

        public Criteria andMicrocellIsNotNull() {
            addCriterion("MICROCELL is not null");
            return (Criteria) this;
        }

        public Criteria andMicrocellEqualTo(BigDecimal value) {
            addCriterion("MICROCELL =", value, "microcell");
            return (Criteria) this;
        }

        public Criteria andMicrocellNotEqualTo(BigDecimal value) {
            addCriterion("MICROCELL <>", value, "microcell");
            return (Criteria) this;
        }

        public Criteria andMicrocellGreaterThan(BigDecimal value) {
            addCriterion("MICROCELL >", value, "microcell");
            return (Criteria) this;
        }

        public Criteria andMicrocellGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MICROCELL >=", value, "microcell");
            return (Criteria) this;
        }

        public Criteria andMicrocellLessThan(BigDecimal value) {
            addCriterion("MICROCELL <", value, "microcell");
            return (Criteria) this;
        }

        public Criteria andMicrocellLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MICROCELL <=", value, "microcell");
            return (Criteria) this;
        }

        public Criteria andMicrocellIn(List<BigDecimal> values) {
            addCriterion("MICROCELL in", values, "microcell");
            return (Criteria) this;
        }

        public Criteria andMicrocellNotIn(List<BigDecimal> values) {
            addCriterion("MICROCELL not in", values, "microcell");
            return (Criteria) this;
        }

        public Criteria andMicrocellBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MICROCELL between", value1, value2, "microcell");
            return (Criteria) this;
        }

        public Criteria andMicrocellNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MICROCELL not between", value1, value2, "microcell");
            return (Criteria) this;
        }

        public Criteria andPnIsNull() {
            addCriterion("PN is null");
            return (Criteria) this;
        }

        public Criteria andPnIsNotNull() {
            addCriterion("PN is not null");
            return (Criteria) this;
        }

        public Criteria andPnEqualTo(BigDecimal value) {
            addCriterion("PN =", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnNotEqualTo(BigDecimal value) {
            addCriterion("PN <>", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnGreaterThan(BigDecimal value) {
            addCriterion("PN >", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PN >=", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnLessThan(BigDecimal value) {
            addCriterion("PN <", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PN <=", value, "pn");
            return (Criteria) this;
        }

        public Criteria andPnIn(List<BigDecimal> values) {
            addCriterion("PN in", values, "pn");
            return (Criteria) this;
        }

        public Criteria andPnNotIn(List<BigDecimal> values) {
            addCriterion("PN not in", values, "pn");
            return (Criteria) this;
        }

        public Criteria andPnBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PN between", value1, value2, "pn");
            return (Criteria) this;
        }

        public Criteria andPnNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PN not between", value1, value2, "pn");
            return (Criteria) this;
        }

        public Criteria andPnIncIsNull() {
            addCriterion("PN_INC is null");
            return (Criteria) this;
        }

        public Criteria andPnIncIsNotNull() {
            addCriterion("PN_INC is not null");
            return (Criteria) this;
        }

        public Criteria andPnIncEqualTo(BigDecimal value) {
            addCriterion("PN_INC =", value, "pnInc");
            return (Criteria) this;
        }

        public Criteria andPnIncNotEqualTo(BigDecimal value) {
            addCriterion("PN_INC <>", value, "pnInc");
            return (Criteria) this;
        }

        public Criteria andPnIncGreaterThan(BigDecimal value) {
            addCriterion("PN_INC >", value, "pnInc");
            return (Criteria) this;
        }

        public Criteria andPnIncGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PN_INC >=", value, "pnInc");
            return (Criteria) this;
        }

        public Criteria andPnIncLessThan(BigDecimal value) {
            addCriterion("PN_INC <", value, "pnInc");
            return (Criteria) this;
        }

        public Criteria andPnIncLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PN_INC <=", value, "pnInc");
            return (Criteria) this;
        }

        public Criteria andPnIncIn(List<BigDecimal> values) {
            addCriterion("PN_INC in", values, "pnInc");
            return (Criteria) this;
        }

        public Criteria andPnIncNotIn(List<BigDecimal> values) {
            addCriterion("PN_INC not in", values, "pnInc");
            return (Criteria) this;
        }

        public Criteria andPnIncBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PN_INC between", value1, value2, "pnInc");
            return (Criteria) this;
        }

        public Criteria andPnIncNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PN_INC not between", value1, value2, "pnInc");
            return (Criteria) this;
        }

        public Criteria andLacIsNull() {
            addCriterion("LAC is null");
            return (Criteria) this;
        }

        public Criteria andLacIsNotNull() {
            addCriterion("LAC is not null");
            return (Criteria) this;
        }

        public Criteria andLacEqualTo(BigDecimal value) {
            addCriterion("LAC =", value, "lac");
            return (Criteria) this;
        }

        public Criteria andLacNotEqualTo(BigDecimal value) {
            addCriterion("LAC <>", value, "lac");
            return (Criteria) this;
        }

        public Criteria andLacGreaterThan(BigDecimal value) {
            addCriterion("LAC >", value, "lac");
            return (Criteria) this;
        }

        public Criteria andLacGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("LAC >=", value, "lac");
            return (Criteria) this;
        }

        public Criteria andLacLessThan(BigDecimal value) {
            addCriterion("LAC <", value, "lac");
            return (Criteria) this;
        }

        public Criteria andLacLessThanOrEqualTo(BigDecimal value) {
            addCriterion("LAC <=", value, "lac");
            return (Criteria) this;
        }

        public Criteria andLacIn(List<BigDecimal> values) {
            addCriterion("LAC in", values, "lac");
            return (Criteria) this;
        }

        public Criteria andLacNotIn(List<BigDecimal> values) {
            addCriterion("LAC not in", values, "lac");
            return (Criteria) this;
        }

        public Criteria andLacBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAC between", value1, value2, "lac");
            return (Criteria) this;
        }

        public Criteria andLacNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("LAC not between", value1, value2, "lac");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(BigDecimal value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(BigDecimal value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(BigDecimal value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(BigDecimal value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(BigDecimal value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<BigDecimal> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<BigDecimal> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andDoCellIsNull() {
            addCriterion("DO_CELL is null");
            return (Criteria) this;
        }

        public Criteria andDoCellIsNotNull() {
            addCriterion("DO_CELL is not null");
            return (Criteria) this;
        }

        public Criteria andDoCellEqualTo(BigDecimal value) {
            addCriterion("DO_CELL =", value, "doCell");
            return (Criteria) this;
        }

        public Criteria andDoCellNotEqualTo(BigDecimal value) {
            addCriterion("DO_CELL <>", value, "doCell");
            return (Criteria) this;
        }

        public Criteria andDoCellGreaterThan(BigDecimal value) {
            addCriterion("DO_CELL >", value, "doCell");
            return (Criteria) this;
        }

        public Criteria andDoCellGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DO_CELL >=", value, "doCell");
            return (Criteria) this;
        }

        public Criteria andDoCellLessThan(BigDecimal value) {
            addCriterion("DO_CELL <", value, "doCell");
            return (Criteria) this;
        }

        public Criteria andDoCellLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DO_CELL <=", value, "doCell");
            return (Criteria) this;
        }

        public Criteria andDoCellIn(List<BigDecimal> values) {
            addCriterion("DO_CELL in", values, "doCell");
            return (Criteria) this;
        }

        public Criteria andDoCellNotIn(List<BigDecimal> values) {
            addCriterion("DO_CELL not in", values, "doCell");
            return (Criteria) this;
        }

        public Criteria andDoCellBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DO_CELL between", value1, value2, "doCell");
            return (Criteria) this;
        }

        public Criteria andDoCellNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DO_CELL not between", value1, value2, "doCell");
            return (Criteria) this;
        }

        public Criteria andRelatedRncIsNull() {
            addCriterion("RELATED_RNC is null");
            return (Criteria) this;
        }

        public Criteria andRelatedRncIsNotNull() {
            addCriterion("RELATED_RNC is not null");
            return (Criteria) this;
        }

        public Criteria andRelatedRncEqualTo(BigDecimal value) {
            addCriterion("RELATED_RNC =", value, "relatedRnc");
            return (Criteria) this;
        }

        public Criteria andRelatedRncNotEqualTo(BigDecimal value) {
            addCriterion("RELATED_RNC <>", value, "relatedRnc");
            return (Criteria) this;
        }

        public Criteria andRelatedRncGreaterThan(BigDecimal value) {
            addCriterion("RELATED_RNC >", value, "relatedRnc");
            return (Criteria) this;
        }

        public Criteria andRelatedRncGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RELATED_RNC >=", value, "relatedRnc");
            return (Criteria) this;
        }

        public Criteria andRelatedRncLessThan(BigDecimal value) {
            addCriterion("RELATED_RNC <", value, "relatedRnc");
            return (Criteria) this;
        }

        public Criteria andRelatedRncLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RELATED_RNC <=", value, "relatedRnc");
            return (Criteria) this;
        }

        public Criteria andRelatedRncIn(List<BigDecimal> values) {
            addCriterion("RELATED_RNC in", values, "relatedRnc");
            return (Criteria) this;
        }

        public Criteria andRelatedRncNotIn(List<BigDecimal> values) {
            addCriterion("RELATED_RNC not in", values, "relatedRnc");
            return (Criteria) this;
        }

        public Criteria andRelatedRncBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RELATED_RNC between", value1, value2, "relatedRnc");
            return (Criteria) this;
        }

        public Criteria andRelatedRncNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RELATED_RNC not between", value1, value2, "relatedRnc");
            return (Criteria) this;
        }

        public Criteria andRncNameIsNull() {
            addCriterion("RNC_NAME is null");
            return (Criteria) this;
        }

        public Criteria andRncNameIsNotNull() {
            addCriterion("RNC_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andRncNameEqualTo(String value) {
            addCriterion("RNC_NAME =", value, "rncName");
            return (Criteria) this;
        }

        public Criteria andRncNameNotEqualTo(String value) {
            addCriterion("RNC_NAME <>", value, "rncName");
            return (Criteria) this;
        }

        public Criteria andRncNameGreaterThan(String value) {
            addCriterion("RNC_NAME >", value, "rncName");
            return (Criteria) this;
        }

        public Criteria andRncNameGreaterThanOrEqualTo(String value) {
            addCriterion("RNC_NAME >=", value, "rncName");
            return (Criteria) this;
        }

        public Criteria andRncNameLessThan(String value) {
            addCriterion("RNC_NAME <", value, "rncName");
            return (Criteria) this;
        }

        public Criteria andRncNameLessThanOrEqualTo(String value) {
            addCriterion("RNC_NAME <=", value, "rncName");
            return (Criteria) this;
        }

        public Criteria andRncNameLike(String value) {
            addCriterion("RNC_NAME like", value, "rncName");
            return (Criteria) this;
        }

        public Criteria andRncNameNotLike(String value) {
            addCriterion("RNC_NAME not like", value, "rncName");
            return (Criteria) this;
        }

        public Criteria andRncNameIn(List<String> values) {
            addCriterion("RNC_NAME in", values, "rncName");
            return (Criteria) this;
        }

        public Criteria andRncNameNotIn(List<String> values) {
            addCriterion("RNC_NAME not in", values, "rncName");
            return (Criteria) this;
        }

        public Criteria andRncNameBetween(String value1, String value2) {
            addCriterion("RNC_NAME between", value1, value2, "rncName");
            return (Criteria) this;
        }

        public Criteria andRncNameNotBetween(String value1, String value2) {
            addCriterion("RNC_NAME not between", value1, value2, "rncName");
            return (Criteria) this;
        }

        public Criteria andSidIsNull() {
            addCriterion("SID is null");
            return (Criteria) this;
        }

        public Criteria andSidIsNotNull() {
            addCriterion("SID is not null");
            return (Criteria) this;
        }

        public Criteria andSidEqualTo(BigDecimal value) {
            addCriterion("SID =", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotEqualTo(BigDecimal value) {
            addCriterion("SID <>", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThan(BigDecimal value) {
            addCriterion("SID >", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SID >=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThan(BigDecimal value) {
            addCriterion("SID <", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SID <=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidIn(List<BigDecimal> values) {
            addCriterion("SID in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotIn(List<BigDecimal> values) {
            addCriterion("SID not in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SID between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SID not between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andNidIsNull() {
            addCriterion("NID is null");
            return (Criteria) this;
        }

        public Criteria andNidIsNotNull() {
            addCriterion("NID is not null");
            return (Criteria) this;
        }

        public Criteria andNidEqualTo(BigDecimal value) {
            addCriterion("NID =", value, "nid");
            return (Criteria) this;
        }

        public Criteria andNidNotEqualTo(BigDecimal value) {
            addCriterion("NID <>", value, "nid");
            return (Criteria) this;
        }

        public Criteria andNidGreaterThan(BigDecimal value) {
            addCriterion("NID >", value, "nid");
            return (Criteria) this;
        }

        public Criteria andNidGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("NID >=", value, "nid");
            return (Criteria) this;
        }

        public Criteria andNidLessThan(BigDecimal value) {
            addCriterion("NID <", value, "nid");
            return (Criteria) this;
        }

        public Criteria andNidLessThanOrEqualTo(BigDecimal value) {
            addCriterion("NID <=", value, "nid");
            return (Criteria) this;
        }

        public Criteria andNidIn(List<BigDecimal> values) {
            addCriterion("NID in", values, "nid");
            return (Criteria) this;
        }

        public Criteria andNidNotIn(List<BigDecimal> values) {
            addCriterion("NID not in", values, "nid");
            return (Criteria) this;
        }

        public Criteria andNidBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NID between", value1, value2, "nid");
            return (Criteria) this;
        }

        public Criteria andNidNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NID not between", value1, value2, "nid");
            return (Criteria) this;
        }

        public Criteria andNumfaDoIsNull() {
            addCriterion("NUMFA_DO is null");
            return (Criteria) this;
        }

        public Criteria andNumfaDoIsNotNull() {
            addCriterion("NUMFA_DO is not null");
            return (Criteria) this;
        }

        public Criteria andNumfaDoEqualTo(BigDecimal value) {
            addCriterion("NUMFA_DO =", value, "numfaDo");
            return (Criteria) this;
        }

        public Criteria andNumfaDoNotEqualTo(BigDecimal value) {
            addCriterion("NUMFA_DO <>", value, "numfaDo");
            return (Criteria) this;
        }

        public Criteria andNumfaDoGreaterThan(BigDecimal value) {
            addCriterion("NUMFA_DO >", value, "numfaDo");
            return (Criteria) this;
        }

        public Criteria andNumfaDoGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("NUMFA_DO >=", value, "numfaDo");
            return (Criteria) this;
        }

        public Criteria andNumfaDoLessThan(BigDecimal value) {
            addCriterion("NUMFA_DO <", value, "numfaDo");
            return (Criteria) this;
        }

        public Criteria andNumfaDoLessThanOrEqualTo(BigDecimal value) {
            addCriterion("NUMFA_DO <=", value, "numfaDo");
            return (Criteria) this;
        }

        public Criteria andNumfaDoIn(List<BigDecimal> values) {
            addCriterion("NUMFA_DO in", values, "numfaDo");
            return (Criteria) this;
        }

        public Criteria andNumfaDoNotIn(List<BigDecimal> values) {
            addCriterion("NUMFA_DO not in", values, "numfaDo");
            return (Criteria) this;
        }

        public Criteria andNumfaDoBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NUMFA_DO between", value1, value2, "numfaDo");
            return (Criteria) this;
        }

        public Criteria andNumfaDoNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NUMFA_DO not between", value1, value2, "numfaDo");
            return (Criteria) this;
        }

        public Criteria andRruCellIsNull() {
            addCriterion("RRU_CELL is null");
            return (Criteria) this;
        }

        public Criteria andRruCellIsNotNull() {
            addCriterion("RRU_CELL is not null");
            return (Criteria) this;
        }

        public Criteria andRruCellEqualTo(String value) {
            addCriterion("RRU_CELL =", value, "rruCell");
            return (Criteria) this;
        }

        public Criteria andRruCellNotEqualTo(String value) {
            addCriterion("RRU_CELL <>", value, "rruCell");
            return (Criteria) this;
        }

        public Criteria andRruCellGreaterThan(String value) {
            addCriterion("RRU_CELL >", value, "rruCell");
            return (Criteria) this;
        }

        public Criteria andRruCellGreaterThanOrEqualTo(String value) {
            addCriterion("RRU_CELL >=", value, "rruCell");
            return (Criteria) this;
        }

        public Criteria andRruCellLessThan(String value) {
            addCriterion("RRU_CELL <", value, "rruCell");
            return (Criteria) this;
        }

        public Criteria andRruCellLessThanOrEqualTo(String value) {
            addCriterion("RRU_CELL <=", value, "rruCell");
            return (Criteria) this;
        }

        public Criteria andRruCellLike(String value) {
            addCriterion("RRU_CELL like", value, "rruCell");
            return (Criteria) this;
        }

        public Criteria andRruCellNotLike(String value) {
            addCriterion("RRU_CELL not like", value, "rruCell");
            return (Criteria) this;
        }

        public Criteria andRruCellIn(List<String> values) {
            addCriterion("RRU_CELL in", values, "rruCell");
            return (Criteria) this;
        }

        public Criteria andRruCellNotIn(List<String> values) {
            addCriterion("RRU_CELL not in", values, "rruCell");
            return (Criteria) this;
        }

        public Criteria andRruCellBetween(String value1, String value2) {
            addCriterion("RRU_CELL between", value1, value2, "rruCell");
            return (Criteria) this;
        }

        public Criteria andRruCellNotBetween(String value1, String value2) {
            addCriterion("RRU_CELL not between", value1, value2, "rruCell");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table C_CELL
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 10 15:30:30 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table C_CELL
     *
     * @mbggenerated Wed Apr 10 15:30:30 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}