package com.scttsc.business.model;

import com.scttsc.admin.model.City;
import com.scttsc.baselibs.model.Cons;
import com.scttsc.common.util.DateUtils;

import java.math.BigDecimal;
import java.util.Date;

public class Cell {

    private String intId;
    private String name;
    private BigDecimal cityId;
    private BigDecimal countryId;
    private String isIndoor;
    private String isRru;
    private String isGf;
    private BigDecimal isOr;
    private BigDecimal isRr;
    private BigDecimal isSr;
    private Long wyBtsIntId;
    private BigDecimal deleteFlag;
    private BigDecimal manualFlag;

    private int btsId;
    private int cellId;
    private String bscName;
    private int ci;
    private int pn;
    private int lac;
    private int doCell;
    private Long relatedBts;


    private City country;//区县

    //一对一关联C_CELL
    private Ccell ccell;


    public City getCountry() {
        return country;
    }

    public void setCountry(City country) {
        this.country = country;
    }


    private Date deletetime;

    private String deleteTimeStr;

    private Date updatetime;

    private Long deleteResoncode;

    private String deleteText;

    private String updatetimeStr;

    public Cons getCons() {
        return cons;
    }

    public void setCons(Cons cons) {
        this.cons = cons;
    }

    private Cons cons;

    public String getIndoor() {
        return isIndoor;
    }

    public void setIndoor(String indoor) {
        isIndoor = indoor;
    }

    public String getRru() {
        return isRru;
    }

    public void setRru(String rru) {
        isRru = rru;
    }

    public String getDeleteText() {
        return deleteText;
    }

    public void setDeleteText(String deleteText) {
        this.deleteText = deleteText;
    }

    public Long getDeleteResoncode() {
        return deleteResoncode;
    }

    public void setDeleteResoncode(Long deleteResoncode) {
        this.deleteResoncode = deleteResoncode;
    }

    public BigDecimal getSr() {
        return isSr;
    }

    public void setSr(BigDecimal sr) {
        isSr = sr;
    }

    public BigDecimal getRr() {
        return isRr;
    }

    public void setRr(BigDecimal rr) {
        isRr = rr;
    }

    public BigDecimal getOr() {
        return isOr;
    }

    public void setOr(BigDecimal or) {
        isOr = or;
    }

    public String getGf() {
        return isGf;
    }

    public void setGf(String gf) {
        isGf = gf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL.INT_ID
     *
     * @return the value of WY_CELL.INT_ID
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public String getIntId() {
        return intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL.INT_ID
     *
     * @param intId the value for WY_CELL.INT_ID
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public void setIntId(String intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL.NAME
     *
     * @return the value of WY_CELL.NAME
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL.NAME
     *
     * @param name the value for WY_CELL.NAME
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL.CITY_ID
     *
     * @return the value of WY_CELL.CITY_ID
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public BigDecimal getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL.CITY_ID
     *
     * @param cityId the value for WY_CELL.CITY_ID
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public void setCityId(BigDecimal cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL.COUNTRY_ID
     *
     * @return the value of WY_CELL.COUNTRY_ID
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public BigDecimal getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL.COUNTRY_ID
     *
     * @param countryId the value for WY_CELL.COUNTRY_ID
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public void setCountryId(BigDecimal countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL.IS_INDOOR
     *
     * @return the value of WY_CELL.IS_INDOOR
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public String getIsIndoor() {
        return isIndoor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL.IS_INDOOR
     *
     * @param isIndoor the value for WY_CELL.IS_INDOOR
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public void setIsIndoor(String isIndoor) {
        this.isIndoor = isIndoor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL.IS_RRU
     *
     * @return the value of WY_CELL.IS_RRU
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public String getIsRru() {
        return isRru;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL.IS_RRU
     *
     * @param isRru the value for WY_CELL.IS_RRU
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public void setIsRru(String isRru) {
        this.isRru = isRru;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL.IS_GF
     *
     * @return the value of WY_CELL.IS_GF
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public String getIsGf() {
        return isGf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL.IS_GF
     *
     * @param isGf the value for WY_CELL.IS_GF
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public void setIsGf(String isGf) {
        this.isGf = isGf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL.IS_OR
     *
     * @return the value of WY_CELL.IS_OR
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public BigDecimal getIsOr() {
        return isOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL.IS_OR
     *
     * @param isOr the value for WY_CELL.IS_OR
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public void setIsOr(BigDecimal isOr) {
        this.isOr = isOr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL.IS_RR
     *
     * @return the value of WY_CELL.IS_RR
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public BigDecimal getIsRr() {
        return isRr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL.IS_RR
     *
     * @param isRr the value for WY_CELL.IS_RR
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public void setIsRr(BigDecimal isRr) {
        this.isRr = isRr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL.IS_SR
     *
     * @return the value of WY_CELL.IS_SR
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public BigDecimal getIsSr() {
        return isSr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL.IS_SR
     *
     * @param isSr the value for WY_CELL.IS_SR
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public void setIsSr(BigDecimal isSr) {
        this.isSr = isSr;
    }

    public Long getWyBtsIntId() {
        return wyBtsIntId;
    }

    public void setWyBtsIntId(Long wyBtsIntId) {
        this.wyBtsIntId = wyBtsIntId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL.DELETE_FLAG
     *
     * @return the value of WY_CELL.DELETE_FLAG
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public BigDecimal getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL.DELETE_FLAG
     *
     * @param deleteFlag the value for WY_CELL.DELETE_FLAG
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public void setDeleteFlag(BigDecimal deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL.MANUAL_FLAG
     *
     * @return the value of WY_CELL.MANUAL_FLAG
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public BigDecimal getManualFlag() {
        return manualFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL.MANUAL_FLAG
     *
     * @param manualFlag the value for WY_CELL.MANUAL_FLAG
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public void setManualFlag(BigDecimal manualFlag) {
        this.manualFlag = manualFlag;
    }

    public Date getDeletetime() {
        return deletetime;
    }

    public void setDeletetime(Date deletetime) {
        this.deletetime = deletetime;
    }

    public String getDeleteTimeStr() {
         return deletetime==null?"": DateUtils.DateToStr(deletetime, "yyyy-MM-dd");
    }

    public void setDeleteTimeStr(String deleteTimeStr) {
        this.deleteTimeStr = deleteTimeStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL.UPDATETIME
     *
     * @return the value of WY_CELL.UPDATETIME
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL.UPDATETIME
     *
     * @param updatetime the value for WY_CELL.UPDATETIME
     * @mbggenerated Sun Mar 31 10:46:37 CST 2013
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }


    private String cityName;

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public Ccell getCcell() {
        return ccell;
    }

    public void setCcell(Ccell ccell) {
        this.ccell = ccell;
    }

    public int getBtsId() {
        return btsId;
    }

    public void setBtsId(int btsId) {
        this.btsId = btsId;
    }

    public int getCellId() {
        return cellId;
    }

    public void setCellId(int cellId) {
        this.cellId = cellId;
    }

    public String getBscName() {
        return bscName;
    }

    public void setBscName(String bscName) {
        this.bscName = bscName;
    }

    public int getCi() {
        return ci;
    }

    public void setCi(int ci) {
        this.ci = ci;
    }

    public Long getRelatedBts() {
        return relatedBts;
    }

    public void setRelatedBts(Long relatedBts) {
        this.relatedBts = relatedBts;
    }

    public int getLac() {
        return lac;
    }

    public void setLac(int lac) {
        this.lac = lac;
    }

    public int getDoCell() {
        return doCell;
    }

    public void setDoCell(int doCell) {
        this.doCell = doCell;
    }

    public int getPn() {
        return pn;
    }

    public void setPn(int pn) {
        this.pn = pn;
    }

    public String getUpdatetimeStr() {
        return  updatetime==null?"": DateUtils.DateToStr( updatetime, "yyyy-MM-dd");
    }

    public void setUpdatetimeStr(String updatetimeStr) {
        this.updatetimeStr = updatetimeStr;
    }
}