package com.scttsc.business.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CellManualExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WY_CELL_MANUAL
     *
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WY_CELL_MANUAL
     *
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WY_CELL_MANUAL
     *
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WY_CELL_MANUAL
     *
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public CellManualExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WY_CELL_MANUAL
     *
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WY_CELL_MANUAL
     *
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WY_CELL_MANUAL
     *
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WY_CELL_MANUAL
     *
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WY_CELL_MANUAL
     *
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WY_CELL_MANUAL
     *
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WY_CELL_MANUAL
     *
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WY_CELL_MANUAL
     *
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WY_CELL_MANUAL
     *
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WY_CELL_MANUAL
     *
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WY_CELL_MANUAL
     *
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIntIdIsNull() {
            addCriterion("INT_ID is null");
            return (Criteria) this;
        }

        public Criteria andIntIdIsNotNull() {
            addCriterion("INT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andIntIdEqualTo(BigDecimal value) {
            addCriterion("INT_ID =", value, "intId");
            return (Criteria) this;
        }

        public Criteria andIntIdNotEqualTo(BigDecimal value) {
            addCriterion("INT_ID <>", value, "intId");
            return (Criteria) this;
        }

        public Criteria andIntIdGreaterThan(BigDecimal value) {
            addCriterion("INT_ID >", value, "intId");
            return (Criteria) this;
        }

        public Criteria andIntIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INT_ID >=", value, "intId");
            return (Criteria) this;
        }

        public Criteria andIntIdLessThan(BigDecimal value) {
            addCriterion("INT_ID <", value, "intId");
            return (Criteria) this;
        }

        public Criteria andIntIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INT_ID <=", value, "intId");
            return (Criteria) this;
        }

        public Criteria andIntIdIn(List<BigDecimal> values) {
            addCriterion("INT_ID in", values, "intId");
            return (Criteria) this;
        }

        public Criteria andIntIdNotIn(List<BigDecimal> values) {
            addCriterion("INT_ID not in", values, "intId");
            return (Criteria) this;
        }

        public Criteria andIntIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INT_ID between", value1, value2, "intId");
            return (Criteria) this;
        }

        public Criteria andIntIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INT_ID not between", value1, value2, "intId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andBscNameIsNull() {
            addCriterion("BSC_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBscNameIsNotNull() {
            addCriterion("BSC_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBscNameEqualTo(String value) {
            addCriterion("BSC_NAME =", value, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameNotEqualTo(String value) {
            addCriterion("BSC_NAME <>", value, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameGreaterThan(String value) {
            addCriterion("BSC_NAME >", value, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameGreaterThanOrEqualTo(String value) {
            addCriterion("BSC_NAME >=", value, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameLessThan(String value) {
            addCriterion("BSC_NAME <", value, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameLessThanOrEqualTo(String value) {
            addCriterion("BSC_NAME <=", value, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameLike(String value) {
            addCriterion("BSC_NAME like", value, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameNotLike(String value) {
            addCriterion("BSC_NAME not like", value, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameIn(List<String> values) {
            addCriterion("BSC_NAME in", values, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameNotIn(List<String> values) {
            addCriterion("BSC_NAME not in", values, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameBetween(String value1, String value2) {
            addCriterion("BSC_NAME between", value1, value2, "bscName");
            return (Criteria) this;
        }

        public Criteria andBscNameNotBetween(String value1, String value2) {
            addCriterion("BSC_NAME not between", value1, value2, "bscName");
            return (Criteria) this;
        }

        public Criteria andCiIsNull() {
            addCriterion("CI is null");
            return (Criteria) this;
        }

        public Criteria andCiIsNotNull() {
            addCriterion("CI is not null");
            return (Criteria) this;
        }

        public Criteria andCiEqualTo(BigDecimal value) {
            addCriterion("CI =", value, "ci");
            return (Criteria) this;
        }

        public Criteria andCiNotEqualTo(BigDecimal value) {
            addCriterion("CI <>", value, "ci");
            return (Criteria) this;
        }

        public Criteria andCiGreaterThan(BigDecimal value) {
            addCriterion("CI >", value, "ci");
            return (Criteria) this;
        }

        public Criteria andCiGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CI >=", value, "ci");
            return (Criteria) this;
        }

        public Criteria andCiLessThan(BigDecimal value) {
            addCriterion("CI <", value, "ci");
            return (Criteria) this;
        }

        public Criteria andCiLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CI <=", value, "ci");
            return (Criteria) this;
        }

        public Criteria andCiIn(List<BigDecimal> values) {
            addCriterion("CI in", values, "ci");
            return (Criteria) this;
        }

        public Criteria andCiNotIn(List<BigDecimal> values) {
            addCriterion("CI not in", values, "ci");
            return (Criteria) this;
        }

        public Criteria andCiBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CI between", value1, value2, "ci");
            return (Criteria) this;
        }

        public Criteria andCiNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CI not between", value1, value2, "ci");
            return (Criteria) this;
        }

        public Criteria andGfflagIsNull() {
            addCriterion("GFFLAG is null");
            return (Criteria) this;
        }

        public Criteria andGfflagIsNotNull() {
            addCriterion("GFFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andGfflagEqualTo(String value) {
            addCriterion("GFFLAG =", value, "gfflag");
            return (Criteria) this;
        }

        public Criteria andGfflagNotEqualTo(String value) {
            addCriterion("GFFLAG <>", value, "gfflag");
            return (Criteria) this;
        }

        public Criteria andGfflagGreaterThan(String value) {
            addCriterion("GFFLAG >", value, "gfflag");
            return (Criteria) this;
        }

        public Criteria andGfflagGreaterThanOrEqualTo(String value) {
            addCriterion("GFFLAG >=", value, "gfflag");
            return (Criteria) this;
        }

        public Criteria andGfflagLessThan(String value) {
            addCriterion("GFFLAG <", value, "gfflag");
            return (Criteria) this;
        }

        public Criteria andGfflagLessThanOrEqualTo(String value) {
            addCriterion("GFFLAG <=", value, "gfflag");
            return (Criteria) this;
        }

        public Criteria andGfflagLike(String value) {
            addCriterion("GFFLAG like", value, "gfflag");
            return (Criteria) this;
        }

        public Criteria andGfflagNotLike(String value) {
            addCriterion("GFFLAG not like", value, "gfflag");
            return (Criteria) this;
        }

        public Criteria andGfflagIn(List<String> values) {
            addCriterion("GFFLAG in", values, "gfflag");
            return (Criteria) this;
        }

        public Criteria andGfflagNotIn(List<String> values) {
            addCriterion("GFFLAG not in", values, "gfflag");
            return (Criteria) this;
        }

        public Criteria andGfflagBetween(String value1, String value2) {
            addCriterion("GFFLAG between", value1, value2, "gfflag");
            return (Criteria) this;
        }

        public Criteria andGfflagNotBetween(String value1, String value2) {
            addCriterion("GFFLAG not between", value1, value2, "gfflag");
            return (Criteria) this;
        }

        public Criteria andGfnumIsNull() {
            addCriterion("GFNUM is null");
            return (Criteria) this;
        }

        public Criteria andGfnumIsNotNull() {
            addCriterion("GFNUM is not null");
            return (Criteria) this;
        }

        public Criteria andGfnumEqualTo(BigDecimal value) {
            addCriterion("GFNUM =", value, "gfnum");
            return (Criteria) this;
        }

        public Criteria andGfnumNotEqualTo(BigDecimal value) {
            addCriterion("GFNUM <>", value, "gfnum");
            return (Criteria) this;
        }

        public Criteria andGfnumGreaterThan(BigDecimal value) {
            addCriterion("GFNUM >", value, "gfnum");
            return (Criteria) this;
        }

        public Criteria andGfnumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("GFNUM >=", value, "gfnum");
            return (Criteria) this;
        }

        public Criteria andGfnumLessThan(BigDecimal value) {
            addCriterion("GFNUM <", value, "gfnum");
            return (Criteria) this;
        }

        public Criteria andGfnumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("GFNUM <=", value, "gfnum");
            return (Criteria) this;
        }

        public Criteria andGfnumIn(List<BigDecimal> values) {
            addCriterion("GFNUM in", values, "gfnum");
            return (Criteria) this;
        }

        public Criteria andGfnumNotIn(List<BigDecimal> values) {
            addCriterion("GFNUM not in", values, "gfnum");
            return (Criteria) this;
        }

        public Criteria andGfnumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GFNUM between", value1, value2, "gfnum");
            return (Criteria) this;
        }

        public Criteria andGfnumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GFNUM not between", value1, value2, "gfnum");
            return (Criteria) this;
        }

        public Criteria andCelltypeIsNull() {
            addCriterion("CELLTYPE is null");
            return (Criteria) this;
        }

        public Criteria andCelltypeIsNotNull() {
            addCriterion("CELLTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCelltypeEqualTo(String value) {
            addCriterion("CELLTYPE =", value, "celltype");
            return (Criteria) this;
        }

        public Criteria andCelltypeNotEqualTo(String value) {
            addCriterion("CELLTYPE <>", value, "celltype");
            return (Criteria) this;
        }

        public Criteria andCelltypeGreaterThan(String value) {
            addCriterion("CELLTYPE >", value, "celltype");
            return (Criteria) this;
        }

        public Criteria andCelltypeGreaterThanOrEqualTo(String value) {
            addCriterion("CELLTYPE >=", value, "celltype");
            return (Criteria) this;
        }

        public Criteria andCelltypeLessThan(String value) {
            addCriterion("CELLTYPE <", value, "celltype");
            return (Criteria) this;
        }

        public Criteria andCelltypeLessThanOrEqualTo(String value) {
            addCriterion("CELLTYPE <=", value, "celltype");
            return (Criteria) this;
        }

        public Criteria andCelltypeLike(String value) {
            addCriterion("CELLTYPE like", value, "celltype");
            return (Criteria) this;
        }

        public Criteria andCelltypeNotLike(String value) {
            addCriterion("CELLTYPE not like", value, "celltype");
            return (Criteria) this;
        }

        public Criteria andCelltypeIn(List<String> values) {
            addCriterion("CELLTYPE in", values, "celltype");
            return (Criteria) this;
        }

        public Criteria andCelltypeNotIn(List<String> values) {
            addCriterion("CELLTYPE not in", values, "celltype");
            return (Criteria) this;
        }

        public Criteria andCelltypeBetween(String value1, String value2) {
            addCriterion("CELLTYPE between", value1, value2, "celltype");
            return (Criteria) this;
        }

        public Criteria andCelltypeNotBetween(String value1, String value2) {
            addCriterion("CELLTYPE not between", value1, value2, "celltype");
            return (Criteria) this;
        }

        public Criteria andIndoornumIsNull() {
            addCriterion("INDOORNUM is null");
            return (Criteria) this;
        }

        public Criteria andIndoornumIsNotNull() {
            addCriterion("INDOORNUM is not null");
            return (Criteria) this;
        }

        public Criteria andIndoornumEqualTo(BigDecimal value) {
            addCriterion("INDOORNUM =", value, "indoornum");
            return (Criteria) this;
        }

        public Criteria andIndoornumNotEqualTo(BigDecimal value) {
            addCriterion("INDOORNUM <>", value, "indoornum");
            return (Criteria) this;
        }

        public Criteria andIndoornumGreaterThan(BigDecimal value) {
            addCriterion("INDOORNUM >", value, "indoornum");
            return (Criteria) this;
        }

        public Criteria andIndoornumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INDOORNUM >=", value, "indoornum");
            return (Criteria) this;
        }

        public Criteria andIndoornumLessThan(BigDecimal value) {
            addCriterion("INDOORNUM <", value, "indoornum");
            return (Criteria) this;
        }

        public Criteria andIndoornumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INDOORNUM <=", value, "indoornum");
            return (Criteria) this;
        }

        public Criteria andIndoornumIn(List<BigDecimal> values) {
            addCriterion("INDOORNUM in", values, "indoornum");
            return (Criteria) this;
        }

        public Criteria andIndoornumNotIn(List<BigDecimal> values) {
            addCriterion("INDOORNUM not in", values, "indoornum");
            return (Criteria) this;
        }

        public Criteria andIndoornumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INDOORNUM between", value1, value2, "indoornum");
            return (Criteria) this;
        }

        public Criteria andIndoornumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INDOORNUM not between", value1, value2, "indoornum");
            return (Criteria) this;
        }

        public Criteria andBorderflagIsNull() {
            addCriterion("BORDERFLAG is null");
            return (Criteria) this;
        }

        public Criteria andBorderflagIsNotNull() {
            addCriterion("BORDERFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andBorderflagEqualTo(String value) {
            addCriterion("BORDERFLAG =", value, "borderflag");
            return (Criteria) this;
        }

        public Criteria andBorderflagNotEqualTo(String value) {
            addCriterion("BORDERFLAG <>", value, "borderflag");
            return (Criteria) this;
        }

        public Criteria andBorderflagGreaterThan(String value) {
            addCriterion("BORDERFLAG >", value, "borderflag");
            return (Criteria) this;
        }

        public Criteria andBorderflagGreaterThanOrEqualTo(String value) {
            addCriterion("BORDERFLAG >=", value, "borderflag");
            return (Criteria) this;
        }

        public Criteria andBorderflagLessThan(String value) {
            addCriterion("BORDERFLAG <", value, "borderflag");
            return (Criteria) this;
        }

        public Criteria andBorderflagLessThanOrEqualTo(String value) {
            addCriterion("BORDERFLAG <=", value, "borderflag");
            return (Criteria) this;
        }

        public Criteria andBorderflagLike(String value) {
            addCriterion("BORDERFLAG like", value, "borderflag");
            return (Criteria) this;
        }

        public Criteria andBorderflagNotLike(String value) {
            addCriterion("BORDERFLAG not like", value, "borderflag");
            return (Criteria) this;
        }

        public Criteria andBorderflagIn(List<String> values) {
            addCriterion("BORDERFLAG in", values, "borderflag");
            return (Criteria) this;
        }

        public Criteria andBorderflagNotIn(List<String> values) {
            addCriterion("BORDERFLAG not in", values, "borderflag");
            return (Criteria) this;
        }

        public Criteria andBorderflagBetween(String value1, String value2) {
            addCriterion("BORDERFLAG between", value1, value2, "borderflag");
            return (Criteria) this;
        }

        public Criteria andBorderflagNotBetween(String value1, String value2) {
            addCriterion("BORDERFLAG not between", value1, value2, "borderflag");
            return (Criteria) this;
        }

        public Criteria andDofrqnumIsNull() {
            addCriterion("DOFRQNUM is null");
            return (Criteria) this;
        }

        public Criteria andDofrqnumIsNotNull() {
            addCriterion("DOFRQNUM is not null");
            return (Criteria) this;
        }

        public Criteria andDofrqnumEqualTo(BigDecimal value) {
            addCriterion("DOFRQNUM =", value, "dofrqnum");
            return (Criteria) this;
        }

        public Criteria andDofrqnumNotEqualTo(BigDecimal value) {
            addCriterion("DOFRQNUM <>", value, "dofrqnum");
            return (Criteria) this;
        }

        public Criteria andDofrqnumGreaterThan(BigDecimal value) {
            addCriterion("DOFRQNUM >", value, "dofrqnum");
            return (Criteria) this;
        }

        public Criteria andDofrqnumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DOFRQNUM >=", value, "dofrqnum");
            return (Criteria) this;
        }

        public Criteria andDofrqnumLessThan(BigDecimal value) {
            addCriterion("DOFRQNUM <", value, "dofrqnum");
            return (Criteria) this;
        }

        public Criteria andDofrqnumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DOFRQNUM <=", value, "dofrqnum");
            return (Criteria) this;
        }

        public Criteria andDofrqnumIn(List<BigDecimal> values) {
            addCriterion("DOFRQNUM in", values, "dofrqnum");
            return (Criteria) this;
        }

        public Criteria andDofrqnumNotIn(List<BigDecimal> values) {
            addCriterion("DOFRQNUM not in", values, "dofrqnum");
            return (Criteria) this;
        }

        public Criteria andDofrqnumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DOFRQNUM between", value1, value2, "dofrqnum");
            return (Criteria) this;
        }

        public Criteria andDofrqnumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DOFRQNUM not between", value1, value2, "dofrqnum");
            return (Criteria) this;
        }

        public Criteria andDopnIsNull() {
            addCriterion("DOPN is null");
            return (Criteria) this;
        }

        public Criteria andDopnIsNotNull() {
            addCriterion("DOPN is not null");
            return (Criteria) this;
        }

        public Criteria andDopnEqualTo(BigDecimal value) {
            addCriterion("DOPN =", value, "dopn");
            return (Criteria) this;
        }

        public Criteria andDopnNotEqualTo(BigDecimal value) {
            addCriterion("DOPN <>", value, "dopn");
            return (Criteria) this;
        }

        public Criteria andDopnGreaterThan(BigDecimal value) {
            addCriterion("DOPN >", value, "dopn");
            return (Criteria) this;
        }

        public Criteria andDopnGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DOPN >=", value, "dopn");
            return (Criteria) this;
        }

        public Criteria andDopnLessThan(BigDecimal value) {
            addCriterion("DOPN <", value, "dopn");
            return (Criteria) this;
        }

        public Criteria andDopnLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DOPN <=", value, "dopn");
            return (Criteria) this;
        }

        public Criteria andDopnIn(List<BigDecimal> values) {
            addCriterion("DOPN in", values, "dopn");
            return (Criteria) this;
        }

        public Criteria andDopnNotIn(List<BigDecimal> values) {
            addCriterion("DOPN not in", values, "dopn");
            return (Criteria) this;
        }

        public Criteria andDopnBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DOPN between", value1, value2, "dopn");
            return (Criteria) this;
        }

        public Criteria andDopnNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DOPN not between", value1, value2, "dopn");
            return (Criteria) this;
        }

        public Criteria andFeederlengthIsNull() {
            addCriterion("FEEDERLENGTH is null");
            return (Criteria) this;
        }

        public Criteria andFeederlengthIsNotNull() {
            addCriterion("FEEDERLENGTH is not null");
            return (Criteria) this;
        }

        public Criteria andFeederlengthEqualTo(BigDecimal value) {
            addCriterion("FEEDERLENGTH =", value, "feederlength");
            return (Criteria) this;
        }

        public Criteria andFeederlengthNotEqualTo(BigDecimal value) {
            addCriterion("FEEDERLENGTH <>", value, "feederlength");
            return (Criteria) this;
        }

        public Criteria andFeederlengthGreaterThan(BigDecimal value) {
            addCriterion("FEEDERLENGTH >", value, "feederlength");
            return (Criteria) this;
        }

        public Criteria andFeederlengthGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FEEDERLENGTH >=", value, "feederlength");
            return (Criteria) this;
        }

        public Criteria andFeederlengthLessThan(BigDecimal value) {
            addCriterion("FEEDERLENGTH <", value, "feederlength");
            return (Criteria) this;
        }

        public Criteria andFeederlengthLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FEEDERLENGTH <=", value, "feederlength");
            return (Criteria) this;
        }

        public Criteria andFeederlengthIn(List<BigDecimal> values) {
            addCriterion("FEEDERLENGTH in", values, "feederlength");
            return (Criteria) this;
        }

        public Criteria andFeederlengthNotIn(List<BigDecimal> values) {
            addCriterion("FEEDERLENGTH not in", values, "feederlength");
            return (Criteria) this;
        }

        public Criteria andFeederlengthBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FEEDERLENGTH between", value1, value2, "feederlength");
            return (Criteria) this;
        }

        public Criteria andFeederlengthNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FEEDERLENGTH not between", value1, value2, "feederlength");
            return (Criteria) this;
        }

        public Criteria andCoverareaIsNull() {
            addCriterion("COVERAREA is null");
            return (Criteria) this;
        }

        public Criteria andCoverareaIsNotNull() {
            addCriterion("COVERAREA is not null");
            return (Criteria) this;
        }

        public Criteria andCoverareaEqualTo(String value) {
            addCriterion("COVERAREA =", value, "coverarea");
            return (Criteria) this;
        }

        public Criteria andCoverareaNotEqualTo(String value) {
            addCriterion("COVERAREA <>", value, "coverarea");
            return (Criteria) this;
        }

        public Criteria andCoverareaGreaterThan(String value) {
            addCriterion("COVERAREA >", value, "coverarea");
            return (Criteria) this;
        }

        public Criteria andCoverareaGreaterThanOrEqualTo(String value) {
            addCriterion("COVERAREA >=", value, "coverarea");
            return (Criteria) this;
        }

        public Criteria andCoverareaLessThan(String value) {
            addCriterion("COVERAREA <", value, "coverarea");
            return (Criteria) this;
        }

        public Criteria andCoverareaLessThanOrEqualTo(String value) {
            addCriterion("COVERAREA <=", value, "coverarea");
            return (Criteria) this;
        }

        public Criteria andCoverareaLike(String value) {
            addCriterion("COVERAREA like", value, "coverarea");
            return (Criteria) this;
        }

        public Criteria andCoverareaNotLike(String value) {
            addCriterion("COVERAREA not like", value, "coverarea");
            return (Criteria) this;
        }

        public Criteria andCoverareaIn(List<String> values) {
            addCriterion("COVERAREA in", values, "coverarea");
            return (Criteria) this;
        }

        public Criteria andCoverareaNotIn(List<String> values) {
            addCriterion("COVERAREA not in", values, "coverarea");
            return (Criteria) this;
        }

        public Criteria andCoverareaBetween(String value1, String value2) {
            addCriterion("COVERAREA between", value1, value2, "coverarea");
            return (Criteria) this;
        }

        public Criteria andCoverareaNotBetween(String value1, String value2) {
            addCriterion("COVERAREA not between", value1, value2, "coverarea");
            return (Criteria) this;
        }

        public Criteria andCoverroadIsNull() {
            addCriterion("COVERROAD is null");
            return (Criteria) this;
        }

        public Criteria andCoverroadIsNotNull() {
            addCriterion("COVERROAD is not null");
            return (Criteria) this;
        }

        public Criteria andCoverroadEqualTo(String value) {
            addCriterion("COVERROAD =", value, "coverroad");
            return (Criteria) this;
        }

        public Criteria andCoverroadNotEqualTo(String value) {
            addCriterion("COVERROAD <>", value, "coverroad");
            return (Criteria) this;
        }

        public Criteria andCoverroadGreaterThan(String value) {
            addCriterion("COVERROAD >", value, "coverroad");
            return (Criteria) this;
        }

        public Criteria andCoverroadGreaterThanOrEqualTo(String value) {
            addCriterion("COVERROAD >=", value, "coverroad");
            return (Criteria) this;
        }

        public Criteria andCoverroadLessThan(String value) {
            addCriterion("COVERROAD <", value, "coverroad");
            return (Criteria) this;
        }

        public Criteria andCoverroadLessThanOrEqualTo(String value) {
            addCriterion("COVERROAD <=", value, "coverroad");
            return (Criteria) this;
        }

        public Criteria andCoverroadLike(String value) {
            addCriterion("COVERROAD like", value, "coverroad");
            return (Criteria) this;
        }

        public Criteria andCoverroadNotLike(String value) {
            addCriterion("COVERROAD not like", value, "coverroad");
            return (Criteria) this;
        }

        public Criteria andCoverroadIn(List<String> values) {
            addCriterion("COVERROAD in", values, "coverroad");
            return (Criteria) this;
        }

        public Criteria andCoverroadNotIn(List<String> values) {
            addCriterion("COVERROAD not in", values, "coverroad");
            return (Criteria) this;
        }

        public Criteria andCoverroadBetween(String value1, String value2) {
            addCriterion("COVERROAD between", value1, value2, "coverroad");
            return (Criteria) this;
        }

        public Criteria andCoverroadNotBetween(String value1, String value2) {
            addCriterion("COVERROAD not between", value1, value2, "coverroad");
            return (Criteria) this;
        }

        public Criteria andCoverhotIsNull() {
            addCriterion("COVERHOT is null");
            return (Criteria) this;
        }

        public Criteria andCoverhotIsNotNull() {
            addCriterion("COVERHOT is not null");
            return (Criteria) this;
        }

        public Criteria andCoverhotEqualTo(String value) {
            addCriterion("COVERHOT =", value, "coverhot");
            return (Criteria) this;
        }

        public Criteria andCoverhotNotEqualTo(String value) {
            addCriterion("COVERHOT <>", value, "coverhot");
            return (Criteria) this;
        }

        public Criteria andCoverhotGreaterThan(String value) {
            addCriterion("COVERHOT >", value, "coverhot");
            return (Criteria) this;
        }

        public Criteria andCoverhotGreaterThanOrEqualTo(String value) {
            addCriterion("COVERHOT >=", value, "coverhot");
            return (Criteria) this;
        }

        public Criteria andCoverhotLessThan(String value) {
            addCriterion("COVERHOT <", value, "coverhot");
            return (Criteria) this;
        }

        public Criteria andCoverhotLessThanOrEqualTo(String value) {
            addCriterion("COVERHOT <=", value, "coverhot");
            return (Criteria) this;
        }

        public Criteria andCoverhotLike(String value) {
            addCriterion("COVERHOT like", value, "coverhot");
            return (Criteria) this;
        }

        public Criteria andCoverhotNotLike(String value) {
            addCriterion("COVERHOT not like", value, "coverhot");
            return (Criteria) this;
        }

        public Criteria andCoverhotIn(List<String> values) {
            addCriterion("COVERHOT in", values, "coverhot");
            return (Criteria) this;
        }

        public Criteria andCoverhotNotIn(List<String> values) {
            addCriterion("COVERHOT not in", values, "coverhot");
            return (Criteria) this;
        }

        public Criteria andCoverhotBetween(String value1, String value2) {
            addCriterion("COVERHOT between", value1, value2, "coverhot");
            return (Criteria) this;
        }

        public Criteria andCoverhotNotBetween(String value1, String value2) {
            addCriterion("COVERHOT not between", value1, value2, "coverhot");
            return (Criteria) this;
        }

        public Criteria andRadiiIsNull() {
            addCriterion("RADII is null");
            return (Criteria) this;
        }

        public Criteria andRadiiIsNotNull() {
            addCriterion("RADII is not null");
            return (Criteria) this;
        }

        public Criteria andRadiiEqualTo(String value) {
            addCriterion("RADII =", value, "radii");
            return (Criteria) this;
        }

        public Criteria andRadiiNotEqualTo(String value) {
            addCriterion("RADII <>", value, "radii");
            return (Criteria) this;
        }

        public Criteria andRadiiGreaterThan(String value) {
            addCriterion("RADII >", value, "radii");
            return (Criteria) this;
        }

        public Criteria andRadiiGreaterThanOrEqualTo(String value) {
            addCriterion("RADII >=", value, "radii");
            return (Criteria) this;
        }

        public Criteria andRadiiLessThan(String value) {
            addCriterion("RADII <", value, "radii");
            return (Criteria) this;
        }

        public Criteria andRadiiLessThanOrEqualTo(String value) {
            addCriterion("RADII <=", value, "radii");
            return (Criteria) this;
        }

        public Criteria andRadiiLike(String value) {
            addCriterion("RADII like", value, "radii");
            return (Criteria) this;
        }

        public Criteria andRadiiNotLike(String value) {
            addCriterion("RADII not like", value, "radii");
            return (Criteria) this;
        }

        public Criteria andRadiiIn(List<String> values) {
            addCriterion("RADII in", values, "radii");
            return (Criteria) this;
        }

        public Criteria andRadiiNotIn(List<String> values) {
            addCriterion("RADII not in", values, "radii");
            return (Criteria) this;
        }

        public Criteria andRadiiBetween(String value1, String value2) {
            addCriterion("RADII between", value1, value2, "radii");
            return (Criteria) this;
        }

        public Criteria andRadiiNotBetween(String value1, String value2) {
            addCriterion("RADII not between", value1, value2, "radii");
            return (Criteria) this;
        }

        public Criteria andBoundarycellflagIsNull() {
            addCriterion("BOUNDARYCELLFLAG is null");
            return (Criteria) this;
        }

        public Criteria andBoundarycellflagIsNotNull() {
            addCriterion("BOUNDARYCELLFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andBoundarycellflagEqualTo(String value) {
            addCriterion("BOUNDARYCELLFLAG =", value, "boundarycellflag");
            return (Criteria) this;
        }

        public Criteria andBoundarycellflagNotEqualTo(String value) {
            addCriterion("BOUNDARYCELLFLAG <>", value, "boundarycellflag");
            return (Criteria) this;
        }

        public Criteria andBoundarycellflagGreaterThan(String value) {
            addCriterion("BOUNDARYCELLFLAG >", value, "boundarycellflag");
            return (Criteria) this;
        }

        public Criteria andBoundarycellflagGreaterThanOrEqualTo(String value) {
            addCriterion("BOUNDARYCELLFLAG >=", value, "boundarycellflag");
            return (Criteria) this;
        }

        public Criteria andBoundarycellflagLessThan(String value) {
            addCriterion("BOUNDARYCELLFLAG <", value, "boundarycellflag");
            return (Criteria) this;
        }

        public Criteria andBoundarycellflagLessThanOrEqualTo(String value) {
            addCriterion("BOUNDARYCELLFLAG <=", value, "boundarycellflag");
            return (Criteria) this;
        }

        public Criteria andBoundarycellflagLike(String value) {
            addCriterion("BOUNDARYCELLFLAG like", value, "boundarycellflag");
            return (Criteria) this;
        }

        public Criteria andBoundarycellflagNotLike(String value) {
            addCriterion("BOUNDARYCELLFLAG not like", value, "boundarycellflag");
            return (Criteria) this;
        }

        public Criteria andBoundarycellflagIn(List<String> values) {
            addCriterion("BOUNDARYCELLFLAG in", values, "boundarycellflag");
            return (Criteria) this;
        }

        public Criteria andBoundarycellflagNotIn(List<String> values) {
            addCriterion("BOUNDARYCELLFLAG not in", values, "boundarycellflag");
            return (Criteria) this;
        }

        public Criteria andBoundarycellflagBetween(String value1, String value2) {
            addCriterion("BOUNDARYCELLFLAG between", value1, value2, "boundarycellflag");
            return (Criteria) this;
        }

        public Criteria andBoundarycellflagNotBetween(String value1, String value2) {
            addCriterion("BOUNDARYCELLFLAG not between", value1, value2, "boundarycellflag");
            return (Criteria) this;
        }

        public Criteria andBorderprovinceIsNull() {
            addCriterion("BORDERPROVINCE is null");
            return (Criteria) this;
        }

        public Criteria andBorderprovinceIsNotNull() {
            addCriterion("BORDERPROVINCE is not null");
            return (Criteria) this;
        }

        public Criteria andBorderprovinceEqualTo(String value) {
            addCriterion("BORDERPROVINCE =", value, "borderprovince");
            return (Criteria) this;
        }

        public Criteria andBorderprovinceNotEqualTo(String value) {
            addCriterion("BORDERPROVINCE <>", value, "borderprovince");
            return (Criteria) this;
        }

        public Criteria andBorderprovinceGreaterThan(String value) {
            addCriterion("BORDERPROVINCE >", value, "borderprovince");
            return (Criteria) this;
        }

        public Criteria andBorderprovinceGreaterThanOrEqualTo(String value) {
            addCriterion("BORDERPROVINCE >=", value, "borderprovince");
            return (Criteria) this;
        }

        public Criteria andBorderprovinceLessThan(String value) {
            addCriterion("BORDERPROVINCE <", value, "borderprovince");
            return (Criteria) this;
        }

        public Criteria andBorderprovinceLessThanOrEqualTo(String value) {
            addCriterion("BORDERPROVINCE <=", value, "borderprovince");
            return (Criteria) this;
        }

        public Criteria andBorderprovinceLike(String value) {
            addCriterion("BORDERPROVINCE like", value, "borderprovince");
            return (Criteria) this;
        }

        public Criteria andBorderprovinceNotLike(String value) {
            addCriterion("BORDERPROVINCE not like", value, "borderprovince");
            return (Criteria) this;
        }

        public Criteria andBorderprovinceIn(List<String> values) {
            addCriterion("BORDERPROVINCE in", values, "borderprovince");
            return (Criteria) this;
        }

        public Criteria andBorderprovinceNotIn(List<String> values) {
            addCriterion("BORDERPROVINCE not in", values, "borderprovince");
            return (Criteria) this;
        }

        public Criteria andBorderprovinceBetween(String value1, String value2) {
            addCriterion("BORDERPROVINCE between", value1, value2, "borderprovince");
            return (Criteria) this;
        }

        public Criteria andBorderprovinceNotBetween(String value1, String value2) {
            addCriterion("BORDERPROVINCE not between", value1, value2, "borderprovince");
            return (Criteria) this;
        }

        public Criteria andBordercityIsNull() {
            addCriterion("BORDERCITY is null");
            return (Criteria) this;
        }

        public Criteria andBordercityIsNotNull() {
            addCriterion("BORDERCITY is not null");
            return (Criteria) this;
        }

        public Criteria andBordercityEqualTo(String value) {
            addCriterion("BORDERCITY =", value, "bordercity");
            return (Criteria) this;
        }

        public Criteria andBordercityNotEqualTo(String value) {
            addCriterion("BORDERCITY <>", value, "bordercity");
            return (Criteria) this;
        }

        public Criteria andBordercityGreaterThan(String value) {
            addCriterion("BORDERCITY >", value, "bordercity");
            return (Criteria) this;
        }

        public Criteria andBordercityGreaterThanOrEqualTo(String value) {
            addCriterion("BORDERCITY >=", value, "bordercity");
            return (Criteria) this;
        }

        public Criteria andBordercityLessThan(String value) {
            addCriterion("BORDERCITY <", value, "bordercity");
            return (Criteria) this;
        }

        public Criteria andBordercityLessThanOrEqualTo(String value) {
            addCriterion("BORDERCITY <=", value, "bordercity");
            return (Criteria) this;
        }

        public Criteria andBordercityLike(String value) {
            addCriterion("BORDERCITY like", value, "bordercity");
            return (Criteria) this;
        }

        public Criteria andBordercityNotLike(String value) {
            addCriterion("BORDERCITY not like", value, "bordercity");
            return (Criteria) this;
        }

        public Criteria andBordercityIn(List<String> values) {
            addCriterion("BORDERCITY in", values, "bordercity");
            return (Criteria) this;
        }

        public Criteria andBordercityNotIn(List<String> values) {
            addCriterion("BORDERCITY not in", values, "bordercity");
            return (Criteria) this;
        }

        public Criteria andBordercityBetween(String value1, String value2) {
            addCriterion("BORDERCITY between", value1, value2, "bordercity");
            return (Criteria) this;
        }

        public Criteria andBordercityNotBetween(String value1, String value2) {
            addCriterion("BORDERCITY not between", value1, value2, "bordercity");
            return (Criteria) this;
        }

        public Criteria andFixtextIsNull() {
            addCriterion("FIXTEXT is null");
            return (Criteria) this;
        }

        public Criteria andFixtextIsNotNull() {
            addCriterion("FIXTEXT is not null");
            return (Criteria) this;
        }

        public Criteria andFixtextEqualTo(String value) {
            addCriterion("FIXTEXT =", value, "fixtext");
            return (Criteria) this;
        }

        public Criteria andFixtextNotEqualTo(String value) {
            addCriterion("FIXTEXT <>", value, "fixtext");
            return (Criteria) this;
        }

        public Criteria andFixtextGreaterThan(String value) {
            addCriterion("FIXTEXT >", value, "fixtext");
            return (Criteria) this;
        }

        public Criteria andFixtextGreaterThanOrEqualTo(String value) {
            addCriterion("FIXTEXT >=", value, "fixtext");
            return (Criteria) this;
        }

        public Criteria andFixtextLessThan(String value) {
            addCriterion("FIXTEXT <", value, "fixtext");
            return (Criteria) this;
        }

        public Criteria andFixtextLessThanOrEqualTo(String value) {
            addCriterion("FIXTEXT <=", value, "fixtext");
            return (Criteria) this;
        }

        public Criteria andFixtextLike(String value) {
            addCriterion("FIXTEXT like", value, "fixtext");
            return (Criteria) this;
        }

        public Criteria andFixtextNotLike(String value) {
            addCriterion("FIXTEXT not like", value, "fixtext");
            return (Criteria) this;
        }

        public Criteria andFixtextIn(List<String> values) {
            addCriterion("FIXTEXT in", values, "fixtext");
            return (Criteria) this;
        }

        public Criteria andFixtextNotIn(List<String> values) {
            addCriterion("FIXTEXT not in", values, "fixtext");
            return (Criteria) this;
        }

        public Criteria andFixtextBetween(String value1, String value2) {
            addCriterion("FIXTEXT between", value1, value2, "fixtext");
            return (Criteria) this;
        }

        public Criteria andFixtextNotBetween(String value1, String value2) {
            addCriterion("FIXTEXT not between", value1, value2, "fixtext");
            return (Criteria) this;
        }

        public Criteria andMarIsNull() {
            addCriterion("MAR is null");
            return (Criteria) this;
        }

        public Criteria andMarIsNotNull() {
            addCriterion("MAR is not null");
            return (Criteria) this;
        }

        public Criteria andMarEqualTo(BigDecimal value) {
            addCriterion("MAR =", value, "mar");
            return (Criteria) this;
        }

        public Criteria andMarNotEqualTo(BigDecimal value) {
            addCriterion("MAR <>", value, "mar");
            return (Criteria) this;
        }

        public Criteria andMarGreaterThan(BigDecimal value) {
            addCriterion("MAR >", value, "mar");
            return (Criteria) this;
        }

        public Criteria andMarGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MAR >=", value, "mar");
            return (Criteria) this;
        }

        public Criteria andMarLessThan(BigDecimal value) {
            addCriterion("MAR <", value, "mar");
            return (Criteria) this;
        }

        public Criteria andMarLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MAR <=", value, "mar");
            return (Criteria) this;
        }

        public Criteria andMarIn(List<BigDecimal> values) {
            addCriterion("MAR in", values, "mar");
            return (Criteria) this;
        }

        public Criteria andMarNotIn(List<BigDecimal> values) {
            addCriterion("MAR not in", values, "mar");
            return (Criteria) this;
        }

        public Criteria andMarBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MAR between", value1, value2, "mar");
            return (Criteria) this;
        }

        public Criteria andMarNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MAR not between", value1, value2, "mar");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("UPDATETIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("UPDATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATETIME =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATETIME <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterionForJDBCDate("UPDATETIME >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATETIME >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterionForJDBCDate("UPDATETIME <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UPDATETIME <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATETIME in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("UPDATETIME not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATETIME between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UPDATETIME not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIsNull() {
            addCriterion("UPDATEUSER is null");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIsNotNull() {
            addCriterion("UPDATEUSER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateuserEqualTo(BigDecimal value) {
            addCriterion("UPDATEUSER =", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotEqualTo(BigDecimal value) {
            addCriterion("UPDATEUSER <>", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserGreaterThan(BigDecimal value) {
            addCriterion("UPDATEUSER >", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("UPDATEUSER >=", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLessThan(BigDecimal value) {
            addCriterion("UPDATEUSER <", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserLessThanOrEqualTo(BigDecimal value) {
            addCriterion("UPDATEUSER <=", value, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserIn(List<BigDecimal> values) {
            addCriterion("UPDATEUSER in", values, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotIn(List<BigDecimal> values) {
            addCriterion("UPDATEUSER not in", values, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UPDATEUSER between", value1, value2, "updateuser");
            return (Criteria) this;
        }

        public Criteria andUpdateuserNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UPDATEUSER not between", value1, value2, "updateuser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WY_CELL_MANUAL
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 10 12:45:03 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table WY_CELL_MANUAL
     *
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}