package com.scttsc.business.model;

import com.scttsc.baselibs.model.*;

import java.util.Date;
import java.util.List;

public class CellManual extends Entity {

    private String intId;
    private String name;
    private String bscName;
    private Integer ci;
    private String gfflag;
    private Integer gfnum;
    private String celltype;
    private Integer indoornum;
    private String borderflag;
    private Integer dofrqnum;
    private Integer dopn;
    private Integer feederlength;  //馈线长度
    private String coverarea;
    private String coverroad;
    private String coverhot;
    private Double radii;//小区半径
    private String boundarycellflag;
    private String borderprovince;
    private String bordercity;
    private Double fixtext;
    private Integer mar;
    private String remark;
    private Date updatetime;
    private Long updateuser;


    List<CellAirLib> airLibs;//小区天线列表

    private String countryLib;//覆盖农村、乡镇库集合
    private String roadLib;//覆盖道路、隧道
    private String hotLib;//覆盖热点

    List<VitoLib> vitoLibs;//覆盖农村库
    List<RoadLib> roadLibs;//覆盖道路库
    List<TunnelLib> tunnelLibs;//覆盖隧道库
    List<SchoolLib> schoolLibs;//覆盖校园库
    List<SecneryLib> secneryLibs;//覆盖风景库


    @Override
    public void setIgFields() {
        this.igFields.add("name");
        this.igFields.add("bscName");
        this.igFields.add("ci");
        this.igFields.add("gfflag");
        this.igFields.add("gfnum");
        this.igFields.add("celltype");
        this.igFields.add("dofrqnum");
        this.igFields.add("dopn");
        this.igFields.add("radii");
        this.igFields.add("fixtext");
        this.igFields.add("mar");
        this.igFields.add("updatetime");
        this.igFields.add("airLibs");
        this.igFields.add("countryLib");
        this.igFields.add("roadLib");
        this.igFields.add("hotLib");
        this.igFields.add("vitoLibs");
        this.igFields.add("roadLibs");
        this.igFields.add("tunnelLibs");
        this.igFields.add("schoolLibs");
        this.igFields.add("secneryLibs");
    }

    public String compareEntity(Object object) {
        return super.compareEntity(object);
    }

    public String getIntId() {
        return intId;
    }

    public void setIntId(String intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_MANUAL.NAME
     *
     * @return the value of WY_CELL_MANUAL.NAME
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_MANUAL.NAME
     *
     * @param name the value for WY_CELL_MANUAL.NAME
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_MANUAL.BSC_NAME
     *
     * @return the value of WY_CELL_MANUAL.BSC_NAME
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public String getBscName() {
        return bscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_MANUAL.BSC_NAME
     *
     * @param bscName the value for WY_CELL_MANUAL.BSC_NAME
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setBscName(String bscName) {
        this.bscName = bscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_MANUAL.CI
     *
     * @return the value of WY_CELL_MANUAL.CI
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public Integer getCi() {
        return ci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_MANUAL.CI
     *
     * @param ci the value for WY_CELL_MANUAL.CI
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setCi(Integer ci) {
        this.ci = ci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_MANUAL.GFFLAG
     *
     * @return the value of WY_CELL_MANUAL.GFFLAG
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public String getGfflag() {
        return gfflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_MANUAL.GFFLAG
     *
     * @param gfflag the value for WY_CELL_MANUAL.GFFLAG
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setGfflag(String gfflag) {
        this.gfflag = gfflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_MANUAL.GFNUM
     *
     * @return the value of WY_CELL_MANUAL.GFNUM
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public Integer getGfnum() {
        return gfnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_MANUAL.GFNUM
     *
     * @param gfnum the value for WY_CELL_MANUAL.GFNUM
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setGfnum(Integer gfnum) {
        this.gfnum = gfnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_MANUAL.CELLTYPE
     *
     * @return the value of WY_CELL_MANUAL.CELLTYPE
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public String getCelltype() {
        return celltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_MANUAL.CELLTYPE
     *
     * @param celltype the value for WY_CELL_MANUAL.CELLTYPE
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setCelltype(String celltype) {
        this.celltype = celltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_MANUAL.INDOORNUM
     *
     * @return the value of WY_CELL_MANUAL.INDOORNUM
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public Integer getIndoornum() {
        return indoornum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_MANUAL.INDOORNUM
     *
     * @param indoornum the value for WY_CELL_MANUAL.INDOORNUM
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setIndoornum(Integer indoornum) {
        this.indoornum = indoornum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_MANUAL.BORDERFLAG
     *
     * @return the value of WY_CELL_MANUAL.BORDERFLAG
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public String getBorderflag() {
        return borderflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_MANUAL.BORDERFLAG
     *
     * @param borderflag the value for WY_CELL_MANUAL.BORDERFLAG
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setBorderflag(String borderflag) {
        this.borderflag = borderflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_MANUAL.DOFRQNUM
     *
     * @return the value of WY_CELL_MANUAL.DOFRQNUM
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public Integer getDofrqnum() {
        return dofrqnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_MANUAL.DOFRQNUM
     *
     * @param dofrqnum the value for WY_CELL_MANUAL.DOFRQNUM
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setDofrqnum(Integer dofrqnum) {
        this.dofrqnum = dofrqnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_MANUAL.DOPN
     *
     * @return the value of WY_CELL_MANUAL.DOPN
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public Integer getDopn() {
        return dopn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_MANUAL.DOPN
     *
     * @param dopn the value for WY_CELL_MANUAL.DOPN
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setDopn(Integer dopn) {
        this.dopn = dopn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_MANUAL.FEEDERLENGTH
     *
     * @return the value of WY_CELL_MANUAL.FEEDERLENGTH
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public Integer getFeederlength() {
        return feederlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_MANUAL.FEEDERLENGTH
     *
     * @param feederlength the value for WY_CELL_MANUAL.FEEDERLENGTH
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setFeederlength(Integer feederlength) {
        this.feederlength = feederlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_MANUAL.COVERAREA
     *
     * @return the value of WY_CELL_MANUAL.COVERAREA
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public String getCoverarea() {
        return coverarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_MANUAL.COVERAREA
     *
     * @param coverarea the value for WY_CELL_MANUAL.COVERAREA
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setCoverarea(String coverarea) {
        this.coverarea = coverarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_MANUAL.COVERROAD
     *
     * @return the value of WY_CELL_MANUAL.COVERROAD
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public String getCoverroad() {
        return coverroad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_MANUAL.COVERROAD
     *
     * @param coverroad the value for WY_CELL_MANUAL.COVERROAD
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setCoverroad(String coverroad) {
        this.coverroad = coverroad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_MANUAL.COVERHOT
     *
     * @return the value of WY_CELL_MANUAL.COVERHOT
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public String getCoverhot() {
        return coverhot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_MANUAL.COVERHOT
     *
     * @param coverhot the value for WY_CELL_MANUAL.COVERHOT
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setCoverhot(String coverhot) {
        this.coverhot = coverhot;
    }


    public Double getRadii() {
        return radii;
    }

    public void setRadii(Double radii) {
        this.radii = radii;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_MANUAL.BOUNDARYCELLFLAG
     *
     * @return the value of WY_CELL_MANUAL.BOUNDARYCELLFLAG
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public String getBoundarycellflag() {
        return boundarycellflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_MANUAL.BOUNDARYCELLFLAG
     *
     * @param boundarycellflag the value for WY_CELL_MANUAL.BOUNDARYCELLFLAG
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setBoundarycellflag(String boundarycellflag) {
        this.boundarycellflag = boundarycellflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_MANUAL.BORDERPROVINCE
     *
     * @return the value of WY_CELL_MANUAL.BORDERPROVINCE
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public String getBorderprovince() {
        return borderprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_MANUAL.BORDERPROVINCE
     *
     * @param borderprovince the value for WY_CELL_MANUAL.BORDERPROVINCE
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setBorderprovince(String borderprovince) {
        this.borderprovince = borderprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_MANUAL.BORDERCITY
     *
     * @return the value of WY_CELL_MANUAL.BORDERCITY
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public String getBordercity() {
        return bordercity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_MANUAL.BORDERCITY
     *
     * @param bordercity the value for WY_CELL_MANUAL.BORDERCITY
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setBordercity(String bordercity) {
        this.bordercity = bordercity;
    }


    public Double getFixtext() {
        return fixtext;
    }

    public void setFixtext(Double fixtext) {
        this.fixtext = fixtext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_MANUAL.MAR
     *
     * @return the value of WY_CELL_MANUAL.MAR
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public Integer getMar() {
        return mar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_MANUAL.MAR
     *
     * @param mar the value for WY_CELL_MANUAL.MAR
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setMar(Integer mar) {
        this.mar = mar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_MANUAL.REMARK
     *
     * @return the value of WY_CELL_MANUAL.REMARK
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_MANUAL.REMARK
     *
     * @param remark the value for WY_CELL_MANUAL.REMARK
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_MANUAL.UPDATETIME
     *
     * @return the value of WY_CELL_MANUAL.UPDATETIME
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_MANUAL.UPDATETIME
     *
     * @param updatetime the value for WY_CELL_MANUAL.UPDATETIME
     * @mbggenerated Wed Apr 10 12:45:03 CST 2013
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    public Long getUpdateuser() {
        return updateuser;
    }

    public void setUpdateuser(Long updateuser) {
        this.updateuser = updateuser;
    }

    public List<CellAirLib> getAirLibs() {
        return airLibs;
    }

    public void setAirLibs(List<CellAirLib> airLibs) {
        this.airLibs = airLibs;
    }

    public String getCountryLib() {
        return countryLib;
    }

    public void setCountryLib(String countryLib) {
        this.countryLib = countryLib;
    }

    public String getRoadLib() {
        return roadLib;
    }

    public void setRoadLib(String roadLib) {
        this.roadLib = roadLib;
    }

    public String getHotLib() {
        return hotLib;
    }

    public void setHotLib(String hotLib) {
        this.hotLib = hotLib;
    }


    public List<VitoLib> getVitoLibs() {
        return vitoLibs;
    }

    public void setVitoLibs(List<VitoLib> vitoLibs) {
        this.vitoLibs = vitoLibs;
    }

    public List<RoadLib> getRoadLibs() {
        return roadLibs;
    }

    public void setRoadLibs(List<RoadLib> roadLibs) {
        this.roadLibs = roadLibs;
    }

    public List<TunnelLib> getTunnelLibs() {
        return tunnelLibs;
    }

    public void setTunnelLibs(List<TunnelLib> tunnelLibs) {
        this.tunnelLibs = tunnelLibs;
    }

    public List<SchoolLib> getSchoolLibs() {
        return schoolLibs;
    }

    public void setSchoolLibs(List<SchoolLib> schoolLibs) {
        this.schoolLibs = schoolLibs;
    }

    public List<SecneryLib> getSecneryLibs() {
        return secneryLibs;
    }

    public void setSecneryLibs(List<SecneryLib> secneryLibs) {
        this.secneryLibs = secneryLibs;
    }
}