package com.scttsc.business.model;


public class CellLib {

    private String cellIntId;
    private Integer libId;
    private Integer libType;

   
    public String getCellIntId() {
		return cellIntId;
	}

	public void setCellIntId(String cellIntId) {
		this.cellIntId = cellIntId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_LIB.LIB_ID
     *
     * @return the value of WY_CELL_LIB.LIB_ID
     *
     * @mbggenerated Wed Apr 10 12:45:31 CST 2013
     */
    public Integer getLibId() {
        return libId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_LIB.LIB_ID
     *
     * @param libId the value for WY_CELL_LIB.LIB_ID
     *
     * @mbggenerated Wed Apr 10 12:45:31 CST 2013
     */
    public void setLibId(Integer libId) {
        this.libId = libId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_CELL_LIB.LIB_TYPE
     *
     * @return the value of WY_CELL_LIB.LIB_TYPE
     *
     * @mbggenerated Wed Apr 10 12:45:31 CST 2013
     */
    public Integer getLibType() {
        return libType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_CELL_LIB.LIB_TYPE
     *
     * @param libType the value for WY_CELL_LIB.LIB_TYPE
     *
     * @mbggenerated Wed Apr 10 12:45:31 CST 2013
     */
    public void setLibType(Integer libType) {
        this.libType = libType;
    }
}