package com.scttsc.business.model;

import java.math.BigDecimal;

public class ColumnsConfig {

    private BigDecimal id;
    private String cnName;
    private String enName;
    private BigDecimal type;
    private Integer orderno;
    private String remark;
    private Integer enable;
    private Integer enedit;
    private Integer comBoBox;


    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_COLUMNS_CONFIG.ID
     *
     * @param id the value for WY_COLUMNS_CONFIG.ID
     * @mbggenerated Mon Apr 22 19:30:22 CST 2013
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_COLUMNS_CONFIG.CN_NAME
     *
     * @return the value of WY_COLUMNS_CONFIG.CN_NAME
     * @mbggenerated Mon Apr 22 19:30:22 CST 2013
     */
    public String getCnName() {
        return cnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_COLUMNS_CONFIG.CN_NAME
     *
     * @param cnName the value for WY_COLUMNS_CONFIG.CN_NAME
     * @mbggenerated Mon Apr 22 19:30:22 CST 2013
     */
    public void setCnName(String cnName) {
        this.cnName = cnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_COLUMNS_CONFIG.EN_NAME
     *
     * @return the value of WY_COLUMNS_CONFIG.EN_NAME
     * @mbggenerated Mon Apr 22 19:30:22 CST 2013
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_COLUMNS_CONFIG.EN_NAME
     *
     * @param enName the value for WY_COLUMNS_CONFIG.EN_NAME
     * @mbggenerated Mon Apr 22 19:30:22 CST 2013
     */
    public void setEnName(String enName) {
        this.enName = enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_COLUMNS_CONFIG.TYPE
     *
     * @return the value of WY_COLUMNS_CONFIG.TYPE
     * @mbggenerated Mon Apr 22 19:30:22 CST 2013
     */
    public BigDecimal getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_COLUMNS_CONFIG.TYPE
     *
     * @param type the value for WY_COLUMNS_CONFIG.TYPE
     * @mbggenerated Mon Apr 22 19:30:22 CST 2013
     */
    public void setType(BigDecimal type) {
        this.type = type;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Integer getEnable() {
        return enable;
    }

    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    public Integer getEnedit() {
        return enedit;
    }

    public void setEnedit(Integer enedit) {
        this.enedit = enedit;
    }

    public Integer getOrderno() {
        return orderno;
    }

    public void setOrderno(Integer orderno) {
        this.orderno = orderno;
    }

    public Integer getComBoBox() {
        return comBoBox;
    }

    public void setComBoBox(Integer comBoBox) {
        this.comBoBox = comBoBox;
    }
}