package com.scttsc.business.model;

import java.math.BigDecimal;
import java.util.Date;

public class CparCell {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.INT_ID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private String intId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.OBJECT_RDN
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private String objectRdn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.OMC_ID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal omcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.NAME
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.RELATED_BSC
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal relatedBsc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.BSC_NAME
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private String bscName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.TIME_STAMP
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private Date timeStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.CONFIRMED
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal confirmed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SYSTEM
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal system;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.CELLID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal cellid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.NID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal nid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.REG_ZONE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal regZone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.TOTAL_ZONES
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal totalZones;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.ZONE_TIMER
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal zoneTimer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.PACKET_ZONE_ID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal packetZoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.P_REV
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal pRev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.ENCRYPT_MODE_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal encryptModeA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.ENC_SUPPORTED_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal encSupportedA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SIG_ENCRYPT_SUP_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal sigEncryptSupA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.AUTH_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal authA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.MAX_NUM_ALT_SO_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal maxNumAltSoA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.USE_SYNC_ID_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal useSyncIdA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.MS_IPL_SUP_IND_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal msIplSupIndA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.MOB_QOS_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal mobQosA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.HOME_REG
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal homeReg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.FOR_SID_REG
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal forSidReg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.FOR_NID_REG
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal forNidReg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.POWER_UP_REG
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal powerUpReg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.POWER_DOWN_REG
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal powerDownReg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.PARAMETER_REG
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal parameterReg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.REG_PRD
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal regPrd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.REG_DIST
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal regDist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.PREF_MSID_TYPE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal prefMsidType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.MCC
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal mcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.IMSI_11_12
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal imsi1112;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.IMSI_T_SUPPORTED
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal imsiTSupported;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.PILOT_REPORT_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal pilotReportA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SDB_SUPPORTED
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal sdbSupported;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.PILOTPN
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal pilotpn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SECTORID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private String sectorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SUBNETMASK
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal subnetmask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.COLORCODE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal colorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.ACCESSRESTRICTEN
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal accessrestricten;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.ACCESSDISTANCE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal accessdistance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.ACCESSSIGNATURE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal accesssignature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.LATITUDE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.LONGITUDE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.ROUTEUPDATERADIUS
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal routeupdateradius;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.MAXIMUMREVISION
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal maximumrevision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.MINIMUMREVISION
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal minimumrevision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.LEAPSECONDS
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal leapseconds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.LOCALTIMEOFFSET
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal localtimeoffset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.CRKEEPTHRESHOLD
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal crkeepthreshold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.LOADBALANCETHRESH
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal loadbalancethresh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.STATUS
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SECTORSIGNATURE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal sectorsignature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.LONGLATLOCK_B
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal longlatlockB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.ANID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal anid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.CI
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal ci;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SUBNETADDRESS_B
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private String subnetaddressB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.BANDCLASS
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal bandclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.ALIAS_B
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private String aliasB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SWITCH1
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal switch1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SWITCH2
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal switch2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SWITCH3
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal switch3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SWITCH4
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal switch4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SWITCH5
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal switch5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SWITCH6
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal switch6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SWITCH7
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal switch7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SWITCH8
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal switch8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SWITCH9
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal switch9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SWITCH10
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal switch10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SUBNETINDEXID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal subnetindexid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.PHYCELLID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal phycellid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SCENETYPE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal scenetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.ISSAMEPNSECTOR
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal issamepnsector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.REFCELLID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal refcellid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SAMEPNCELLMAXNUM
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal samepncellmaxnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SOFTERHOGROUPID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal softerhogroupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.BTS_ALIAS
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private String btsAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.ISSECTORMCCAPABLE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal issectormccapable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.LATITUDE_B
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private Double latitudeB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.LONGTITUDE_B
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private Double longtitudeB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SECCOLORCODE1
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal seccolorcode1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SECCOLORCODE2
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal seccolorcode2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SECCOLORCODE3
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal seccolorcode3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SECCOLORCODE4
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal seccolorcode4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SECCOLORCODE5
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal seccolorcode5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SECCOLORCODE6
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal seccolorcode6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.SECCOLORCODE7
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal seccolorcode7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.MAINCONNQOSENABLED
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal mainconnqosenabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.FPC_MODE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal fpcMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.FPC_PTTSCH_FER
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal fpcPttschFer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.FPC_PTTSCH_INI_SPT
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal fpcPttschIniSpt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column C_TZX_PAR_CELL_DO.AN_ID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    private BigDecimal anId;

   
    
    
    

    public String getIntId() {
		return intId;
	}

	public void setIntId(String intId) {
		this.intId = intId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.OBJECT_RDN
     *
     * @return the value of C_TZX_PAR_CELL_DO.OBJECT_RDN
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public String getObjectRdn() {
        return objectRdn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.OBJECT_RDN
     *
     * @param objectRdn the value for C_TZX_PAR_CELL_DO.OBJECT_RDN
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setObjectRdn(String objectRdn) {
        this.objectRdn = objectRdn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.OMC_ID
     *
     * @return the value of C_TZX_PAR_CELL_DO.OMC_ID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getOmcId() {
        return omcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.OMC_ID
     *
     * @param omcId the value for C_TZX_PAR_CELL_DO.OMC_ID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setOmcId(BigDecimal omcId) {
        this.omcId = omcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.NAME
     *
     * @return the value of C_TZX_PAR_CELL_DO.NAME
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.NAME
     *
     * @param name the value for C_TZX_PAR_CELL_DO.NAME
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.RELATED_BSC
     *
     * @return the value of C_TZX_PAR_CELL_DO.RELATED_BSC
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getRelatedBsc() {
        return relatedBsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.RELATED_BSC
     *
     * @param relatedBsc the value for C_TZX_PAR_CELL_DO.RELATED_BSC
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setRelatedBsc(BigDecimal relatedBsc) {
        this.relatedBsc = relatedBsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.BSC_NAME
     *
     * @return the value of C_TZX_PAR_CELL_DO.BSC_NAME
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public String getBscName() {
        return bscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.BSC_NAME
     *
     * @param bscName the value for C_TZX_PAR_CELL_DO.BSC_NAME
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setBscName(String bscName) {
        this.bscName = bscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.TIME_STAMP
     *
     * @return the value of C_TZX_PAR_CELL_DO.TIME_STAMP
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.TIME_STAMP
     *
     * @param timeStamp the value for C_TZX_PAR_CELL_DO.TIME_STAMP
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.CONFIRMED
     *
     * @return the value of C_TZX_PAR_CELL_DO.CONFIRMED
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getConfirmed() {
        return confirmed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.CONFIRMED
     *
     * @param confirmed the value for C_TZX_PAR_CELL_DO.CONFIRMED
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setConfirmed(BigDecimal confirmed) {
        this.confirmed = confirmed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SYSTEM
     *
     * @return the value of C_TZX_PAR_CELL_DO.SYSTEM
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSystem() {
        return system;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SYSTEM
     *
     * @param system the value for C_TZX_PAR_CELL_DO.SYSTEM
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSystem(BigDecimal system) {
        this.system = system;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.CELLID
     *
     * @return the value of C_TZX_PAR_CELL_DO.CELLID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getCellid() {
        return cellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.CELLID
     *
     * @param cellid the value for C_TZX_PAR_CELL_DO.CELLID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setCellid(BigDecimal cellid) {
        this.cellid = cellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SID
     *
     * @return the value of C_TZX_PAR_CELL_DO.SID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SID
     *
     * @param sid the value for C_TZX_PAR_CELL_DO.SID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSid(BigDecimal sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.NID
     *
     * @return the value of C_TZX_PAR_CELL_DO.NID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getNid() {
        return nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.NID
     *
     * @param nid the value for C_TZX_PAR_CELL_DO.NID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setNid(BigDecimal nid) {
        this.nid = nid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.REG_ZONE
     *
     * @return the value of C_TZX_PAR_CELL_DO.REG_ZONE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getRegZone() {
        return regZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.REG_ZONE
     *
     * @param regZone the value for C_TZX_PAR_CELL_DO.REG_ZONE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setRegZone(BigDecimal regZone) {
        this.regZone = regZone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.TOTAL_ZONES
     *
     * @return the value of C_TZX_PAR_CELL_DO.TOTAL_ZONES
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getTotalZones() {
        return totalZones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.TOTAL_ZONES
     *
     * @param totalZones the value for C_TZX_PAR_CELL_DO.TOTAL_ZONES
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setTotalZones(BigDecimal totalZones) {
        this.totalZones = totalZones;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.ZONE_TIMER
     *
     * @return the value of C_TZX_PAR_CELL_DO.ZONE_TIMER
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getZoneTimer() {
        return zoneTimer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.ZONE_TIMER
     *
     * @param zoneTimer the value for C_TZX_PAR_CELL_DO.ZONE_TIMER
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setZoneTimer(BigDecimal zoneTimer) {
        this.zoneTimer = zoneTimer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.PACKET_ZONE_ID
     *
     * @return the value of C_TZX_PAR_CELL_DO.PACKET_ZONE_ID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getPacketZoneId() {
        return packetZoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.PACKET_ZONE_ID
     *
     * @param packetZoneId the value for C_TZX_PAR_CELL_DO.PACKET_ZONE_ID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setPacketZoneId(BigDecimal packetZoneId) {
        this.packetZoneId = packetZoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.P_REV
     *
     * @return the value of C_TZX_PAR_CELL_DO.P_REV
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getpRev() {
        return pRev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.P_REV
     *
     * @param pRev the value for C_TZX_PAR_CELL_DO.P_REV
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setpRev(BigDecimal pRev) {
        this.pRev = pRev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.ENCRYPT_MODE_A
     *
     * @return the value of C_TZX_PAR_CELL_DO.ENCRYPT_MODE_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getEncryptModeA() {
        return encryptModeA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.ENCRYPT_MODE_A
     *
     * @param encryptModeA the value for C_TZX_PAR_CELL_DO.ENCRYPT_MODE_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setEncryptModeA(BigDecimal encryptModeA) {
        this.encryptModeA = encryptModeA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.ENC_SUPPORTED_A
     *
     * @return the value of C_TZX_PAR_CELL_DO.ENC_SUPPORTED_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getEncSupportedA() {
        return encSupportedA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.ENC_SUPPORTED_A
     *
     * @param encSupportedA the value for C_TZX_PAR_CELL_DO.ENC_SUPPORTED_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setEncSupportedA(BigDecimal encSupportedA) {
        this.encSupportedA = encSupportedA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SIG_ENCRYPT_SUP_A
     *
     * @return the value of C_TZX_PAR_CELL_DO.SIG_ENCRYPT_SUP_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSigEncryptSupA() {
        return sigEncryptSupA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SIG_ENCRYPT_SUP_A
     *
     * @param sigEncryptSupA the value for C_TZX_PAR_CELL_DO.SIG_ENCRYPT_SUP_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSigEncryptSupA(BigDecimal sigEncryptSupA) {
        this.sigEncryptSupA = sigEncryptSupA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.AUTH_A
     *
     * @return the value of C_TZX_PAR_CELL_DO.AUTH_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getAuthA() {
        return authA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.AUTH_A
     *
     * @param authA the value for C_TZX_PAR_CELL_DO.AUTH_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setAuthA(BigDecimal authA) {
        this.authA = authA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.MAX_NUM_ALT_SO_A
     *
     * @return the value of C_TZX_PAR_CELL_DO.MAX_NUM_ALT_SO_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getMaxNumAltSoA() {
        return maxNumAltSoA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.MAX_NUM_ALT_SO_A
     *
     * @param maxNumAltSoA the value for C_TZX_PAR_CELL_DO.MAX_NUM_ALT_SO_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setMaxNumAltSoA(BigDecimal maxNumAltSoA) {
        this.maxNumAltSoA = maxNumAltSoA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.USE_SYNC_ID_A
     *
     * @return the value of C_TZX_PAR_CELL_DO.USE_SYNC_ID_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getUseSyncIdA() {
        return useSyncIdA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.USE_SYNC_ID_A
     *
     * @param useSyncIdA the value for C_TZX_PAR_CELL_DO.USE_SYNC_ID_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setUseSyncIdA(BigDecimal useSyncIdA) {
        this.useSyncIdA = useSyncIdA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.MS_IPL_SUP_IND_A
     *
     * @return the value of C_TZX_PAR_CELL_DO.MS_IPL_SUP_IND_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getMsIplSupIndA() {
        return msIplSupIndA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.MS_IPL_SUP_IND_A
     *
     * @param msIplSupIndA the value for C_TZX_PAR_CELL_DO.MS_IPL_SUP_IND_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setMsIplSupIndA(BigDecimal msIplSupIndA) {
        this.msIplSupIndA = msIplSupIndA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.MOB_QOS_A
     *
     * @return the value of C_TZX_PAR_CELL_DO.MOB_QOS_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getMobQosA() {
        return mobQosA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.MOB_QOS_A
     *
     * @param mobQosA the value for C_TZX_PAR_CELL_DO.MOB_QOS_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setMobQosA(BigDecimal mobQosA) {
        this.mobQosA = mobQosA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.HOME_REG
     *
     * @return the value of C_TZX_PAR_CELL_DO.HOME_REG
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getHomeReg() {
        return homeReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.HOME_REG
     *
     * @param homeReg the value for C_TZX_PAR_CELL_DO.HOME_REG
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setHomeReg(BigDecimal homeReg) {
        this.homeReg = homeReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.FOR_SID_REG
     *
     * @return the value of C_TZX_PAR_CELL_DO.FOR_SID_REG
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getForSidReg() {
        return forSidReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.FOR_SID_REG
     *
     * @param forSidReg the value for C_TZX_PAR_CELL_DO.FOR_SID_REG
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setForSidReg(BigDecimal forSidReg) {
        this.forSidReg = forSidReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.FOR_NID_REG
     *
     * @return the value of C_TZX_PAR_CELL_DO.FOR_NID_REG
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getForNidReg() {
        return forNidReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.FOR_NID_REG
     *
     * @param forNidReg the value for C_TZX_PAR_CELL_DO.FOR_NID_REG
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setForNidReg(BigDecimal forNidReg) {
        this.forNidReg = forNidReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.POWER_UP_REG
     *
     * @return the value of C_TZX_PAR_CELL_DO.POWER_UP_REG
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getPowerUpReg() {
        return powerUpReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.POWER_UP_REG
     *
     * @param powerUpReg the value for C_TZX_PAR_CELL_DO.POWER_UP_REG
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setPowerUpReg(BigDecimal powerUpReg) {
        this.powerUpReg = powerUpReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.POWER_DOWN_REG
     *
     * @return the value of C_TZX_PAR_CELL_DO.POWER_DOWN_REG
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getPowerDownReg() {
        return powerDownReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.POWER_DOWN_REG
     *
     * @param powerDownReg the value for C_TZX_PAR_CELL_DO.POWER_DOWN_REG
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setPowerDownReg(BigDecimal powerDownReg) {
        this.powerDownReg = powerDownReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.PARAMETER_REG
     *
     * @return the value of C_TZX_PAR_CELL_DO.PARAMETER_REG
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getParameterReg() {
        return parameterReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.PARAMETER_REG
     *
     * @param parameterReg the value for C_TZX_PAR_CELL_DO.PARAMETER_REG
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setParameterReg(BigDecimal parameterReg) {
        this.parameterReg = parameterReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.REG_PRD
     *
     * @return the value of C_TZX_PAR_CELL_DO.REG_PRD
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getRegPrd() {
        return regPrd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.REG_PRD
     *
     * @param regPrd the value for C_TZX_PAR_CELL_DO.REG_PRD
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setRegPrd(BigDecimal regPrd) {
        this.regPrd = regPrd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.REG_DIST
     *
     * @return the value of C_TZX_PAR_CELL_DO.REG_DIST
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getRegDist() {
        return regDist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.REG_DIST
     *
     * @param regDist the value for C_TZX_PAR_CELL_DO.REG_DIST
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setRegDist(BigDecimal regDist) {
        this.regDist = regDist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.PREF_MSID_TYPE
     *
     * @return the value of C_TZX_PAR_CELL_DO.PREF_MSID_TYPE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getPrefMsidType() {
        return prefMsidType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.PREF_MSID_TYPE
     *
     * @param prefMsidType the value for C_TZX_PAR_CELL_DO.PREF_MSID_TYPE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setPrefMsidType(BigDecimal prefMsidType) {
        this.prefMsidType = prefMsidType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.MCC
     *
     * @return the value of C_TZX_PAR_CELL_DO.MCC
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getMcc() {
        return mcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.MCC
     *
     * @param mcc the value for C_TZX_PAR_CELL_DO.MCC
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setMcc(BigDecimal mcc) {
        this.mcc = mcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.IMSI_11_12
     *
     * @return the value of C_TZX_PAR_CELL_DO.IMSI_11_12
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getImsi1112() {
        return imsi1112;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.IMSI_11_12
     *
     * @param imsi1112 the value for C_TZX_PAR_CELL_DO.IMSI_11_12
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setImsi1112(BigDecimal imsi1112) {
        this.imsi1112 = imsi1112;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.IMSI_T_SUPPORTED
     *
     * @return the value of C_TZX_PAR_CELL_DO.IMSI_T_SUPPORTED
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getImsiTSupported() {
        return imsiTSupported;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.IMSI_T_SUPPORTED
     *
     * @param imsiTSupported the value for C_TZX_PAR_CELL_DO.IMSI_T_SUPPORTED
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setImsiTSupported(BigDecimal imsiTSupported) {
        this.imsiTSupported = imsiTSupported;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.PILOT_REPORT_A
     *
     * @return the value of C_TZX_PAR_CELL_DO.PILOT_REPORT_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getPilotReportA() {
        return pilotReportA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.PILOT_REPORT_A
     *
     * @param pilotReportA the value for C_TZX_PAR_CELL_DO.PILOT_REPORT_A
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setPilotReportA(BigDecimal pilotReportA) {
        this.pilotReportA = pilotReportA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SDB_SUPPORTED
     *
     * @return the value of C_TZX_PAR_CELL_DO.SDB_SUPPORTED
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSdbSupported() {
        return sdbSupported;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SDB_SUPPORTED
     *
     * @param sdbSupported the value for C_TZX_PAR_CELL_DO.SDB_SUPPORTED
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSdbSupported(BigDecimal sdbSupported) {
        this.sdbSupported = sdbSupported;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.PILOTPN
     *
     * @return the value of C_TZX_PAR_CELL_DO.PILOTPN
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getPilotpn() {
        return pilotpn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.PILOTPN
     *
     * @param pilotpn the value for C_TZX_PAR_CELL_DO.PILOTPN
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setPilotpn(BigDecimal pilotpn) {
        this.pilotpn = pilotpn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SECTORID
     *
     * @return the value of C_TZX_PAR_CELL_DO.SECTORID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public String getSectorid() {
        return sectorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SECTORID
     *
     * @param sectorid the value for C_TZX_PAR_CELL_DO.SECTORID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSectorid(String sectorid) {
        this.sectorid = sectorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SUBNETMASK
     *
     * @return the value of C_TZX_PAR_CELL_DO.SUBNETMASK
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSubnetmask() {
        return subnetmask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SUBNETMASK
     *
     * @param subnetmask the value for C_TZX_PAR_CELL_DO.SUBNETMASK
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSubnetmask(BigDecimal subnetmask) {
        this.subnetmask = subnetmask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.COLORCODE
     *
     * @return the value of C_TZX_PAR_CELL_DO.COLORCODE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getColorcode() {
        return colorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.COLORCODE
     *
     * @param colorcode the value for C_TZX_PAR_CELL_DO.COLORCODE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setColorcode(BigDecimal colorcode) {
        this.colorcode = colorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.ACCESSRESTRICTEN
     *
     * @return the value of C_TZX_PAR_CELL_DO.ACCESSRESTRICTEN
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getAccessrestricten() {
        return accessrestricten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.ACCESSRESTRICTEN
     *
     * @param accessrestricten the value for C_TZX_PAR_CELL_DO.ACCESSRESTRICTEN
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setAccessrestricten(BigDecimal accessrestricten) {
        this.accessrestricten = accessrestricten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.ACCESSDISTANCE
     *
     * @return the value of C_TZX_PAR_CELL_DO.ACCESSDISTANCE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getAccessdistance() {
        return accessdistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.ACCESSDISTANCE
     *
     * @param accessdistance the value for C_TZX_PAR_CELL_DO.ACCESSDISTANCE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setAccessdistance(BigDecimal accessdistance) {
        this.accessdistance = accessdistance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.ACCESSSIGNATURE
     *
     * @return the value of C_TZX_PAR_CELL_DO.ACCESSSIGNATURE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getAccesssignature() {
        return accesssignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.ACCESSSIGNATURE
     *
     * @param accesssignature the value for C_TZX_PAR_CELL_DO.ACCESSSIGNATURE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setAccesssignature(BigDecimal accesssignature) {
        this.accesssignature = accesssignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.LATITUDE
     *
     * @return the value of C_TZX_PAR_CELL_DO.LATITUDE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.LATITUDE
     *
     * @param latitude the value for C_TZX_PAR_CELL_DO.LATITUDE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.LONGITUDE
     *
     * @return the value of C_TZX_PAR_CELL_DO.LONGITUDE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.LONGITUDE
     *
     * @param longitude the value for C_TZX_PAR_CELL_DO.LONGITUDE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.ROUTEUPDATERADIUS
     *
     * @return the value of C_TZX_PAR_CELL_DO.ROUTEUPDATERADIUS
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getRouteupdateradius() {
        return routeupdateradius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.ROUTEUPDATERADIUS
     *
     * @param routeupdateradius the value for C_TZX_PAR_CELL_DO.ROUTEUPDATERADIUS
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setRouteupdateradius(BigDecimal routeupdateradius) {
        this.routeupdateradius = routeupdateradius;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.MAXIMUMREVISION
     *
     * @return the value of C_TZX_PAR_CELL_DO.MAXIMUMREVISION
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getMaximumrevision() {
        return maximumrevision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.MAXIMUMREVISION
     *
     * @param maximumrevision the value for C_TZX_PAR_CELL_DO.MAXIMUMREVISION
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setMaximumrevision(BigDecimal maximumrevision) {
        this.maximumrevision = maximumrevision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.MINIMUMREVISION
     *
     * @return the value of C_TZX_PAR_CELL_DO.MINIMUMREVISION
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getMinimumrevision() {
        return minimumrevision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.MINIMUMREVISION
     *
     * @param minimumrevision the value for C_TZX_PAR_CELL_DO.MINIMUMREVISION
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setMinimumrevision(BigDecimal minimumrevision) {
        this.minimumrevision = minimumrevision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.LEAPSECONDS
     *
     * @return the value of C_TZX_PAR_CELL_DO.LEAPSECONDS
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getLeapseconds() {
        return leapseconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.LEAPSECONDS
     *
     * @param leapseconds the value for C_TZX_PAR_CELL_DO.LEAPSECONDS
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setLeapseconds(BigDecimal leapseconds) {
        this.leapseconds = leapseconds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.LOCALTIMEOFFSET
     *
     * @return the value of C_TZX_PAR_CELL_DO.LOCALTIMEOFFSET
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getLocaltimeoffset() {
        return localtimeoffset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.LOCALTIMEOFFSET
     *
     * @param localtimeoffset the value for C_TZX_PAR_CELL_DO.LOCALTIMEOFFSET
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setLocaltimeoffset(BigDecimal localtimeoffset) {
        this.localtimeoffset = localtimeoffset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.CRKEEPTHRESHOLD
     *
     * @return the value of C_TZX_PAR_CELL_DO.CRKEEPTHRESHOLD
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getCrkeepthreshold() {
        return crkeepthreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.CRKEEPTHRESHOLD
     *
     * @param crkeepthreshold the value for C_TZX_PAR_CELL_DO.CRKEEPTHRESHOLD
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setCrkeepthreshold(BigDecimal crkeepthreshold) {
        this.crkeepthreshold = crkeepthreshold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.LOADBALANCETHRESH
     *
     * @return the value of C_TZX_PAR_CELL_DO.LOADBALANCETHRESH
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getLoadbalancethresh() {
        return loadbalancethresh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.LOADBALANCETHRESH
     *
     * @param loadbalancethresh the value for C_TZX_PAR_CELL_DO.LOADBALANCETHRESH
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setLoadbalancethresh(BigDecimal loadbalancethresh) {
        this.loadbalancethresh = loadbalancethresh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.STATUS
     *
     * @return the value of C_TZX_PAR_CELL_DO.STATUS
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.STATUS
     *
     * @param status the value for C_TZX_PAR_CELL_DO.STATUS
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setStatus(BigDecimal status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SECTORSIGNATURE
     *
     * @return the value of C_TZX_PAR_CELL_DO.SECTORSIGNATURE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSectorsignature() {
        return sectorsignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SECTORSIGNATURE
     *
     * @param sectorsignature the value for C_TZX_PAR_CELL_DO.SECTORSIGNATURE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSectorsignature(BigDecimal sectorsignature) {
        this.sectorsignature = sectorsignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.LONGLATLOCK_B
     *
     * @return the value of C_TZX_PAR_CELL_DO.LONGLATLOCK_B
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getLonglatlockB() {
        return longlatlockB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.LONGLATLOCK_B
     *
     * @param longlatlockB the value for C_TZX_PAR_CELL_DO.LONGLATLOCK_B
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setLonglatlockB(BigDecimal longlatlockB) {
        this.longlatlockB = longlatlockB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.ANID
     *
     * @return the value of C_TZX_PAR_CELL_DO.ANID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getAnid() {
        return anid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.ANID
     *
     * @param anid the value for C_TZX_PAR_CELL_DO.ANID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setAnid(BigDecimal anid) {
        this.anid = anid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.CI
     *
     * @return the value of C_TZX_PAR_CELL_DO.CI
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getCi() {
        return ci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.CI
     *
     * @param ci the value for C_TZX_PAR_CELL_DO.CI
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setCi(BigDecimal ci) {
        this.ci = ci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SUBNETADDRESS_B
     *
     * @return the value of C_TZX_PAR_CELL_DO.SUBNETADDRESS_B
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public String getSubnetaddressB() {
        return subnetaddressB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SUBNETADDRESS_B
     *
     * @param subnetaddressB the value for C_TZX_PAR_CELL_DO.SUBNETADDRESS_B
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSubnetaddressB(String subnetaddressB) {
        this.subnetaddressB = subnetaddressB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.BANDCLASS
     *
     * @return the value of C_TZX_PAR_CELL_DO.BANDCLASS
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getBandclass() {
        return bandclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.BANDCLASS
     *
     * @param bandclass the value for C_TZX_PAR_CELL_DO.BANDCLASS
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setBandclass(BigDecimal bandclass) {
        this.bandclass = bandclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.ALIAS_B
     *
     * @return the value of C_TZX_PAR_CELL_DO.ALIAS_B
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public String getAliasB() {
        return aliasB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.ALIAS_B
     *
     * @param aliasB the value for C_TZX_PAR_CELL_DO.ALIAS_B
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setAliasB(String aliasB) {
        this.aliasB = aliasB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SWITCH1
     *
     * @return the value of C_TZX_PAR_CELL_DO.SWITCH1
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSwitch1() {
        return switch1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SWITCH1
     *
     * @param switch1 the value for C_TZX_PAR_CELL_DO.SWITCH1
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSwitch1(BigDecimal switch1) {
        this.switch1 = switch1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SWITCH2
     *
     * @return the value of C_TZX_PAR_CELL_DO.SWITCH2
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSwitch2() {
        return switch2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SWITCH2
     *
     * @param switch2 the value for C_TZX_PAR_CELL_DO.SWITCH2
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSwitch2(BigDecimal switch2) {
        this.switch2 = switch2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SWITCH3
     *
     * @return the value of C_TZX_PAR_CELL_DO.SWITCH3
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSwitch3() {
        return switch3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SWITCH3
     *
     * @param switch3 the value for C_TZX_PAR_CELL_DO.SWITCH3
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSwitch3(BigDecimal switch3) {
        this.switch3 = switch3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SWITCH4
     *
     * @return the value of C_TZX_PAR_CELL_DO.SWITCH4
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSwitch4() {
        return switch4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SWITCH4
     *
     * @param switch4 the value for C_TZX_PAR_CELL_DO.SWITCH4
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSwitch4(BigDecimal switch4) {
        this.switch4 = switch4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SWITCH5
     *
     * @return the value of C_TZX_PAR_CELL_DO.SWITCH5
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSwitch5() {
        return switch5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SWITCH5
     *
     * @param switch5 the value for C_TZX_PAR_CELL_DO.SWITCH5
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSwitch5(BigDecimal switch5) {
        this.switch5 = switch5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SWITCH6
     *
     * @return the value of C_TZX_PAR_CELL_DO.SWITCH6
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSwitch6() {
        return switch6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SWITCH6
     *
     * @param switch6 the value for C_TZX_PAR_CELL_DO.SWITCH6
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSwitch6(BigDecimal switch6) {
        this.switch6 = switch6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SWITCH7
     *
     * @return the value of C_TZX_PAR_CELL_DO.SWITCH7
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSwitch7() {
        return switch7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SWITCH7
     *
     * @param switch7 the value for C_TZX_PAR_CELL_DO.SWITCH7
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSwitch7(BigDecimal switch7) {
        this.switch7 = switch7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SWITCH8
     *
     * @return the value of C_TZX_PAR_CELL_DO.SWITCH8
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSwitch8() {
        return switch8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SWITCH8
     *
     * @param switch8 the value for C_TZX_PAR_CELL_DO.SWITCH8
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSwitch8(BigDecimal switch8) {
        this.switch8 = switch8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SWITCH9
     *
     * @return the value of C_TZX_PAR_CELL_DO.SWITCH9
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSwitch9() {
        return switch9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SWITCH9
     *
     * @param switch9 the value for C_TZX_PAR_CELL_DO.SWITCH9
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSwitch9(BigDecimal switch9) {
        this.switch9 = switch9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SWITCH10
     *
     * @return the value of C_TZX_PAR_CELL_DO.SWITCH10
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSwitch10() {
        return switch10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SWITCH10
     *
     * @param switch10 the value for C_TZX_PAR_CELL_DO.SWITCH10
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSwitch10(BigDecimal switch10) {
        this.switch10 = switch10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SUBNETINDEXID
     *
     * @return the value of C_TZX_PAR_CELL_DO.SUBNETINDEXID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSubnetindexid() {
        return subnetindexid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SUBNETINDEXID
     *
     * @param subnetindexid the value for C_TZX_PAR_CELL_DO.SUBNETINDEXID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSubnetindexid(BigDecimal subnetindexid) {
        this.subnetindexid = subnetindexid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.PHYCELLID
     *
     * @return the value of C_TZX_PAR_CELL_DO.PHYCELLID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getPhycellid() {
        return phycellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.PHYCELLID
     *
     * @param phycellid the value for C_TZX_PAR_CELL_DO.PHYCELLID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setPhycellid(BigDecimal phycellid) {
        this.phycellid = phycellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SCENETYPE
     *
     * @return the value of C_TZX_PAR_CELL_DO.SCENETYPE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getScenetype() {
        return scenetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SCENETYPE
     *
     * @param scenetype the value for C_TZX_PAR_CELL_DO.SCENETYPE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setScenetype(BigDecimal scenetype) {
        this.scenetype = scenetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.ISSAMEPNSECTOR
     *
     * @return the value of C_TZX_PAR_CELL_DO.ISSAMEPNSECTOR
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getIssamepnsector() {
        return issamepnsector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.ISSAMEPNSECTOR
     *
     * @param issamepnsector the value for C_TZX_PAR_CELL_DO.ISSAMEPNSECTOR
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setIssamepnsector(BigDecimal issamepnsector) {
        this.issamepnsector = issamepnsector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.REFCELLID
     *
     * @return the value of C_TZX_PAR_CELL_DO.REFCELLID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getRefcellid() {
        return refcellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.REFCELLID
     *
     * @param refcellid the value for C_TZX_PAR_CELL_DO.REFCELLID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setRefcellid(BigDecimal refcellid) {
        this.refcellid = refcellid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SAMEPNCELLMAXNUM
     *
     * @return the value of C_TZX_PAR_CELL_DO.SAMEPNCELLMAXNUM
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSamepncellmaxnum() {
        return samepncellmaxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SAMEPNCELLMAXNUM
     *
     * @param samepncellmaxnum the value for C_TZX_PAR_CELL_DO.SAMEPNCELLMAXNUM
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSamepncellmaxnum(BigDecimal samepncellmaxnum) {
        this.samepncellmaxnum = samepncellmaxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SOFTERHOGROUPID
     *
     * @return the value of C_TZX_PAR_CELL_DO.SOFTERHOGROUPID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSofterhogroupid() {
        return softerhogroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SOFTERHOGROUPID
     *
     * @param softerhogroupid the value for C_TZX_PAR_CELL_DO.SOFTERHOGROUPID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSofterhogroupid(BigDecimal softerhogroupid) {
        this.softerhogroupid = softerhogroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.BTS_ALIAS
     *
     * @return the value of C_TZX_PAR_CELL_DO.BTS_ALIAS
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public String getBtsAlias() {
        return btsAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.BTS_ALIAS
     *
     * @param btsAlias the value for C_TZX_PAR_CELL_DO.BTS_ALIAS
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setBtsAlias(String btsAlias) {
        this.btsAlias = btsAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.ISSECTORMCCAPABLE
     *
     * @return the value of C_TZX_PAR_CELL_DO.ISSECTORMCCAPABLE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getIssectormccapable() {
        return issectormccapable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.ISSECTORMCCAPABLE
     *
     * @param issectormccapable the value for C_TZX_PAR_CELL_DO.ISSECTORMCCAPABLE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setIssectormccapable(BigDecimal issectormccapable) {
        this.issectormccapable = issectormccapable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.LATITUDE_B
     *
     * @return the value of C_TZX_PAR_CELL_DO.LATITUDE_B
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public Double getLatitudeB() {
        return latitudeB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.LATITUDE_B
     *
     * @param latitudeB the value for C_TZX_PAR_CELL_DO.LATITUDE_B
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setLatitudeB(Double latitudeB) {
        this.latitudeB = latitudeB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.LONGTITUDE_B
     *
     * @return the value of C_TZX_PAR_CELL_DO.LONGTITUDE_B
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public Double getLongtitudeB() {
        return longtitudeB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.LONGTITUDE_B
     *
     * @param longtitudeB the value for C_TZX_PAR_CELL_DO.LONGTITUDE_B
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setLongtitudeB(Double longtitudeB) {
        this.longtitudeB = longtitudeB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SECCOLORCODE1
     *
     * @return the value of C_TZX_PAR_CELL_DO.SECCOLORCODE1
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSeccolorcode1() {
        return seccolorcode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SECCOLORCODE1
     *
     * @param seccolorcode1 the value for C_TZX_PAR_CELL_DO.SECCOLORCODE1
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSeccolorcode1(BigDecimal seccolorcode1) {
        this.seccolorcode1 = seccolorcode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SECCOLORCODE2
     *
     * @return the value of C_TZX_PAR_CELL_DO.SECCOLORCODE2
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSeccolorcode2() {
        return seccolorcode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SECCOLORCODE2
     *
     * @param seccolorcode2 the value for C_TZX_PAR_CELL_DO.SECCOLORCODE2
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSeccolorcode2(BigDecimal seccolorcode2) {
        this.seccolorcode2 = seccolorcode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SECCOLORCODE3
     *
     * @return the value of C_TZX_PAR_CELL_DO.SECCOLORCODE3
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSeccolorcode3() {
        return seccolorcode3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SECCOLORCODE3
     *
     * @param seccolorcode3 the value for C_TZX_PAR_CELL_DO.SECCOLORCODE3
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSeccolorcode3(BigDecimal seccolorcode3) {
        this.seccolorcode3 = seccolorcode3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SECCOLORCODE4
     *
     * @return the value of C_TZX_PAR_CELL_DO.SECCOLORCODE4
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSeccolorcode4() {
        return seccolorcode4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SECCOLORCODE4
     *
     * @param seccolorcode4 the value for C_TZX_PAR_CELL_DO.SECCOLORCODE4
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSeccolorcode4(BigDecimal seccolorcode4) {
        this.seccolorcode4 = seccolorcode4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SECCOLORCODE5
     *
     * @return the value of C_TZX_PAR_CELL_DO.SECCOLORCODE5
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSeccolorcode5() {
        return seccolorcode5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SECCOLORCODE5
     *
     * @param seccolorcode5 the value for C_TZX_PAR_CELL_DO.SECCOLORCODE5
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSeccolorcode5(BigDecimal seccolorcode5) {
        this.seccolorcode5 = seccolorcode5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SECCOLORCODE6
     *
     * @return the value of C_TZX_PAR_CELL_DO.SECCOLORCODE6
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSeccolorcode6() {
        return seccolorcode6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SECCOLORCODE6
     *
     * @param seccolorcode6 the value for C_TZX_PAR_CELL_DO.SECCOLORCODE6
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSeccolorcode6(BigDecimal seccolorcode6) {
        this.seccolorcode6 = seccolorcode6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.SECCOLORCODE7
     *
     * @return the value of C_TZX_PAR_CELL_DO.SECCOLORCODE7
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getSeccolorcode7() {
        return seccolorcode7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.SECCOLORCODE7
     *
     * @param seccolorcode7 the value for C_TZX_PAR_CELL_DO.SECCOLORCODE7
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setSeccolorcode7(BigDecimal seccolorcode7) {
        this.seccolorcode7 = seccolorcode7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.MAINCONNQOSENABLED
     *
     * @return the value of C_TZX_PAR_CELL_DO.MAINCONNQOSENABLED
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getMainconnqosenabled() {
        return mainconnqosenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.MAINCONNQOSENABLED
     *
     * @param mainconnqosenabled the value for C_TZX_PAR_CELL_DO.MAINCONNQOSENABLED
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setMainconnqosenabled(BigDecimal mainconnqosenabled) {
        this.mainconnqosenabled = mainconnqosenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.FPC_MODE
     *
     * @return the value of C_TZX_PAR_CELL_DO.FPC_MODE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getFpcMode() {
        return fpcMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.FPC_MODE
     *
     * @param fpcMode the value for C_TZX_PAR_CELL_DO.FPC_MODE
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setFpcMode(BigDecimal fpcMode) {
        this.fpcMode = fpcMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.FPC_PTTSCH_FER
     *
     * @return the value of C_TZX_PAR_CELL_DO.FPC_PTTSCH_FER
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getFpcPttschFer() {
        return fpcPttschFer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.FPC_PTTSCH_FER
     *
     * @param fpcPttschFer the value for C_TZX_PAR_CELL_DO.FPC_PTTSCH_FER
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setFpcPttschFer(BigDecimal fpcPttschFer) {
        this.fpcPttschFer = fpcPttschFer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.FPC_PTTSCH_INI_SPT
     *
     * @return the value of C_TZX_PAR_CELL_DO.FPC_PTTSCH_INI_SPT
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getFpcPttschIniSpt() {
        return fpcPttschIniSpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.FPC_PTTSCH_INI_SPT
     *
     * @param fpcPttschIniSpt the value for C_TZX_PAR_CELL_DO.FPC_PTTSCH_INI_SPT
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setFpcPttschIniSpt(BigDecimal fpcPttschIniSpt) {
        this.fpcPttschIniSpt = fpcPttschIniSpt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column C_TZX_PAR_CELL_DO.AN_ID
     *
     * @return the value of C_TZX_PAR_CELL_DO.AN_ID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public BigDecimal getAnId() {
        return anId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column C_TZX_PAR_CELL_DO.AN_ID
     *
     * @param anId the value for C_TZX_PAR_CELL_DO.AN_ID
     *
     * @mbggenerated Fri Apr 12 09:50:55 CST 2013
     */
    public void setAnId(BigDecimal anId) {
        this.anId = anId;
    }
}