package com.scttsc.business.model;

import com.scttsc.admin.model.City;
import org.apache.commons.lang.time.DateFormatUtils;

import java.math.BigDecimal;
import java.util.Date;

public class DryStation {

    private BigDecimal id;
    private BigDecimal wybtsintid;
    private String wybtsname;
    private BigDecimal cityId;
    private BigDecimal no;
    private String coverage;
    private String model;
    private String fac;
    private String address;
    private String monitorflag;
    private String monitornumber;
    private String parentdevice;
    private String meteraddress;
    private String remark;

    private City country;
    private Bts bts;


    public Bts getBts() {
        return bts;
    }

    public void setBts(Bts bts) {
        this.bts = bts;
    }

    public City getCountry() {
        return country;
    }

    public void setCountry(City country) {
        this.country = country;
    }

    private Date updatetime;

    private Long updateuser;

    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_DRYSTATION.ID
     *
     * @param id the value for WY_DRYSTATION.ID
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_DRYSTATION.WYBTSINTID
     *
     * @return the value of WY_DRYSTATION.WYBTSINTID
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public BigDecimal getWybtsintid() {
        return wybtsintid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_DRYSTATION.WYBTSINTID
     *
     * @param wybtsintid the value for WY_DRYSTATION.WYBTSINTID
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public void setWybtsintid(BigDecimal wybtsintid) {
        this.wybtsintid = wybtsintid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_DRYSTATION.WYBTSNAME
     *
     * @return the value of WY_DRYSTATION.WYBTSNAME
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public String getWybtsname() {
        return wybtsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_DRYSTATION.WYBTSNAME
     *
     * @param wybtsname the value for WY_DRYSTATION.WYBTSNAME
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public void setWybtsname(String wybtsname) {
        this.wybtsname = wybtsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_DRYSTATION.CITY_ID
     *
     * @return the value of WY_DRYSTATION.CITY_ID
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public BigDecimal getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_DRYSTATION.CITY_ID
     *
     * @param cityId the value for WY_DRYSTATION.CITY_ID
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public void setCityId(BigDecimal cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_DRYSTATION.NO
     *
     * @return the value of WY_DRYSTATION.NO
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public BigDecimal getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_DRYSTATION.NO
     *
     * @param no the value for WY_DRYSTATION.NO
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public void setNo(BigDecimal no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_DRYSTATION.COVERAGE
     *
     * @return the value of WY_DRYSTATION.COVERAGE
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public String getCoverage() {
        return coverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_DRYSTATION.COVERAGE
     *
     * @param coverage the value for WY_DRYSTATION.COVERAGE
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public void setCoverage(String coverage) {
        this.coverage = coverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_DRYSTATION.MODEL
     *
     * @return the value of WY_DRYSTATION.MODEL
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_DRYSTATION.MODEL
     *
     * @param model the value for WY_DRYSTATION.MODEL
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_DRYSTATION.FAC
     *
     * @return the value of WY_DRYSTATION.FAC
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public String getFac() {
        return fac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_DRYSTATION.FAC
     *
     * @param fac the value for WY_DRYSTATION.FAC
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public void setFac(String fac) {
        this.fac = fac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_DRYSTATION.ADDRESS
     *
     * @return the value of WY_DRYSTATION.ADDRESS
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_DRYSTATION.ADDRESS
     *
     * @param address the value for WY_DRYSTATION.ADDRESS
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_DRYSTATION.MONITORFLAG
     *
     * @return the value of WY_DRYSTATION.MONITORFLAG
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public String getMonitorflag() {
        return monitorflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_DRYSTATION.MONITORFLAG
     *
     * @param monitorflag the value for WY_DRYSTATION.MONITORFLAG
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public void setMonitorflag(String monitorflag) {
        this.monitorflag = monitorflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_DRYSTATION.MONITORNUMBER
     *
     * @return the value of WY_DRYSTATION.MONITORNUMBER
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public String getMonitornumber() {
        return monitornumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_DRYSTATION.MONITORNUMBER
     *
     * @param monitornumber the value for WY_DRYSTATION.MONITORNUMBER
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public void setMonitornumber(String monitornumber) {
        this.monitornumber = monitornumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_DRYSTATION.PARENTDEVICE
     *
     * @return the value of WY_DRYSTATION.PARENTDEVICE
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public String getParentdevice() {
        return parentdevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_DRYSTATION.PARENTDEVICE
     *
     * @param parentdevice the value for WY_DRYSTATION.PARENTDEVICE
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public void setParentdevice(String parentdevice) {
        this.parentdevice = parentdevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_DRYSTATION.METERADDRESS
     *
     * @return the value of WY_DRYSTATION.METERADDRESS
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public String getMeteraddress() {
        return meteraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_DRYSTATION.METERADDRESS
     *
     * @param meteraddress the value for WY_DRYSTATION.METERADDRESS
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public void setMeteraddress(String meteraddress) {
        this.meteraddress = meteraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_DRYSTATION.REMARK
     *
     * @return the value of WY_DRYSTATION.REMARK
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_DRYSTATION.REMARK
     *
     * @param remark the value for WY_DRYSTATION.REMARK
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_DRYSTATION.UPDATETIME
     *
     * @return the value of WY_DRYSTATION.UPDATETIME
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    public String getUpdatetimeToString() {
        return updatetime == null ? "" : DateFormatUtils.format(updatetime, "yyyy-MM-dd HH:mm:ss");
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_DRYSTATION.UPDATETIME
     *
     * @param updatetime the value for WY_DRYSTATION.UPDATETIME
     * @mbggenerated Tue Apr 09 11:31:16 CST 2013
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    public Long getUpdateuser() {
        return updateuser;
    }

    public void setUpdateuser(Long updateuser) {
        this.updateuser = updateuser;
    }
}