package com.scttsc.business.model;

import com.scttsc.admin.model.City;
import com.scttsc.baselibs.model.WyLibVillage;

import java.math.BigDecimal;
import java.util.Date;

public class IndoorManual extends Entity {

    private String intId;

    private String name;

    private BigDecimal cityId;

    private BigDecimal countryId;

    private String countryIds;

    private BigDecimal longitude;

    private BigDecimal latitude;

    private String vendorBtstype;

    private String bscName;

    private String btsName;

    private BigDecimal cellSeq;

    private BigDecimal pn;

    private BigDecimal ci;

    private String prop1;

    private String prop2;

    private String grade;   //站点分级

    private String coverage;

    private BigDecimal buildingnum;

    private String address;

    private BigDecimal devicenum;

    private String monitorflag;

    private String monitornumber;

    private String deviceaddress;

    private BigDecimal repeaternum;  //直放站设备数量

    private BigDecimal drynum; //干放站设备数量

    private String distributedesc;

    private String distributefac;

    private String motorflag;

    private String motorarea;

    private String motorright;

    private String meteraddress;

    private String constructiondate;

    private String wlanflag;

    private String wlanshare;

    private String wlancoverage;

    private String ownername;

    private String ownerphone;

    private BigDecimal monitordevicenum;

    private String monitordeviceids;

    private String remark;

    private Date updatetime;

    private Long updateuser;

    private BigDecimal manualFlag;

    private Integer addFlag;

    //增加字段
    private String town;
    private String village;
    private WyLibVillage wyLibVillage;


    City city;
    City country;


    private String sceneLibs;//关联的场景库
    private String sceneLibNames;


    @Override
    public void setIgFields() {
        this.igFields.add("updatetime");
        this.igFields.add("city");
        this.igFields.add("country");
    }

    public String compareEntity(Object object){
        return super.compareEntity(object);
    }

    public String getCountryIds() {
        return countryIds;
    }

    public void setCountryIds(String countryIds) {
        this.countryIds = countryIds;
    }

    public Integer getAddFlag() {
        return addFlag;
    }

    public void setAddFlag(Integer addFlag) {
        this.addFlag = addFlag;
    }

    public String getIntId() {
        return intId;
    }

    public void setIntId(String intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.NAME
     *
     * @return the value of WY_INDOOR_MANUAL.NAME
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.NAME
     *
     * @param name the value for WY_INDOOR_MANUAL.NAME
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.CITY_ID
     *
     * @return the value of WY_INDOOR_MANUAL.CITY_ID
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public BigDecimal getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.CITY_ID
     *
     * @param cityId the value for WY_INDOOR_MANUAL.CITY_ID
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setCityId(BigDecimal cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.COUNTRY_ID
     *
     * @return the value of WY_INDOOR_MANUAL.COUNTRY_ID
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public BigDecimal getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.COUNTRY_ID
     *
     * @param countryId the value for WY_INDOOR_MANUAL.COUNTRY_ID
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setCountryId(BigDecimal countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.LONGITUDE
     *
     * @return the value of WY_INDOOR_MANUAL.LONGITUDE
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.LONGITUDE
     *
     * @param longitude the value for WY_INDOOR_MANUAL.LONGITUDE
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.LATITUDE
     *
     * @return the value of WY_INDOOR_MANUAL.LATITUDE
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.LATITUDE
     *
     * @param latitude the value for WY_INDOOR_MANUAL.LATITUDE
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.VENDOR_BTSTYPE
     *
     * @return the value of WY_INDOOR_MANUAL.VENDOR_BTSTYPE
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getVendorBtstype() {
        return vendorBtstype == null ? "" : vendorBtstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.VENDOR_BTSTYPE
     *
     * @param vendorBtstype the value for WY_INDOOR_MANUAL.VENDOR_BTSTYPE
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setVendorBtstype(String vendorBtstype) {
        this.vendorBtstype = vendorBtstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.BSC_NAME
     *
     * @return the value of WY_INDOOR_MANUAL.BSC_NAME
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getBscName() {
        return bscName == null ? "" : bscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.BSC_NAME
     *
     * @param bscName the value for WY_INDOOR_MANUAL.BSC_NAME
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setBscName(String bscName) {
        this.bscName = bscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.BTS_NAME
     *
     * @return the value of WY_INDOOR_MANUAL.BTS_NAME
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getBtsName() {
        return btsName == null ? "" : btsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.BTS_NAME
     *
     * @param btsName the value for WY_INDOOR_MANUAL.BTS_NAME
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setBtsName(String btsName) {
        this.btsName = btsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.CELL_SEQ
     *
     * @return the value of WY_INDOOR_MANUAL.CELL_SEQ
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public BigDecimal getCellSeq() {
        return cellSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.CELL_SEQ
     *
     * @param cellSeq the value for WY_INDOOR_MANUAL.CELL_SEQ
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setCellSeq(BigDecimal cellSeq) {
        this.cellSeq = cellSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.PN
     *
     * @return the value of WY_INDOOR_MANUAL.PN
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public BigDecimal getPn() {
        return pn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.PN
     *
     * @param pn the value for WY_INDOOR_MANUAL.PN
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setPn(BigDecimal pn) {
        this.pn = pn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.CI
     *
     * @return the value of WY_INDOOR_MANUAL.CI
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public BigDecimal getCi() {
        return ci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.CI
     *
     * @param ci the value for WY_INDOOR_MANUAL.CI
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setCi(BigDecimal ci) {
        this.ci = ci;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.PROP1
     *
     * @return the value of WY_INDOOR_MANUAL.PROP1
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getProp1() {
        return prop1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.PROP1
     *
     * @param prop1 the value for WY_INDOOR_MANUAL.PROP1
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setProp1(String prop1) {
        this.prop1 = prop1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.PROP2
     *
     * @return the value of WY_INDOOR_MANUAL.PROP2
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getProp2() {
        return prop2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.PROP2
     *
     * @param prop2 the value for WY_INDOOR_MANUAL.PROP2
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setProp2(String prop2) {
        this.prop2 = prop2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.GRADE
     *
     * @return the value of WY_INDOOR_MANUAL.GRADE
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.GRADE
     *
     * @param grade the value for WY_INDOOR_MANUAL.GRADE
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.COVERAGE
     *
     * @return the value of WY_INDOOR_MANUAL.COVERAGE
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getCoverage() {
        return coverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.COVERAGE
     *
     * @param coverage the value for WY_INDOOR_MANUAL.COVERAGE
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setCoverage(String coverage) {
        this.coverage = coverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.BUILDINGNUM
     *
     * @return the value of WY_INDOOR_MANUAL.BUILDINGNUM
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public BigDecimal getBuildingnum() {
        return buildingnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.BUILDINGNUM
     *
     * @param buildingnum the value for WY_INDOOR_MANUAL.BUILDINGNUM
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setBuildingnum(BigDecimal buildingnum) {
        this.buildingnum = buildingnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.ADDRESS
     *
     * @return the value of WY_INDOOR_MANUAL.ADDRESS
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.ADDRESS
     *
     * @param address the value for WY_INDOOR_MANUAL.ADDRESS
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.DEVICENUM
     *
     * @return the value of WY_INDOOR_MANUAL.DEVICENUM
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public BigDecimal getDevicenum() {
        return devicenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.DEVICENUM
     *
     * @param devicenum the value for WY_INDOOR_MANUAL.DEVICENUM
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setDevicenum(BigDecimal devicenum) {
        this.devicenum = devicenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.MONITORFLAG
     *
     * @return the value of WY_INDOOR_MANUAL.MONITORFLAG
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getMonitorflag() {
        return monitorflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.MONITORFLAG
     *
     * @param monitorflag the value for WY_INDOOR_MANUAL.MONITORFLAG
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setMonitorflag(String monitorflag) {
        this.monitorflag = monitorflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.MONITORNUMBER
     *
     * @return the value of WY_INDOOR_MANUAL.MONITORNUMBER
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getMonitornumber() {
        return monitornumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.MONITORNUMBER
     *
     * @param monitornumber the value for WY_INDOOR_MANUAL.MONITORNUMBER
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setMonitornumber(String monitornumber) {
        this.monitornumber = monitornumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.DEVICEADDRESS
     *
     * @return the value of WY_INDOOR_MANUAL.DEVICEADDRESS
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getDeviceaddress() {
        return deviceaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.DEVICEADDRESS
     *
     * @param deviceaddress the value for WY_INDOOR_MANUAL.DEVICEADDRESS
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setDeviceaddress(String deviceaddress) {
        this.deviceaddress = deviceaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.REPEATERNUM
     *
     * @return the value of WY_INDOOR_MANUAL.REPEATERNUM
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public BigDecimal getRepeaternum() {
        return repeaternum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.REPEATERNUM
     *
     * @param repeaternum the value for WY_INDOOR_MANUAL.REPEATERNUM
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setRepeaternum(BigDecimal repeaternum) {
        this.repeaternum = repeaternum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.DRYNUM
     *
     * @return the value of WY_INDOOR_MANUAL.DRYNUM
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public BigDecimal getDrynum() {
        return drynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.DRYNUM
     *
     * @param drynum the value for WY_INDOOR_MANUAL.DRYNUM
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setDrynum(BigDecimal drynum) {
        this.drynum = drynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.DISTRIBUTEDESC
     *
     * @return the value of WY_INDOOR_MANUAL.DISTRIBUTEDESC
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getDistributedesc() {
        return distributedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.DISTRIBUTEDESC
     *
     * @param distributedesc the value for WY_INDOOR_MANUAL.DISTRIBUTEDESC
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setDistributedesc(String distributedesc) {
        this.distributedesc = distributedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.DISTRIBUTEFAC
     *
     * @return the value of WY_INDOOR_MANUAL.DISTRIBUTEFAC
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getDistributefac() {
        return distributefac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.DISTRIBUTEFAC
     *
     * @param distributefac the value for WY_INDOOR_MANUAL.DISTRIBUTEFAC
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setDistributefac(String distributefac) {
        this.distributefac = distributefac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.MOTORFLAG
     *
     * @return the value of WY_INDOOR_MANUAL.MOTORFLAG
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getMotorflag() {
        return motorflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.MOTORFLAG
     *
     * @param motorflag the value for WY_INDOOR_MANUAL.MOTORFLAG
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setMotorflag(String motorflag) {
        this.motorflag = motorflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.MOTORAREA
     *
     * @return the value of WY_INDOOR_MANUAL.MOTORAREA
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getMotorarea() {
        return motorarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.MOTORAREA
     *
     * @param motorarea the value for WY_INDOOR_MANUAL.MOTORAREA
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setMotorarea(String motorarea) {
        this.motorarea = motorarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.MOTORRIGHT
     *
     * @return the value of WY_INDOOR_MANUAL.MOTORRIGHT
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getMotorright() {
        return motorright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.MOTORRIGHT
     *
     * @param motorright the value for WY_INDOOR_MANUAL.MOTORRIGHT
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setMotorright(String motorright) {
        this.motorright = motorright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.METERADDRESS
     *
     * @return the value of WY_INDOOR_MANUAL.METERADDRESS
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getMeteraddress() {
        return meteraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.METERADDRESS
     *
     * @param meteraddress the value for WY_INDOOR_MANUAL.METERADDRESS
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setMeteraddress(String meteraddress) {
        this.meteraddress = meteraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.CONSTRUCTIONDATE
     *
     * @return the value of WY_INDOOR_MANUAL.CONSTRUCTIONDATE
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getConstructiondate() {
        return constructiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.CONSTRUCTIONDATE
     *
     * @param constructiondate the value for WY_INDOOR_MANUAL.CONSTRUCTIONDATE
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setConstructiondate(String constructiondate) {
        this.constructiondate = constructiondate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.WLANFLAG
     *
     * @return the value of WY_INDOOR_MANUAL.WLANFLAG
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getWlanflag() {
        return wlanflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.WLANFLAG
     *
     * @param wlanflag the value for WY_INDOOR_MANUAL.WLANFLAG
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setWlanflag(String wlanflag) {
        this.wlanflag = wlanflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.WLANSHARE
     *
     * @return the value of WY_INDOOR_MANUAL.WLANSHARE
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getWlanshare() {
        return wlanshare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.WLANSHARE
     *
     * @param wlanshare the value for WY_INDOOR_MANUAL.WLANSHARE
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setWlanshare(String wlanshare) {
        this.wlanshare = wlanshare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.WLANCOVERAGE
     *
     * @return the value of WY_INDOOR_MANUAL.WLANCOVERAGE
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getWlancoverage() {
        return wlancoverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.WLANCOVERAGE
     *
     * @param wlancoverage the value for WY_INDOOR_MANUAL.WLANCOVERAGE
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setWlancoverage(String wlancoverage) {
        this.wlancoverage = wlancoverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.OWNERNAME
     *
     * @return the value of WY_INDOOR_MANUAL.OWNERNAME
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getOwnername() {
        return ownername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.OWNERNAME
     *
     * @param ownername the value for WY_INDOOR_MANUAL.OWNERNAME
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setOwnername(String ownername) {
        this.ownername = ownername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.OWNERPHONE
     *
     * @return the value of WY_INDOOR_MANUAL.OWNERPHONE
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getOwnerphone() {
        return ownerphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.OWNERPHONE
     *
     * @param ownerphone the value for WY_INDOOR_MANUAL.OWNERPHONE
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setOwnerphone(String ownerphone) {
        this.ownerphone = ownerphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.MONITORDEVICENUM
     *
     * @return the value of WY_INDOOR_MANUAL.MONITORDEVICENUM
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public BigDecimal getMonitordevicenum() {
        return monitordevicenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.MONITORDEVICENUM
     *
     * @param monitordevicenum the value for WY_INDOOR_MANUAL.MONITORDEVICENUM
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setMonitordevicenum(BigDecimal monitordevicenum) {
        this.monitordevicenum = monitordevicenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.MONITORDEVICEIDS
     *
     * @return the value of WY_INDOOR_MANUAL.MONITORDEVICEIDS
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getMonitordeviceids() {
        return monitordeviceids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.MONITORDEVICEIDS
     *
     * @param monitordeviceids the value for WY_INDOOR_MANUAL.MONITORDEVICEIDS
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setMonitordeviceids(String monitordeviceids) {
        this.monitordeviceids = monitordeviceids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.REMARK
     *
     * @return the value of WY_INDOOR_MANUAL.REMARK
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.REMARK
     *
     * @param remark the value for WY_INDOOR_MANUAL.REMARK
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_INDOOR_MANUAL.UPDATETIME
     *
     * @return the value of WY_INDOOR_MANUAL.UPDATETIME
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_INDOOR_MANUAL.UPDATETIME
     *
     * @param updatetime the value for WY_INDOOR_MANUAL.UPDATETIME
     * @mbggenerated Tue Apr 09 11:30:50 CST 2013
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }


    public Long getUpdateuser() {
        return updateuser;
    }

    public void setUpdateuser(Long updateuser) {
        this.updateuser = updateuser;
    }

    public City getCity() {
        return city;
    }

    public void setCity(City city) {
        this.city = city;
    }

    public City getCountry() {
        return country;
    }

    public void setCountry(City country) {
        this.country = country;
    }

    public BigDecimal getManualFlag() {
        return manualFlag;
    }

    public void setManualFlag(BigDecimal manualFlag) {
        this.manualFlag = manualFlag;
    }

    public String getTown() {
        return town;
    }

    public void setTown(String town) {
        this.town = town;
    }

    public String getVillage() {
        return village;
    }

    public void setVillage(String village) {
        this.village = village;
    }

    public String getSceneLibs() {
        return sceneLibs;
    }

    public void setSceneLibs(String sceneLibs) {
        this.sceneLibs = sceneLibs;
    }

    public String getSceneLibNames() {
        return sceneLibNames;
    }

    public void setSceneLibNames(String sceneLibNames) {
        this.sceneLibNames = sceneLibNames;
    }

    public WyLibVillage getWyLibVillage() {
        return wyLibVillage;
    }
    public void setWyLibVillage(WyLibVillage wyLibVillage) {
        this.wyLibVillage = wyLibVillage;
    }
}