package com.scttsc.business.model;

import com.scttsc.admin.model.User;

import java.math.BigDecimal;
import java.util.Date;

public class Template {

    private BigDecimal id;
    private String name;//模板名称
    private String columnsConfigs;
    private BigDecimal type;
    private Long userId;
    private Date updateTime;
    private BigDecimal shareflag;
    private Integer useFlag;//模板用途

    User user;//定制用户

    //冗余

    private String useFlagStr;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_TEMPLATE.ID
     *
     * @return the value of WY_TEMPLATE.ID
     *
     * @mbggenerated Mon Apr 22 19:31:06 CST 2013
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_TEMPLATE.ID
     *
     * @param id the value for WY_TEMPLATE.ID
     *
     * @mbggenerated Mon Apr 22 19:31:06 CST 2013
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_TEMPLATE.COLUMNS_CONFIGS
     *
     * @return the value of WY_TEMPLATE.COLUMNS_CONFIGS
     *
     * @mbggenerated Mon Apr 22 19:31:06 CST 2013
     */
    public String getColumnsConfigs() {
        return columnsConfigs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_TEMPLATE.COLUMNS_CONFIGS
     *
     * @param columnsConfigs the value for WY_TEMPLATE.COLUMNS_CONFIGS
     *
     * @mbggenerated Mon Apr 22 19:31:06 CST 2013
     */
    public void setColumnsConfigs(String columnsConfigs) {
        this.columnsConfigs = columnsConfigs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_TEMPLATE.TYPE
     *
     * @return the value of WY_TEMPLATE.TYPE
     *
     * @mbggenerated Mon Apr 22 19:31:06 CST 2013
     */
    public BigDecimal getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_TEMPLATE.TYPE
     *
     * @param type the value for WY_TEMPLATE.TYPE
     *
     * @mbggenerated Mon Apr 22 19:31:06 CST 2013
     */
    public void setType(BigDecimal type) {
        this.type = type;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_TEMPLATE.UPDATE_TIME
     *
     * @return the value of WY_TEMPLATE.UPDATE_TIME
     *
     * @mbggenerated Mon Apr 22 19:31:06 CST 2013
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_TEMPLATE.UPDATE_TIME
     *
     * @param updateTime the value for WY_TEMPLATE.UPDATE_TIME
     *
     * @mbggenerated Mon Apr 22 19:31:06 CST 2013
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_TEMPLATE.SHAREFLAG
     *
     * @return the value of WY_TEMPLATE.SHAREFLAG
     *
     * @mbggenerated Mon Apr 22 19:31:06 CST 2013
     */
    public BigDecimal getShareflag() {
        return shareflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_TEMPLATE.SHAREFLAG
     *
     * @param shareflag the value for WY_TEMPLATE.SHAREFLAG
     *
     * @mbggenerated Mon Apr 22 19:31:06 CST 2013
     */
    public void setShareflag(BigDecimal shareflag) {
        this.shareflag = shareflag;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Integer getUseFlag() {
        return useFlag;
    }

    public void setUseFlag(Integer useFlag) {
        this.useFlag = useFlag;
    }

    public String getUseFlagStr() {
        if(useFlag!=null){
            switch (useFlag.intValue()){
                case 0:
                    useFlagStr="导出模板";
                    break;
                case 1:
                    useFlagStr="统计模板";
                    break;
            }
        }
        return useFlagStr;
    }

    public void setUseFlagStr(String useFlagStr) {
        this.useFlagStr = useFlagStr;
    }
}