package com.scttsc.business.model;

import com.scttsc.admin.model.City;

import java.math.BigDecimal;
import java.util.Date;

public class WrongName {

    private BigDecimal intId;
    private String cellName;
    private String bscName;
    private BigDecimal btsId;
    private String btsname;
    private Date intime;
    private Date updatetime;
    private BigDecimal deleteFlag;
    private BigDecimal type;
    private BigDecimal cityId;

    private City city;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_WRONGNAME.INT_ID
     *
     * @return the value of WY_WRONGNAME.INT_ID
     * @mbggenerated Sat Apr 27 16:17:58 CST 2013
     */
    public BigDecimal getIntId() {
        return intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_WRONGNAME.INT_ID
     *
     * @param intId the value for WY_WRONGNAME.INT_ID
     * @mbggenerated Sat Apr 27 16:17:58 CST 2013
     */
    public void setIntId(BigDecimal intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_WRONGNAME.CELL_NAME
     *
     * @return the value of WY_WRONGNAME.CELL_NAME
     * @mbggenerated Sat Apr 27 16:17:58 CST 2013
     */
    public String getCellName() {
        return cellName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_WRONGNAME.CELL_NAME
     *
     * @param cellName the value for WY_WRONGNAME.CELL_NAME
     * @mbggenerated Sat Apr 27 16:17:58 CST 2013
     */
    public void setCellName(String cellName) {
        this.cellName = cellName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_WRONGNAME.BSC_NAME
     *
     * @return the value of WY_WRONGNAME.BSC_NAME
     * @mbggenerated Sat Apr 27 16:17:58 CST 2013
     */
    public String getBscName() {
        return bscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_WRONGNAME.BSC_NAME
     *
     * @param bscName the value for WY_WRONGNAME.BSC_NAME
     * @mbggenerated Sat Apr 27 16:17:58 CST 2013
     */
    public void setBscName(String bscName) {
        this.bscName = bscName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_WRONGNAME.BTS_ID
     *
     * @return the value of WY_WRONGNAME.BTS_ID
     * @mbggenerated Sat Apr 27 16:17:58 CST 2013
     */
    public BigDecimal getBtsId() {
        return btsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_WRONGNAME.BTS_ID
     *
     * @param btsId the value for WY_WRONGNAME.BTS_ID
     * @mbggenerated Sat Apr 27 16:17:58 CST 2013
     */
    public void setBtsId(BigDecimal btsId) {
        this.btsId = btsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_WRONGNAME.BTSNAME
     *
     * @return the value of WY_WRONGNAME.BTSNAME
     * @mbggenerated Sat Apr 27 16:17:58 CST 2013
     */
    public String getBtsname() {
        return btsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_WRONGNAME.BTSNAME
     *
     * @param btsname the value for WY_WRONGNAME.BTSNAME
     * @mbggenerated Sat Apr 27 16:17:58 CST 2013
     */
    public void setBtsname(String btsname) {
        this.btsname = btsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_WRONGNAME.INTIME
     *
     * @return the value of WY_WRONGNAME.INTIME
     * @mbggenerated Sat Apr 27 16:17:58 CST 2013
     */
    public Date getIntime() {
        return intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_WRONGNAME.INTIME
     *
     * @param intime the value for WY_WRONGNAME.INTIME
     * @mbggenerated Sat Apr 27 16:17:58 CST 2013
     */
    public void setIntime(Date intime) {
        this.intime = intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_WRONGNAME.UPDATETIME
     *
     * @return the value of WY_WRONGNAME.UPDATETIME
     * @mbggenerated Sat Apr 27 16:17:58 CST 2013
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_WRONGNAME.UPDATETIME
     *
     * @param updatetime the value for WY_WRONGNAME.UPDATETIME
     * @mbggenerated Sat Apr 27 16:17:58 CST 2013
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_WRONGNAME.DELETE_FLAG
     *
     * @return the value of WY_WRONGNAME.DELETE_FLAG
     * @mbggenerated Sat Apr 27 16:17:58 CST 2013
     */
    public BigDecimal getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_WRONGNAME.DELETE_FLAG
     *
     * @param deleteFlag the value for WY_WRONGNAME.DELETE_FLAG
     * @mbggenerated Sat Apr 27 16:17:58 CST 2013
     */
    public void setDeleteFlag(BigDecimal deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_WRONGNAME.TYPE
     *
     * @return the value of WY_WRONGNAME.TYPE
     * @mbggenerated Sat Apr 27 16:17:58 CST 2013
     */
    public BigDecimal getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_WRONGNAME.TYPE
     *
     * @param type the value for WY_WRONGNAME.TYPE
     * @mbggenerated Sat Apr 27 16:17:58 CST 2013
     */
    public void setType(BigDecimal type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_WRONGNAME.CITY_ID
     *
     * @return the value of WY_WRONGNAME.CITY_ID
     * @mbggenerated Sat Apr 27 16:17:58 CST 2013
     */
    public BigDecimal getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_WRONGNAME.CITY_ID
     *
     * @param cityId the value for WY_WRONGNAME.CITY_ID
     * @mbggenerated Sat Apr 27 16:17:58 CST 2013
     */
    public void setCityId(BigDecimal cityId) {
        this.cityId = cityId;
    }


    public City getCity() {
        return city;
    }

    public void setCity(City city) {
        this.city = city;
    }
}