package com.scttsc.baselibs.model;

import java.math.BigDecimal;
import java.util.Date;

import com.scttsc.common.dao.MyBatisRepository;
import com.scttsc.common.util.DateUtil;
import com.scttsc.common.util.DateUtils;

@MyBatisRepository
public class RoadLib {
  
    private BigDecimal id;
    private BigDecimal cityId;
    private BigDecimal roadProp;
    private String name;
    private BigDecimal speed;
    private BigDecimal lineMile;
    private BigDecimal tunnelMile;
    private BigDecimal plainMile;
    private BigDecimal mountainMile;
    private BigDecimal stationNum;
    private BigDecimal covertype;
    private BigDecimal coverMile1x;
    private BigDecimal coverRate1x;
    private BigDecimal dropcallMile;
    private BigDecimal coverMileDo;
    private BigDecimal coverRateDo;
    private BigDecimal downTpRate;
    private BigDecimal downTpgoodRate;//有覆盖区域下行吞吐率优良比（>=300kbps）：
    private BigDecimal coverStationNum;//辖区内已覆盖车站（收费站或服务区）数量：
    private BigDecimal coverStationRate;//辖区内已覆盖车站（收费站或服务区）覆盖比例：
    private Date testtime;
    private String testuser;
    private Date intime;
    private Date updatetime;
    private String remark;
    private Integer deleteFlag;
    
    
    
    //冗余字段
    private String cityName;//本地网名称
    private String roadPropName;//属性名称
    private String coverTypeName;//沿线CDMA覆盖方式
    private String testTimeStr;//测试时间字符型，界面展示

 
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.ID
     *
     * @param id the value for WY_LIB_ROAD.ID
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.CITY_ID
     *
     * @return the value of WY_LIB_ROAD.CITY_ID
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public BigDecimal getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.CITY_ID
     *
     * @param cityId the value for WY_LIB_ROAD.CITY_ID
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setCityId(BigDecimal cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.ROAD_PROP
     *
     * @return the value of WY_LIB_ROAD.ROAD_PROP
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public BigDecimal getRoadProp() {
        return roadProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.ROAD_PROP
     *
     * @param roadProp the value for WY_LIB_ROAD.ROAD_PROP
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setRoadProp(BigDecimal roadProp) {
        this.roadProp = roadProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.NAME
     *
     * @return the value of WY_LIB_ROAD.NAME
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.NAME
     *
     * @param name the value for WY_LIB_ROAD.NAME
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.SPEED
     *
     * @return the value of WY_LIB_ROAD.SPEED
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public BigDecimal getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.SPEED
     *
     * @param speed the value for WY_LIB_ROAD.SPEED
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setSpeed(BigDecimal speed) {
        this.speed = speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.LINE_MILE
     *
     * @return the value of WY_LIB_ROAD.LINE_MILE
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public BigDecimal getLineMile() {
        return lineMile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.LINE_MILE
     *
     * @param lineMile the value for WY_LIB_ROAD.LINE_MILE
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setLineMile(BigDecimal lineMile) {
        this.lineMile = lineMile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.TUNNEL_MILE
     *
     * @return the value of WY_LIB_ROAD.TUNNEL_MILE
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public BigDecimal getTunnelMile() {
        return tunnelMile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.TUNNEL_MILE
     *
     * @param tunnelMile the value for WY_LIB_ROAD.TUNNEL_MILE
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setTunnelMile(BigDecimal tunnelMile) {
        this.tunnelMile = tunnelMile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.PLAIN_MILE
     *
     * @return the value of WY_LIB_ROAD.PLAIN_MILE
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public BigDecimal getPlainMile() {
        return plainMile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.PLAIN_MILE
     *
     * @param plainMile the value for WY_LIB_ROAD.PLAIN_MILE
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setPlainMile(BigDecimal plainMile) {
        this.plainMile = plainMile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.MOUNTAIN_MILE
     *
     * @return the value of WY_LIB_ROAD.MOUNTAIN_MILE
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public BigDecimal getMountainMile() {
        return mountainMile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.MOUNTAIN_MILE
     *
     * @param mountainMile the value for WY_LIB_ROAD.MOUNTAIN_MILE
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setMountainMile(BigDecimal mountainMile) {
        this.mountainMile = mountainMile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.STATION_NUM
     *
     * @return the value of WY_LIB_ROAD.STATION_NUM
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public BigDecimal getStationNum() {
        return stationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.STATION_NUM
     *
     * @param stationNum the value for WY_LIB_ROAD.STATION_NUM
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setStationNum(BigDecimal stationNum) {
        this.stationNum = stationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.COVERTYPE
     *
     * @return the value of WY_LIB_ROAD.COVERTYPE
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public BigDecimal getCovertype() {
        return covertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.COVERTYPE
     *
     * @param covertype the value for WY_LIB_ROAD.COVERTYPE
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setCovertype(BigDecimal covertype) {
        this.covertype = covertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.COVER_MILE_1X
     *
     * @return the value of WY_LIB_ROAD.COVER_MILE_1X
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public BigDecimal getCoverMile1x() {
        return coverMile1x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.COVER_MILE_1X
     *
     * @param coverMile1x the value for WY_LIB_ROAD.COVER_MILE_1X
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setCoverMile1x(BigDecimal coverMile1x) {
        this.coverMile1x = coverMile1x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.COVER_RATE_1X
     *
     * @return the value of WY_LIB_ROAD.COVER_RATE_1X
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public BigDecimal getCoverRate1x() {
        return coverRate1x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.COVER_RATE_1X
     *
     * @param coverRate1x the value for WY_LIB_ROAD.COVER_RATE_1X
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setCoverRate1x(BigDecimal coverRate1x) {
        this.coverRate1x = coverRate1x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.DROPCALL_MILE
     *
     * @return the value of WY_LIB_ROAD.DROPCALL_MILE
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public BigDecimal getDropcallMile() {
        return dropcallMile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.DROPCALL_MILE
     *
     * @param dropcallMile the value for WY_LIB_ROAD.DROPCALL_MILE
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setDropcallMile(BigDecimal dropcallMile) {
        this.dropcallMile = dropcallMile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.COVER_MILE_DO
     *
     * @return the value of WY_LIB_ROAD.COVER_MILE_DO
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public BigDecimal getCoverMileDo() {
        return coverMileDo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.COVER_MILE_DO
     *
     * @param coverMileDo the value for WY_LIB_ROAD.COVER_MILE_DO
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setCoverMileDo(BigDecimal coverMileDo) {
        this.coverMileDo = coverMileDo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.COVER_RATE_DO
     *
     * @return the value of WY_LIB_ROAD.COVER_RATE_DO
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public BigDecimal getCoverRateDo() {
        return coverRateDo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.COVER_RATE_DO
     *
     * @param coverRateDo the value for WY_LIB_ROAD.COVER_RATE_DO
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setCoverRateDo(BigDecimal coverRateDo) {
        this.coverRateDo = coverRateDo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.DOWN_TP_RATE
     *
     * @return the value of WY_LIB_ROAD.DOWN_TP_RATE
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public BigDecimal getDownTpRate() {
        return downTpRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.DOWN_TP_RATE
     *
     * @param downTpRate the value for WY_LIB_ROAD.DOWN_TP_RATE
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setDownTpRate(BigDecimal downTpRate) {
        this.downTpRate = downTpRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.DOWN_TPGOOD_RATE
     *
     * @return the value of WY_LIB_ROAD.DOWN_TPGOOD_RATE
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public BigDecimal getDownTpgoodRate() {
        return downTpgoodRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.DOWN_TPGOOD_RATE
     *
     * @param downTpgoodRate the value for WY_LIB_ROAD.DOWN_TPGOOD_RATE
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setDownTpgoodRate(BigDecimal downTpgoodRate) {
        this.downTpgoodRate = downTpgoodRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.COVER_STATION_NUM
     *
     * @return the value of WY_LIB_ROAD.COVER_STATION_NUM
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public BigDecimal getCoverStationNum() {
        return coverStationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.COVER_STATION_NUM
     *
     * @param coverStationNum the value for WY_LIB_ROAD.COVER_STATION_NUM
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setCoverStationNum(BigDecimal coverStationNum) {
        this.coverStationNum = coverStationNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.COVER_STATION_RATE
     *
     * @return the value of WY_LIB_ROAD.COVER_STATION_RATE
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public BigDecimal getCoverStationRate() {
        return coverStationRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.COVER_STATION_RATE
     *
     * @param coverStationRate the value for WY_LIB_ROAD.COVER_STATION_RATE
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setCoverStationRate(BigDecimal coverStationRate) {
        this.coverStationRate = coverStationRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.TESTTIME
     *
     * @return the value of WY_LIB_ROAD.TESTTIME
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public Date getTesttime() {
        return testtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.TESTTIME
     *
     * @param testtime the value for WY_LIB_ROAD.TESTTIME
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setTesttime(Date testtime) {
        this.testtime = testtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.TESTUSER
     *
     * @return the value of WY_LIB_ROAD.TESTUSER
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public String getTestuser() {
        return testuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.TESTUSER
     *
     * @param testuser the value for WY_LIB_ROAD.TESTUSER
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setTestuser(String testuser) {
        this.testuser = testuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.INTIME
     *
     * @return the value of WY_LIB_ROAD.INTIME
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public Date getIntime() {
        return intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.INTIME
     *
     * @param intime the value for WY_LIB_ROAD.INTIME
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setIntime(Date intime) {
        this.intime = intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.UPDATETIME
     *
     * @return the value of WY_LIB_ROAD.UPDATETIME
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.UPDATETIME
     *
     * @param updatetime the value for WY_LIB_ROAD.UPDATETIME
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_ROAD.REMARK
     *
     * @return the value of WY_LIB_ROAD.REMARK
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_ROAD.REMARK
     *
     * @param remark the value for WY_LIB_ROAD.REMARK
     *
     * @mbggenerated Tue Mar 19 12:01:36 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getRoadPropName() {
		return roadPropName;
	}

	public void setRoadPropName(String roadPropName) {
		this.roadPropName = roadPropName;
	}

	public String getCoverTypeName() {
		return coverTypeName;
	}

	public void setCoverTypeName(String coverTypeName) {
		this.coverTypeName = coverTypeName;
	}

	public String getTestTimeStr() {
		return (testtime==null)?"":DateUtils.formatDateTime(testtime, "yyyy-MM-dd");
	}

	public void setTestTimeStr(String testTimeStr) {
		this.testTimeStr = testTimeStr;
	}

    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}