package com.scttsc.baselibs.model;

import java.math.BigDecimal;
import java.util.Date;

public class SecneryLib {

    private BigDecimal id;
    private BigDecimal provinceId;
    private BigDecimal cityId;
    private BigDecimal countryId;
    private String sceName;
    private BigDecimal sceLevel;
    private BigDecimal longitude;
    private BigDecimal latitude;
    private Date intime;
    private Date updatetime;
    private String remark;
    private Integer deleteFlag;
    
    
    //冗余
    
    private String cityName;
    private String countryName;
    private String scelevelName;

 
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_SCENERY.ID
     *
     * @param id the value for WY_LIB_SCENERY.ID
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_SCENERY.PROVINCE_ID
     *
     * @return the value of WY_LIB_SCENERY.PROVINCE_ID
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public BigDecimal getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_SCENERY.PROVINCE_ID
     *
     * @param provinceId the value for WY_LIB_SCENERY.PROVINCE_ID
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public void setProvinceId(BigDecimal provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_SCENERY.CITY_ID
     *
     * @return the value of WY_LIB_SCENERY.CITY_ID
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public BigDecimal getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_SCENERY.CITY_ID
     *
     * @param cityId the value for WY_LIB_SCENERY.CITY_ID
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public void setCityId(BigDecimal cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_SCENERY.COUNTRY_ID
     *
     * @return the value of WY_LIB_SCENERY.COUNTRY_ID
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public BigDecimal getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_SCENERY.COUNTRY_ID
     *
     * @param countryId the value for WY_LIB_SCENERY.COUNTRY_ID
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public void setCountryId(BigDecimal countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_SCENERY.SCE_NAME
     *
     * @return the value of WY_LIB_SCENERY.SCE_NAME
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public String getSceName() {
        return sceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_SCENERY.SCE_NAME
     *
     * @param sceName the value for WY_LIB_SCENERY.SCE_NAME
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public void setSceName(String sceName) {
        this.sceName = sceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_SCENERY.SCE_LEVEL
     *
     * @return the value of WY_LIB_SCENERY.SCE_LEVEL
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public BigDecimal getSceLevel() {
        return sceLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_SCENERY.SCE_LEVEL
     *
     * @param sceLevel the value for WY_LIB_SCENERY.SCE_LEVEL
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public void setSceLevel(BigDecimal sceLevel) {
        this.sceLevel = sceLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_SCENERY.LONGITUDE
     *
     * @return the value of WY_LIB_SCENERY.LONGITUDE
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_SCENERY.LONGITUDE
     *
     * @param longitude the value for WY_LIB_SCENERY.LONGITUDE
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_SCENERY.LATITUDE
     *
     * @return the value of WY_LIB_SCENERY.LATITUDE
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_SCENERY.LATITUDE
     *
     * @param latitude the value for WY_LIB_SCENERY.LATITUDE
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_SCENERY.INTIME
     *
     * @return the value of WY_LIB_SCENERY.INTIME
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public Date getIntime() {
        return intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_SCENERY.INTIME
     *
     * @param intime the value for WY_LIB_SCENERY.INTIME
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public void setIntime(Date intime) {
        this.intime = intime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_SCENERY.UPDATETIME
     *
     * @return the value of WY_LIB_SCENERY.UPDATETIME
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_SCENERY.UPDATETIME
     *
     * @param updatetime the value for WY_LIB_SCENERY.UPDATETIME
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WY_LIB_SCENERY.REMARK
     *
     * @return the value of WY_LIB_SCENERY.REMARK
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WY_LIB_SCENERY.REMARK
     *
     * @param remark the value for WY_LIB_SCENERY.REMARK
     *
     * @mbggenerated Tue Mar 19 11:42:04 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getCountryName() {
		return countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	public String getScelevelName() {
		return scelevelName;
	}

	public void setScelevelName(String scelevelName) {
		this.scelevelName = scelevelName;
	}

    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}