package com.scttsc.baselibs.model;

import java.math.BigDecimal;
import java.util.Date;

public class TunnelLib {

	private BigDecimal id;
	private BigDecimal cityId;
	private BigDecimal countryId;
	private String name;
	private BigDecimal roadId;
	private BigDecimal tunnellength;
	private String direction;
	private BigDecimal longitude;
	private BigDecimal latitude;
	private BigDecimal height;
	private String covgtype;
	private String installadress;
	private String rights;
	private String togbs;
	private String togname;
	private String opentime;
	private String address;
	private String remark;
	private Date updatetime;
	private Long updateuser;
    private Integer deleteFlag;
    private Integer autoFlag;//自动解析标识
	
	
	//冗余
	private String cityName;
	private String countryName;
	private String roadPropName;
	private String roadName;

    private String autoFlagStr;


    private RoadLib roadLib;

	public BigDecimal getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_LIB_TUNNEL.ID
	 * 
	 * @param id
	 *            the value for WY_LIB_TUNNEL.ID
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public void setId(BigDecimal id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_LIB_TUNNEL.CITY_ID
	 * 
	 * @return the value of WY_LIB_TUNNEL.CITY_ID
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public BigDecimal getCityId() {
		return cityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_LIB_TUNNEL.CITY_ID
	 * 
	 * @param cityId
	 *            the value for WY_LIB_TUNNEL.CITY_ID
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public void setCityId(BigDecimal cityId) {
		this.cityId = cityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_LIB_TUNNEL.COUNTRY_ID
	 * 
	 * @return the value of WY_LIB_TUNNEL.COUNTRY_ID
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public BigDecimal getCountryId() {
		return countryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_LIB_TUNNEL.COUNTRY_ID
	 * 
	 * @param countryId
	 *            the value for WY_LIB_TUNNEL.COUNTRY_ID
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public void setCountryId(BigDecimal countryId) {
		this.countryId = countryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_LIB_TUNNEL.ROAD_ID
	 * 
	 * @return the value of WY_LIB_TUNNEL.ROAD_ID
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public BigDecimal getRoadId() {
		return roadId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_LIB_TUNNEL.ROAD_ID
	 * 
	 * @param roadId
	 *            the value for WY_LIB_TUNNEL.ROAD_ID
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public void setRoadId(BigDecimal roadId) {
		this.roadId = roadId;
	}

    public BigDecimal getTunnellength() {
        return tunnellength;
    }

    public void setTunnellength(BigDecimal tunnellength) {
        this.tunnellength = tunnellength;
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_LIB_TUNNEL.DIRECTION
	 * 
	 * @return the value of WY_LIB_TUNNEL.DIRECTION
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public String getDirection() {
		return direction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_LIB_TUNNEL.DIRECTION
	 * 
	 * @param direction
	 *            the value for WY_LIB_TUNNEL.DIRECTION
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public void setDirection(String direction) {
		this.direction = direction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_LIB_TUNNEL.LONGITUDE
	 * 
	 * @return the value of WY_LIB_TUNNEL.LONGITUDE
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public BigDecimal getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_LIB_TUNNEL.LONGITUDE
	 * 
	 * @param longitude
	 *            the value for WY_LIB_TUNNEL.LONGITUDE
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_LIB_TUNNEL.LATITUDE
	 * 
	 * @return the value of WY_LIB_TUNNEL.LATITUDE
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public BigDecimal getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_LIB_TUNNEL.LATITUDE
	 * 
	 * @param latitude
	 *            the value for WY_LIB_TUNNEL.LATITUDE
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_LIB_TUNNEL.HEIGHT
	 * 
	 * @return the value of WY_LIB_TUNNEL.HEIGHT
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public BigDecimal getHeight() {
		return height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_LIB_TUNNEL.HEIGHT
	 * 
	 * @param height
	 *            the value for WY_LIB_TUNNEL.HEIGHT
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public void setHeight(BigDecimal height) {
		this.height = height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_LIB_TUNNEL.COVGTYPE
	 * 
	 * @return the value of WY_LIB_TUNNEL.COVGTYPE
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public String getCovgtype() {
		return covgtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_LIB_TUNNEL.COVGTYPE
	 * 
	 * @param covgtype
	 *            the value for WY_LIB_TUNNEL.COVGTYPE
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public void setCovgtype(String covgtype) {
		this.covgtype = covgtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_LIB_TUNNEL.INSTALLADRESS
	 * 
	 * @return the value of WY_LIB_TUNNEL.INSTALLADRESS
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public String getInstalladress() {
		return installadress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_LIB_TUNNEL.INSTALLADRESS
	 * 
	 * @param installadress
	 *            the value for WY_LIB_TUNNEL.INSTALLADRESS
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public void setInstalladress(String installadress) {
		this.installadress = installadress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_LIB_TUNNEL.RIGHTS
	 * 
	 * @return the value of WY_LIB_TUNNEL.RIGHTS
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public String getRights() {
		return rights;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_LIB_TUNNEL.RIGHTS
	 * 
	 * @param rights
	 *            the value for WY_LIB_TUNNEL.RIGHTS
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public void setRights(String rights) {
		this.rights = rights;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_LIB_TUNNEL.TOGBS
	 * 
	 * @return the value of WY_LIB_TUNNEL.TOGBS
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public String getTogbs() {
		return togbs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_LIB_TUNNEL.TOGBS
	 * 
	 * @param togbs
	 *            the value for WY_LIB_TUNNEL.TOGBS
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public void setTogbs(String togbs) {
		this.togbs = togbs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_LIB_TUNNEL.TOGNAME
	 * 
	 * @return the value of WY_LIB_TUNNEL.TOGNAME
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public String getTogname() {
		return togname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_LIB_TUNNEL.TOGNAME
	 * 
	 * @param togname
	 *            the value for WY_LIB_TUNNEL.TOGNAME
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public void setTogname(String togname) {
		this.togname = togname;
	}


	public String getOpentime() {
		return opentime;
	}

	public void setOpentime(String opentime) {
		this.opentime = opentime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_LIB_TUNNEL.ADDRESS
	 * 
	 * @return the value of WY_LIB_TUNNEL.ADDRESS
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_LIB_TUNNEL.ADDRESS
	 * 
	 * @param address
	 *            the value for WY_LIB_TUNNEL.ADDRESS
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_LIB_TUNNEL.REMARK
	 * 
	 * @return the value of WY_LIB_TUNNEL.REMARK
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_LIB_TUNNEL.REMARK
	 * 
	 * @param remark
	 *            the value for WY_LIB_TUNNEL.REMARK
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column WY_LIB_TUNNEL.UPDATETIME
	 * 
	 * @return the value of WY_LIB_TUNNEL.UPDATETIME
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column WY_LIB_TUNNEL.UPDATETIME
	 * 
	 * @param updatetime
	 *            the value for WY_LIB_TUNNEL.UPDATETIME
	 * 
	 * @mbggenerated Wed Mar 27 15:46:05 CST 2013
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

    public Long getUpdateuser() {
        return updateuser;
    }

    public void setUpdateuser(Long updateuser) {
        this.updateuser = updateuser;
    }

    public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCityName() {
		return cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public String getCountryName() {
		return countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	public String getRoadPropName() {
		return roadPropName;
	}

	public void setRoadPropName(String roadPropName) {
		this.roadPropName = roadPropName;
	}

	public String getRoadName() {
		return roadName;
	}

	public void setRoadName(String roadName) {
		this.roadName = roadName;
	}


    public RoadLib getRoadLib() {
        return roadLib;
    }

    public void setRoadLib(RoadLib roadLib) {
        this.roadLib = roadLib;
    }

    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    public Integer getAutoFlag() {
        return autoFlag;
    }

    public void setAutoFlag(Integer autoFlag) {
        this.autoFlag = autoFlag;
    }

    public String getAutoFlagStr() {
        if (autoFlag==null){
            return autoFlagStr;
        }
        switch (autoFlag.intValue()){
            case 1:
                autoFlagStr="自动";
                break;
            case 0:
                autoFlagStr="手动";
                break;
            default:
                break;
        }
        return autoFlagStr;
    }

    public void setAutoFlagStr(String autoFlagStr) {
        this.autoFlagStr = autoFlagStr;
    }

}