package com.scttsc.admin.model;

import java.math.BigDecimal;

public class DepartMent {
    
    private BigDecimal intId;
    private String name;
    private BigDecimal regionId;


    public BigDecimal getIntId() {
        return intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_DEPARTMENT.INT_ID
     *
     * @param intId the value for FRAMEWORK_DEPARTMENT.INT_ID
     *
     * @mbggenerated Wed Apr 03 16:51:44 CST 2013
     */
    public void setIntId(BigDecimal intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRAMEWORK_DEPARTMENT.NAME
     *
     * @return the value of FRAMEWORK_DEPARTMENT.NAME
     *
     * @mbggenerated Wed Apr 03 16:51:44 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_DEPARTMENT.NAME
     *
     * @param name the value for FRAMEWORK_DEPARTMENT.NAME
     *
     * @mbggenerated Wed Apr 03 16:51:44 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRAMEWORK_DEPARTMENT.REGION_ID
     *
     * @return the value of FRAMEWORK_DEPARTMENT.REGION_ID
     *
     * @mbggenerated Wed Apr 03 16:51:44 CST 2013
     */
    public BigDecimal getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_DEPARTMENT.REGION_ID
     *
     * @param regionId the value for FRAMEWORK_DEPARTMENT.REGION_ID
     *
     * @mbggenerated Wed Apr 03 16:51:44 CST 2013
     */
    public void setRegionId(BigDecimal regionId) {
        this.regionId = regionId;
    }
}