package com.scttsc.admin.model;

import java.math.BigDecimal;

public class Role {

    private BigDecimal intId;
    private String name;
    private String description;


    public BigDecimal getIntId() {
        return intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_SECURITY_ROLE.INT_ID
     *
     * @param intId the value for FRAMEWORK_SECURITY_ROLE.INT_ID
     *
     * @mbggenerated Sun Apr 28 10:49:13 CST 2013
     */
    public void setIntId(BigDecimal intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRAMEWORK_SECURITY_ROLE.NAME
     *
     * @return the value of FRAMEWORK_SECURITY_ROLE.NAME
     *
     * @mbggenerated Sun Apr 28 10:49:13 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_SECURITY_ROLE.NAME
     *
     * @param name the value for FRAMEWORK_SECURITY_ROLE.NAME
     *
     * @mbggenerated Sun Apr 28 10:49:13 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRAMEWORK_SECURITY_ROLE.DESCRIPTION
     *
     * @return the value of FRAMEWORK_SECURITY_ROLE.DESCRIPTION
     *
     * @mbggenerated Sun Apr 28 10:49:13 CST 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_SECURITY_ROLE.DESCRIPTION
     *
     * @param description the value for FRAMEWORK_SECURITY_ROLE.DESCRIPTION
     *
     * @mbggenerated Sun Apr 28 10:49:13 CST 2013
     */
    public void setDescription(String description) {
        this.description = description;
    }
}