package com.scttsc.admin.model;

import java.math.BigDecimal;

public class UserRole {

    private BigDecimal userId;
    private BigDecimal roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRAMEWORK_SECURITY_USER_ROLE.USER_ID
     *
     * @return the value of FRAMEWORK_SECURITY_USER_ROLE.USER_ID
     *
     * @mbggenerated Sun Apr 28 10:51:48 CST 2013
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_SECURITY_USER_ROLE.USER_ID
     *
     * @param userId the value for FRAMEWORK_SECURITY_USER_ROLE.USER_ID
     *
     * @mbggenerated Sun Apr 28 10:51:48 CST 2013
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRAMEWORK_SECURITY_USER_ROLE.ROLE_ID
     *
     * @return the value of FRAMEWORK_SECURITY_USER_ROLE.ROLE_ID
     *
     * @mbggenerated Sun Apr 28 10:51:48 CST 2013
     */
    public BigDecimal getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_SECURITY_USER_ROLE.ROLE_ID
     *
     * @param roleId the value for FRAMEWORK_SECURITY_USER_ROLE.ROLE_ID
     *
     * @mbggenerated Sun Apr 28 10:51:48 CST 2013
     */
    public void setRoleId(BigDecimal roleId) {
        this.roleId = roleId;
    }
}