package com.scttsc.admin.model;

import java.math.BigDecimal;
import java.util.Date;

public class User {
   
    private Long intId;
    private String name;
    private String mobile;
    private String phone;
    private String email;
    private String address;
    private String identity;
    private BigDecimal departmentId;
    private Date createtime;
    private BigDecimal deleted;
    private BigDecimal createuser;
    private String username;
    private String password;
    private Date pwdModifyTime;

    DepartMent departMent;
    City city;
    
    //冗余
    private String cityIds;
    private String countryIds;


    public Long getIntId() {
        return intId;
    }

    public void setIntId(Long intId) {
        this.intId = intId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRAMEWORK_SECURITY_USER.NAME
     *
     * @return the value of FRAMEWORK_SECURITY_USER.NAME
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_SECURITY_USER.NAME
     *
     * @param name the value for FRAMEWORK_SECURITY_USER.NAME
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRAMEWORK_SECURITY_USER.MOBILE
     *
     * @return the value of FRAMEWORK_SECURITY_USER.MOBILE
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_SECURITY_USER.MOBILE
     *
     * @param mobile the value for FRAMEWORK_SECURITY_USER.MOBILE
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRAMEWORK_SECURITY_USER.PHONE
     *
     * @return the value of FRAMEWORK_SECURITY_USER.PHONE
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_SECURITY_USER.PHONE
     *
     * @param phone the value for FRAMEWORK_SECURITY_USER.PHONE
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRAMEWORK_SECURITY_USER.EMAIL
     *
     * @return the value of FRAMEWORK_SECURITY_USER.EMAIL
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_SECURITY_USER.EMAIL
     *
     * @param email the value for FRAMEWORK_SECURITY_USER.EMAIL
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRAMEWORK_SECURITY_USER.ADDRESS
     *
     * @return the value of FRAMEWORK_SECURITY_USER.ADDRESS
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_SECURITY_USER.ADDRESS
     *
     * @param address the value for FRAMEWORK_SECURITY_USER.ADDRESS
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRAMEWORK_SECURITY_USER.IDENTITY
     *
     * @return the value of FRAMEWORK_SECURITY_USER.IDENTITY
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_SECURITY_USER.IDENTITY
     *
     * @param identity the value for FRAMEWORK_SECURITY_USER.IDENTITY
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public void setIdentity(String identity) {
        this.identity = identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRAMEWORK_SECURITY_USER.DEPARTMENT_ID
     *
     * @return the value of FRAMEWORK_SECURITY_USER.DEPARTMENT_ID
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public BigDecimal getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_SECURITY_USER.DEPARTMENT_ID
     *
     * @param departmentId the value for FRAMEWORK_SECURITY_USER.DEPARTMENT_ID
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public void setDepartmentId(BigDecimal departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRAMEWORK_SECURITY_USER.CREATETIME
     *
     * @return the value of FRAMEWORK_SECURITY_USER.CREATETIME
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_SECURITY_USER.CREATETIME
     *
     * @param createtime the value for FRAMEWORK_SECURITY_USER.CREATETIME
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRAMEWORK_SECURITY_USER.DELETED
     *
     * @return the value of FRAMEWORK_SECURITY_USER.DELETED
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public BigDecimal getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_SECURITY_USER.DELETED
     *
     * @param deleted the value for FRAMEWORK_SECURITY_USER.DELETED
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public void setDeleted(BigDecimal deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRAMEWORK_SECURITY_USER.CREATEUSER
     *
     * @return the value of FRAMEWORK_SECURITY_USER.CREATEUSER
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public BigDecimal getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_SECURITY_USER.CREATEUSER
     *
     * @param createuser the value for FRAMEWORK_SECURITY_USER.CREATEUSER
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public void setCreateuser(BigDecimal createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRAMEWORK_SECURITY_USER.USERNAME
     *
     * @return the value of FRAMEWORK_SECURITY_USER.USERNAME
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_SECURITY_USER.USERNAME
     *
     * @param username the value for FRAMEWORK_SECURITY_USER.USERNAME
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRAMEWORK_SECURITY_USER.PASSWORD
     *
     * @return the value of FRAMEWORK_SECURITY_USER.PASSWORD
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_SECURITY_USER.PASSWORD
     *
     * @param password the value for FRAMEWORK_SECURITY_USER.PASSWORD
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FRAMEWORK_SECURITY_USER.PWD_MODIFY_TIME
     *
     * @return the value of FRAMEWORK_SECURITY_USER.PWD_MODIFY_TIME
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public Date getPwdModifyTime() {
        return pwdModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FRAMEWORK_SECURITY_USER.PWD_MODIFY_TIME
     *
     * @param pwdModifyTime the value for FRAMEWORK_SECURITY_USER.PWD_MODIFY_TIME
     *
     * @mbggenerated Wed Mar 27 11:40:08 CST 2013
     */
    public void setPwdModifyTime(Date pwdModifyTime) {
        this.pwdModifyTime = pwdModifyTime;
    }

	public DepartMent getDepartMent() {
		return departMent;
	}

	public void setDepartMent(DepartMent departMent) {
		this.departMent = departMent;
	}

	public City getCity() {
		return city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public String getCityIds() {
		return cityIds;
	}

	public void setCityIds(String cityIds) {
		this.cityIds = cityIds;
	}

	public String getCountryIds() {
		return countryIds;
	}

	public void setCountryIds(String countryIds) {
		this.countryIds = countryIds;
	}
    
    
    
    
    
}